### ISSUE TITLE
[Feature Request] Add a checkbox in installer to not takeover Windows file association settings.

### ISSUE THREAD

**Issue by axzxc1236** [transmission/transmission#1013]
I installed transmission just to try it out, I already had qBittorrent installed.

After I installed transmission, it took over `magnet:` protocol association, Windows only let me choose Transmission to handle `magnet:` links, I was pissed before [I found the solution to register qBittorrent again](https://github.com/qbittorrent/qBittorrent/issues/2517).

**Comment by mikedld** [comment]
AFAIK we're not taking anything over, this was a specific goal when creating the installation package. Transmission is being registered as a choice, and one needs to select it one way or another. Not sure what happens if it's the only choice, but if Windows starts using it without prompting that's not our problem...

**Comment by ckerr** [comment]
@mikedld before this comment, 1013 was the least-recently-updated issue with a `needs clarification` label.

Is there something that still needs clarification? Is it actionable as-is? Should it be closed?

**Comment by axzxc1236** [comment]
Closed this issue because I no longer use Windows.
