### ISSUE TITLE
Ratio Bug

### ISSUE THREAD

**Issue by AlucardSama04** [transmission/transmission#1016]
Hi! I saw a bug at ratio in Transmission.
For example: I have a torrent.
Downloaded: 8.14GB
Uploaded: 4.29 GB
Ratio: 3846
Raport is Ratio because I have Transmission in Romanian
GO is GB
![Screenshot from 2019-10-09 22-41-11](https://user-images.githubusercontent.com/42693393/66514501-eca29880-eae5-11e9-90d7-da7429530c2e.png)

**Comment by strypey** [comment]
I've been having a similar issue with Transmission, using the package version from the Trisquel GNU/Linux repos (2.92/ 14714). It seemed to start with a system update a week or so ago, but this [may or may not be causally related](https://trisquel.info/en/forum/transmission-bt-client-transfer-ratios-ridiculously-high#comment-160621). After rebooting, all the torrents I had been seeding started to download again, and I had to manually verify the existing data on all of them to get them seeding again. Since then, the transfer ratio under the title of those torrents has been out of whack with the data uploaded, for example a 3.43GB torrent that has seeded 20.87GB has a ratio of "671590" (see attached screenshot: https://trisquel.info/files/transmission_screenshot-2021-09-22.png ).

**Comment by ckerr** [comment]
Fixed by #2424
