### ISSUE TITLE
Request: Start using semantic versioning starting from 4.0 release

### ISSUE THREAD

**Issue by 0x022b** [transmission/transmission#1037]
I think Transmission should start using semantic versioning starting from next major release to make it easier for end users, developers and package maintainers to see which versions are bug fix releases and which ones include new functionality.

You can read more about semantic versioning from [here](https://semver.org/spec/v2.0.0.html).

**Comment by VideoPlayerCode** [comment]
Fantastic idea. YES!

**Comment by ckerr** [comment]
I like this idea. We're obviously too late for 3.0, but rather than being in 3.xx limbo forever I think we're going to skip to v4 for the next release due to all of the rewriting that's taken place over the last 3-4 months as a result of switching from C to C++. That seems like a good time to switch to semver.

**Comment by Bananaman** [comment]
@ckerr Great, I agree! :)
