### ISSUE TITLE
[Feature Request] Configuration option to poll watch folder instead of inotify on Linux

### ISSUE THREAD

**Issue by cybershoe** [transmission/transmission#1125]
This is an issue when using a watch folder on non-local storage (NFS/CIFS), because inotify cannot operate across remote filesystems.

I would like to see a configuration item in settings.json along the lines of {"force-watch-polling": <boolean>} to fall back to the poll mechanism when inotify is available on the system, but not for the watch folder.

**Comment by goncaloalves** [comment]
In a discussion in the forum ([https://forum.transmissionbt.com/viewtopic.php?t=17960](https://forum.transmissionbt.com/viewtopic.php?t=17960)) there is a mention to a "watch-dir-force-generic" boolean option that when set to true polls instead of waiting for inotify. This option was added in version 2.9 and I've confirmed that is available in version 3.0

I believe that this addresses this issue and therefore it can be closed.

**Comment by ckerr** [comment]
Closing this issue based on the previous comment
