### ISSUE TITLE
Display name parameter lose efficacy

### ISSUE THREAD

**Issue by fjqingyou** [transmission/transmission#1144]
Sorry, my English is very poor. The following is from the Internet Translation

The DN parameter can be specified in the magnetic link. When a new task is created, the DN attribute works normally and can be displayed in the transmission task list.

But after downloading the source data, this will be replaced by the folder name, or by the file name when a single file is downloaded.

**Comment by fjqingyou** [comment]
Should not continue to use DN configuration value?

When all are changed to folder name or file name. I'm not sure who they are

**Comment by ckerr** [comment]
I am not sure if this would be a good idea or not. It does sound useful, as the display name might be more descriptive than the foldername.

However I think most users see the list of torrents and believe these to be the folder names (because they currently are the folder names). If the display name and folder name were too different from each other, I think that could lead to confusion, e.g. users looking for a particular folder but not being able to find it.

On balance I think it's less confusing if _all_ torrents, rather than just _some_ torrents, show a name that's related to their foldername. You can always rename the folder if you'd like it to have a different name.

**Comment by fjqingyou** [comment]
@ckerr 
Because my English is very poor, the following content comes from online translation

The new task does not immediately generate the corresponding folder. It's likely that you haven't downloaded anything for more than half a year after you created a new task. The progress is 0.00%.

One day, however, it suddenly has a speed, changing from the name specified by the DN parameter to the name of the folder.

However, this half a year. Hundreds or even thousands of new tasks may be added.

It is likely that the task of no speed has long been forgotten.

At this time, you can't find the original task by searching the DN keyword in your memory. Because its name has changed. And when it changes, it is not notified that its name has changed!

If the downloaded content is not native language content, you may need to manually traverse to find the original task. When you don't know a language, you may even need the help of translation!

So. It is expected that an option can be provided. The display name can take precedence over the DN parameter or the folder name, and the priority display name can be specified according to user habits
