### ISSUE TITLE
Crash when opening multiple torrents (MacOS High Sierra)

### ISSUE THREAD

**Issue by tkircher** [transmission/transmission#1179]
I've noticed multiple other people on different platforms having this same problem. When I open more than one torrent file, either at the same time, or open one when another torrent is in progress, transmission hangs hard and has to be force quit. I've since deleted transmission and moved to qbittorrent which is not only stable but actually downloads files way faster. Just saying.

**Comment by ckerr** [comment]
Glad you found another app that you enjoy!

I would ask for a crash report to help triage the problem; however, since you've already deleted the app and are being kind of passive-aggressive about the process, I'm not sure there's anywhere productive to go with this issue.

If someone else reading this experiences this issue and has information that is more actionable, please file a new bug report. Thanks!
