### ISSUE TITLE
Add support for multiple blocklists in the UI

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#1259]
We can already add multiple blocklists manually, but a feature in the UI to add several would be nice.

I recommend the following format per list:

* enable checkbox: Turns using the list on/off
* update checkbox: Turns on/off automatic updates for the list, disabled if no URL is present
* URL: (optional) the URL of the list
* file name: (optional) user specified file name for the blocklist. Can also display a file name if a file is added to the blocklists directory manually.

The file name should show a randomly generated name greyed out unless the user chooses to enter one. This is useful for managing multiple lists, as you can also display any blocklist file that isn't associated with a URL as well.

**Comment by ckerr** [comment]
Due to the history of blocklists on this project, I'm really hesitant to add any more blocklist features at all. Google can probably give more context about it but tldr is "no", the project's not adding support for multiblocklists.

But, you could probably accomplish the same thing with a small script to pull in lists from different sources and concatenate them together into a single file for Transmission to read.
