### ISSUE TITLE
Transmission cannot find files (or dirs) with spaces at the beginning of a name

### ISSUE THREAD

**Issue by amatus-** [transmission/transmission#1272]
Regression after updating from 2.94 to 3.0. If the files of the torrent file contain spaces at the beginning of the name, then the transmission cannot find these files. In the properties of the torrent file, I see paths without spaces.

Ubuntu 18.04. Transmission 3.00 (bb6b5a062e)

**Comment by mikedld** [comment]
Have you removed the torrent from the client and then re-added it? That would certainly explain it, and I wouldn't call it a regression then but a new path components sanitizing behavior introduced in response to issues like #61 and #294.

**Comment by amatus-** [comment]
After upgrading from 2.94 to 3.0 some torrents tell me "files not found". I tried to remove the torrent and add it again, but the client still does not find the files and tries to download the whole torrent again.

**Comment by amatus-** [comment]
After re-adding and downloading, the transmission saved all new files without spaces. But all old torrents are lost.

**Comment by mikedld** [comment]
I don't think they're lost as you're saying. Transmission doesn't remove the files unless you tell it to, so they may still be on your disk. I'm not sure what led to the initial issue, but removing and re-adding the torrent (or adding a new one) is going to change the names if they aren't correct enough, and having leading or trailing spaces in the name, along with a number of other cases, is certainly not correct, at least for some file systems or operating systems we support. It's unfortunate and I'm sorry that you will probably have to go and manually rename the files before Transmission will be able to find them again.

We'll take a look at why it may have happened right after the update.

**Comment by ckerr** [comment]
The issue is that 99033b067da01c646a3e12a13f8bbcd43a9dd056 sanitizes nonportable filenames into a portable form, including removing leading spaces. So if a torrent was downloaded in a version of Transmission _before_ this feature was added, the torrent contents will be on disk in a folder **with** a leading space in the name, but the new Transmission version will be looking for a folder **without** the leading space.

Unfortunately we can't just revert the change. Transmission 3.00 has been in the wild for two years now, so anyone who downloaded torrents with odd filenames during that time would get the same "disappearing file" problem when _they_ upgrade. For that reason, I'm going to mark this as 'declined' because changing the current behavior would create more problems than it solves.
