### ISSUE TITLE
Transmission cannot connect to private SSL tracker.

### ISSUE THREAD

**Issue by zebrasonmygrass** [transmission/transmission#1338]
Transmission cannot connect to private trackers that use SSL, simply stating the error "Cannot connect to tracker." As far as I can see, there are no options through which I can ignore certificate verification. I'm on Debian 18.04, running Transmission 3.00. 

As far as I can see this has been an issue for a while with no resolution - is there really no way to work around this limitation?

**Comment by anoteng** [comment]
Importing and trusting the private trackers certificate will get things
working again.

tor. 25. jun. 2020, 13:22 skrev Doruk Babalık <notifications@github.com>:

**Comment by zebrasonmygrass** [comment]
Thanks, not even sure how to get the tracker certificate.

**Comment by xavery** [comment]
Set the `TR_CURL_SSL_NO_VERIFY` variable in Transmission's environment and kiss all your certificate problems goodbye.

**Comment by dsXLII** [comment]
I think making this a user-accessible option (a checkbox to disable SSL cert path validation) would be useful, if admittedly a bit hard to document because users seem to freeze up whenever encryption is mentioned. Wouldn't want it to become "oh just uncheck this and everything magically gets better" because there absolutely are use cases where you'd want cert validation.

**Comment by ckerr** [comment]
Is this issue the same as https://github.com/transmission/transmission/issues/1876 ? They seem the same, but this one seems to precede the letsencrypt changes

**Comment by GScottElshaw** [comment]
> Is this issue the same as #1876 ?

Yes.
