### ISSUE TITLE
add ExecStop to transmission-daemon service file

### ISSUE THREAD

**Issue by sandrotosi** [transmission/transmission#138]
Hello,
as reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831467 , without an ExecStop systemd brutally kills transmission-daemon; the reported suggests

```
ExecStop=/bin/kill -s STOP $MAINPID
```

and i'm going to apply that to the debian package

**Comment by mikedld** [comment]
This doesn't look like a correct solution. My understanding is that SIGSTOP is used to pause the process, with ability to unpause later on by sending SIGCONT, not to stop it in the sense of termination.

[systemd.service](https://www.freedesktop.org/software/systemd/man/systemd.service.html):

>  `ExecStop=`
> ... If this option is not specified, the process is terminated by sending the signal specified in `KillSignal=` when service stop is requested ...

[systemd.kill](https://www.freedesktop.org/software/systemd/man/systemd.kill.html):

> `KillSignal=`
> ... Defaults to `SIGTERM` ...

Hence I'm deducing that there should be no need in specifying ExecStop explicitly as default behavior suits us.

Looking at the provided Debian bug report, I see service status is reported as:

> Active: failed (Result: signal) since Sat 2016-07-16 18:14:42 IST; 1s ago
> Main PID: 3145 (code=killed, signal=SEGV)

This means that process dies because of segmentation fault, not because systemd "brutally kills" it. Right course of action here is to get a backtrace and see what it is all really about.

**Comment by mikedld** [comment]
Closing for the lack of response.
