### ISSUE TITLE
Can we have an option to not create a Folder 

### ISSUE THREAD

**Issue by hk3wx** [transmission/transmission#1440]
Every download creates a folder, can we have an option to disable that.

**Comment by jln1925** [comment]
Pretty sure this deals with the same thing. I have a lot of files that are sorted into folders on my drive (e.g. "Video Name (2020)/Video.mkv"). A lot of torrents files are made with a single file in a folder ("Video-bitrate-info/Video-info.mkv). I wish there was a way to prevent Transmission from creating that folder. I just switched and there are a lot of torrents I can't move over because even when I point them to the folder, they keep looking for that subfolder and not finding them.
This would definitely be appreciated.

**Comment by pmarsden** [comment]
It only creates a folder if the torrent comes as a folder.
That is working as expected, I have both on my current boxes.

**Comment by hk3wx** [comment]
> It only creates a folder if the torrent comes as a folder.
> That is working as expected, I have both on my current boxes.

And that is the issue, because we want an option to not create that folder as 
almost every other torrent client has. So they don't create a folder but instead only download 
the content.

**Comment by pmarsden** [comment]
Its not an issue, its working correctly, the folder is part of the torrent.

**Comment by anaveem** [comment]
As the OP stated it's a option AKA feature request. The option is missing in Transmission but available in other clients like ruTorrent ("don't add torrent's name to path") and qBittorrent ("don't create subfolder"). 

And it's a much needed option for cross-seeding.

**Comment by pmarsden** [comment]
I have no issue at all cross seeding torrents in Transmission.
I do it all the time - so how is it a "much needed option" to do this ?

**Comment by anaveem** [comment]
I'm referring specifically to torrents from 2+ trackers, where one torrent has the file in a subfolder, and another has the file "naked" or "folderless" in the download directory. You can't cross-seed the file because it resides in different folders. The only workaround is to create symlinks or manually change the download directory of the folder-less file. As you can imagine, when seeding hundreds of torrents, nobody wants to do these things manually for each file in order to cross-seed, and it's completely unnecessary with clients like ruTorrent and qBittorrent. 

Right now, I have at least 20 torrents that I can't cross-seed because they are not in a subfolder.

I think this feature has been requested for many years in some other forums, but since there is no single phrase to describe the option, it's hard to identify them. As I mentioned, ruTorrent calls it "don't add torrent's name to path" and qBittorrent calls it "don't create subfolder". 

Please let me know if it still isn't clear why this feature is desirable.

**Comment by hk3wx** [comment]
> I'm referring specifically to torrents from 2+ trackers, where one torrent has the file in a subfolder, and another has the file "naked" or "folderless" in the download directory. You can't cross-seed the file because it resides in different folders. The only workaround is to create symlinks or manually change the download directory of the folder-less file. As you can imagine, when seeding hundreds of torrents, nobody wants to do these things manually for each file in order to cross-seed, and it's completely unnecessary with clients like ruTorrent and qBittorrent.
> 
> Right now, I have at least 20 torrents that I can't cross-seed because they are not in a subfolder.
> 
> I think this feature has been requested for many years in some other forums, but since there is no single phrase to describe the option, it's hard to identify them. As I mentioned, ruTorrent calls it "don't add torrent's name to path" and qBittorrent calls it "don't create subfolder".
> 
> Please let me know if it still isn't clear why this feature is desirable.
> 
> **Edit:** I've switched to qBittorrent. Sadly, Transmission is too barebones in features for me.

I did the same.
closed.

**Comment by smiba** [comment]
Running into the same issue, making Transmission useless to the majority of the files I have sadly.

**Comment by omriamos** [comment]
Same here. Until this missing feature issue is resolved, I will not be using Transmission.

**Comment by pmarsden** [comment]
This should have been closed a long time ago.
Its not a missing feature, so I guess you'll be using somehting else.
As has already been noted, its working correctly, breaking a torrents layout is not a "feature". 
If a torrent was created in a folder (or folders) it will be downloaded in the same folder(s), if it was created without, then it wont.

**Comment by anaveem** [comment]
pmarsden, no offense, but you keep being dismissive instead of acknowledging that transmission is lacking a feature that other torrent programs have and users want, something that is actually driving users away from Transmission. Honestly, this is the kind of behavior I would expect from snotty, high level execs from Adobe, not from people who share open source programs and seek user feedback.

**Comment by eUnisk** [comment]
I googled this question and I found this closed issue here. Surprising developers won't add it as a feature. When people say, I need it, and other clients have it. They say, no, you don't need it. How does it feel being a king in your territory?

**Comment by zoostorm1** [comment]
Being King feels great to me, YMMV.
