### ISSUE TITLE
"Corrupt DL" label is not as easy to understand as it should be

### ISSUE THREAD

**Issue by feisar** [transmission/transmission#154]
Transmission 2.92 (14714)
Ubuntu MATE 16.04

I use the Transmission Daemon with the web interface and when torrents have been seeding for a while (long after I've finished downloading them), I start to see 'X MB Corrupt' on the torrent info screen.

* Running 'Verify Local Data' doesn't appear to have any affect.

Here is an example output:

```
ID     Done       Have  ETA           Up    Down  Ratio  Status       Name
   2   100%    1.88 GB  Done         4.0     0.0   28.7  Seeding      linuxmint-18.1-mate-64bit.iso
Sum:           1.88 GB               4.0     0.0
```

```
NAME
  Id: 2
  Name: linuxmint-18.1-mate-64bit.iso
  Hash: 8c7254fe5c171a88c8cad8e60d000ec65f2a60f6
  Magnet: magnet:?xt=urn:btih:8c7254fe5c171a88c8cad8e60d000ec65f2a60f6&dn=linuxmint-18.1-mate-64bit.iso&tr=https%3A%2F%2Ftorrents.linuxmint.com%2Fannounce.php

TRANSFER
  State: Seeding
  Location: /home/shared/downloads
  Percent Done: 100%
  ETA: 0 seconds (0 seconds)
  Download Speed: 0 kB/s
  Upload Speed: 4 kB/s
  Have: 1.88 GB (1.88 GB verified)
  Availability: 100%
  Total size: 1.88 GB (1.88 GB wanted)
  Downloaded: 1.91 GB
  Uploaded: 54.96 GB
  Ratio: 28.7
  Corrupt DL: 22.02 MB
  Peers: connected to 7, uploading to 3, downloading from 0
```

**Comment by ScoreUnder** [comment]
I've been seeing this too (ver 2.93). I'm pretty sure it started somewhat recently.

In the end Transmission just ends up just blocking every peer and the download stops until transmission is restarted.

**Comment by bigretromike** [comment]
2.93 with uTP enabled. Same thing here. After seeding for some time same file get corrupted - over and over again. When seeing audit notice that transmission is overwriting files that are being seeded! - which shouldn't be the case !

**Comment by ckerr** [comment]
"Corrupt DL: 22.02" means that when  you were downloading the torrent, you got some bad data from someone and it didn't pass the checksum test. That number is just the count of excess download bytes that were caused as a result of that. It doesn't mean that you have corrupt data on the disk, which is why the number doesn't change when you try to verify local data.

This is why the text "DL" is added there, but even so the text could probably be clearer. As usual it's a tradeoff between conciseness and clarity.

PRs are welcome for concise text that is more understandable than "Corrupt DL:"
