### ISSUE TITLE
Qt not showing running torrents

### ISSUE THREAD

**Issue by thezak48** [transmission/transmission#1556]
I am running transmission on Windows and the Qt Client is not showing anything yet the web interface is.

Also it seems that transmission is not taking any settings as I have disabled the access whitelist yet it is still blocking me from accessing the web interface from a separate pc

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.

You're most probably running two Transmission sessions. Did you choose to install the daemon? If so, that would probably be your other session. Either uninstall the daemon component, or connect to the daemon session from the Qt client instead of starting a new session.
