### ISSUE TITLE
[Feature Request][macOS] Add sort mode — by Uploaded/Downloaded ratio

### ISSUE THREAD

**Issue by magicgoose** [transmission/transmission#159]
I think it's simple and very useful.
BTW all other torrent clients I remember using had this feature.
Right now it's not present at least in ~~~OS X~~~ macOS version of Transmission.

Some explanation on forum: https://forum.transmissionbt.com/viewtopic.php?f=3&t=18321

**Comment by mikedld** [comment]
Related to [TRAC-4363](https://trac.transmissionbt.com/ticket/4363).

**Comment by magicgoose** [comment]
> You can already sort by progress, which includes ratio *for seeding transfers*. Including a separate ratio sort seems like overkill to me.

btw, if adding another sort order is somehow against religion, then maybe counting partial-but-seeding transfers as seeding will be a solution too.

**Comment by Coeur** [comment]
For seeding torrents, the "Sort by progress" does just that.
For non-seeding torrents, if we were to add a "Sort by ratio", how do you expect it to get arranged?

A. seeding and non-seeding torrents are mixed together (ratio-only sorting) [fair request]
B. seeding and non-seeding torrents are separated (completion then ratio sorting) [in that case, best to stick with "Sort by progress"]

But there is presently a macOS UI incompatibility: we do not display the ratio at all for non-seeding torrents, so they would appear mixed up randomly.
So to me, this feature request is to be rejected until we first allow displaying "ratio" of non-seeding torrents in both UI styles (normal and minimised style).

As this issue is tagged "feature disparity", kindly offer a screenshot of GTK or web client Transmission torrents ordered by ratio, including non-seeding torrents.

**Comment by magicgoose** [comment]
Sorry for the snarky tone in my past messages, I should have calmed down before posting on the Internet. Regarding the original issue, I'm no longer using nor interested, it's fine to close the issue if it's actually working as intended.
