### ISSUE TITLE
why does Transmission have fewer peers than uTorrent?

### ISSUE THREAD

**Issue by lovk1y** [transmission/transmission#1613]
i have tested two transmission apps, for Synology (DSM) and for PC (Windows 10) and they are both have slower downloading speed compared to uTorrent on PC (Windows 10). the problem is that Transmission has fewer peers than uTorrent (see the attachment).
why is that and how it can be fixed?
all the tests were at the same time and with the same torrent file, of course. PEX, DHT, LPD are on.
![utorrent_vs_transmission](https://user-images.githubusercontent.com/58986294/106392431-d8815980-6402-11eb-8748-e136f85a4cb6.jpg)

**Comment by avivmu** [comment]
Both of them are torrent clients. The number of peers depends on the torrent itself. Note that when you open the same torrent from both clients at the same time you are competing for download speed between each other. It's hard to test it but maybe open one client and see the number of peers, then close it and immediately open the other client and check number of peers. They should be the same

**Comment by hewwra** [comment]
I had that problem too, I fixed it by changing some settings.
I changed several so I can't say for sure which one did it but I suspect that it got fixed when I disabled utp, or maybe it was because I enabled encryption.
All the settings I changed are in the screenshot, I use the Transmission Remote GUI

![Screenshot 2021-02-06 220739](https://user-images.githubusercontent.com/26254390/107129786-542e4b00-68c8-11eb-8aec-e7889e579ab4.png)

**Comment by ValZapod** [comment]
@hewwra did you really disable DHT? That means you have 0 (zero) peers in most cases.

**Comment by hewwra** [comment]
@ValZapod I only use private trackers so there is no need for DHT to be enabled for me.

**Comment by Anuskuss** [comment]
I've also noticed this. I run Transmission on my server and have some torrents sitting around at 0% and today I fired up qBittorrent on my PC to test this one torrent and it found 3 peers (one of which was my server) very quickly. The trackers are identical so what's the difference here? Is it LSD (Transmission only has LPD)?

**Comment by sserdda-liamE** [comment]
µTorrent's connectivity is godly.
Asking another programmer to match Ludvig Strigeus's accomplishment is like asking an engineer to match Elon Musk's.  Some things are just not repeatable by mere mortals.

**Comment by ValZapod** [comment]
> µTorrent's connectivity is godly.

In practice Tixati is sometimes batter and does not crash or outright does not load on even slighly bigger torrent files.

**Comment by sserdda-liamE** [comment]
> Also 64 bit.

If your torrent client is using more than 2GB RAM, something is wrong.
If your torrent client is using more than 300MB of RAM, something is wrong.

**Comment by ckerr** [comment]
My theory is that Transmission's implementation of the BitTorrent protocol has not kept up with all the innovations that have happened in the protocol, e.g. some of the changes added in http://bittorrent.org/beps/bep_0052.html.

Some of these issues can be found by searching for 'bep' in the issues, https://github.com/transmission/transmission/issues?q=is%3Aissue++bep.

As you've no doubt noticed, Transmission is maintained by a few people who have significantly less free time than they used to :smile: so the project goes through spurts of productivity and longer dry spells. If someone would like to contribute code to improve protocol support, I personally would be very happy to help with code review & suggestions.

That said, this issue is the wrong place for followup discussion about refreshing the protocol code. I'm going to close this issue because it's in the same category of "why is my download slow?" questions -- there are dozens of reasons, any of which could apply to a specific person's situation, and as such it's not an issue that can ever be "fixed" since even the most robust app will still behave badly under the wrong circumstances. It's more productive to have issues address specific problems that can be fixed, thus eventually chipping away at the list of situations where the app can misbehave.

**Comment by FergoTheGreat** [comment]
Anyone saying that there isn't a problem has their head in the ground. I tried downloading 3 torrents on Transmission. Trackers said that each had many (30-60) peers. On Transmission I was getting 1/0/0 peers respectively, and 80KB/s on the one with a single peer. I tried reloading and checking network settings multiple time and nothing helped. With qBittorrent I instantly had 10/2/1 peers and each torrent was downloading between 2-3MB/s.
