### ISSUE TITLE
2 torrents with same target folders/files handled correctly?

### ISSUE THREAD

**Issue by EdwinKM** [transmission/transmission#1620]
Unfortunately i can not really test if this is a problem. Please close otherwise.
Sometimes you add multiple torrents which contain the same folders or files. Files are stored in the root of "incomplete".
So, if two different torrents are containing the same file(name) they both will write to the same target?
Maybe it is better to create a unique subfolder for each torrent (hash comes to mind)

After completion it will be moved to "Downloads". Moving the unique foldername will always work, dropping this subfolder at this point can again create conflicts

**Comment by Anuskuss** [comment]
I had two torrents with the same name and lots of file name collisions and Transmission would sometimes write the data of both torrents into the same file, thereby corrupting the file. So this is definitely an issue if you don't pay attention (because you can always just rename the torrent before starting it).

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #1200.
