### ISSUE TITLE
Portable version of Transmission CLI utilities?

### ISSUE THREAD

**Issue by redbrain** [transmission/transmission#1627]
I'd love to be able to do some simple things like `transmission-show` or other things from the CLI from a flashdrive.
For this to happen, I can't depend on the fact that all the required libraries are on the machine the flashdrive's in.
Are there portable builds of the Transmission CLI utilities, or is it possible to make things like `transmission-show` run portably?
Thanks in advance.

**Comment by ckerr** [comment]
It probably is possible, and I'd love it if any downstream project wants to take this on!

The Transmission project is very shorthanded right now and there are no maintainers who are going to work on static builds of CLI utilities, so this is something that would need new volunteer work in order to happen.

I love the idea; we just don't have resources for it on the project.
