### ISSUE TITLE
MacOS extended attributes "com.apple.quarantine"

### ISSUE THREAD

**Issue by zachary822** [transmission/transmission#164]
Transmission sets the "com.apple.quarantine" flag, which usually isn't a problem per se, but it triggers the 'Verifying "[FILENAME]"' dialog every time I click on files and folders downloaded through transmission. Files downloaded by browsers also have that flag set, but it never triggers the verify file dialog. If you use the `xattr -p com.apple.quarantine [FILENAME]` to check the flag, the time and uuid is not set on the flag for files downloaded through Transmission.

**Comment by mikedld** [comment]
Transmission doesn't itself set "com.apple.quarantine" flag. Related to [TRAC-6103](https://trac.transmissionbt.com/ticket/6103).

**Comment by mikedld** [comment]
Turns out I was wrong and Mac client [sets quarantine attribute](https://github.com/transmission/transmission/blob/fa504fb27f2840561dbec20bda55a99d16a9808f/macosx/Torrent.m#L1864) after all, my appologies. I cannot agree on "time and uuid is not set" though, as time is "set automatically to the current date and time if this key is not present in the caller's dictionary" (and Transmission doesn't add it to the dictionary) and UUID (quarantine event ID) is present for me after the referenced code execution (but it seems to be "optional" anyway). I noticed though that the attribute is set even before Transmission finishes the download (Transmission itself only sets it after download is complete), and when this happens it indeed is missing the UUID (at least in my limited testing). I also never saw any "Verifying [FILENAME]" messages, so... leaving this as invalid for the time being.
