### ISSUE TITLE
[question] How to maximize RAM usage and minimize disk I/O 

### ISSUE THREAD

**Issue by zilexa** [transmission/transmission#1640]
When you have 8-12GB RAM available (of 32GB) and want to absolutely minimise the I/O on the disk (SSD, BTRFS), how would one configure Transmission to use as much RAM as available? 
I used to have `disk cache size` set to `6144` (6GB). But I read in some forum, this setting is actually a `per peer` setting. The documentation does not state so [here](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#misc): 

>cache-size-mb: Size (default = 4), in megabytes, to allocate for Transmission's memory cache. The cache is used to help batch disk IO together, so increasing the cache size can be used to reduce the number of disk reads and writes. Default is 2 if configured with --enable-lightweight. 

**My 2nd question: what does this cache mean? Per torrent, per peer or overall?**

I have a 500/500 connection and set it to 20 downloads, but now I realize that might not be smart if I want as much torrents to be completed within my RAM. So this morning I reduced it to 2 downloads max at the same time. 
I hope Transmission will download entire files pieces to the RAM, combine them into the actual file and then write in 1 go to disk.

If I am downloading 2 files of 8GB each, I would want qB to still use 8GB RAM in total, just write parts of the files to disk to prevent the cache from being 100% full. What I want to prevent is the cache being constantly full and the disk now being used without cache for each downloaded piece.

How would one go about to configure Transmission in such a way to minimize disk writes and maximize RAM usage? I rarely use much RAM, so most of it is doing nothing, which is a waste.

**Comment by zilexa** [comment]
Just to add, I did a test. 

Situation: 
1. 9 of 32 GB RAM in use. 
2. No torrents in transmission, set disk cache to 8192 (8GB).
3. restart transmission, add a single torrent of 26GB movie. 

What happens: 
1. RAM uses slowly increases while downloading, seems to be 1.5x to 2x the size of what Transmission has downloaded. 
2. This happens up to ~2GB RAM usage.
3. Then suddenly an amount is written to SSD (monitored) and RAM usage drops. 
4. This keeps repeating itself. 

Is this the host OS (Ubuntu 20.10) forcing its own caching policy? Forcing Transmission to write to disk? This way, I can never get Transmission to use more than ~2GB. Which is acceptable I guess, but I still have plenty RAM available.

**Comment by xavery** [comment]
> 
> > cache-size-mb: Size (default = 4), in megabytes, to allocate for Transmission's memory cache. The cache is used to help batch disk IO together, so increasing the cache size can be used to reduce the number of disk reads and writes. Default is 2 if configured with --enable-lightweight.
> 
> **My 2nd question: what does this cache mean? Per torrent, per peer or overall?**

This setting is applied per a Transmission "session", i.e. one Transmission program. The cache is allocated when the session is created, which happens when the program starts. The relevant code is in [cache.c](https://github.com/transmission/transmission/blob/master/libtransmission/cache.c) if you want to have a look at how it operates.

**Comment by zilexa** [comment]
Thanks for confirming, I am no developer at all. 
So unless it is a bug,  Transmission can't help it that after 2GB of RAM, it gets written to disk, even if I set 8GB of cache. I think the OS is forcing that somehow, due to memory management.

**Comment by xavery** [comment]
> I think the OS is forcing that somehow, due to memory management.
Doubtful. Why would it? As long as the data for what you're downloading stays in the `tr_cache` structures, the OS has no idea that you want to write it to disk at all. If the OS actually needed to "force" a process to "give" more memory back to the OS, it would just kill it, which is most certainly not the case here. The OS I/O buffers have no relation at all to the Transmission cache : these only come into play when the cache is flushed. Perhaps what you're trying to do would be achievable by setting Transmission's internal caching to minimal size (I'm not sure if setting it to 0 disables it entirely), and tweaking OS settings in order to enlarge the I/O buffers.

Nevertheless, what you're describing could just as well be the expected behaviour. If you have a look at the [calcRuns](https://github.com/transmission/transmission/blob/master/libtransmission/cache.c#L131) function, you'll see that some cached blocks have priority over others : there is logic in place that decides what gets flushed first. Unfortunately, I'm not competent enough to comment on the validity of this particular algorithm, I just wanted to stress that it exists.
