### ISSUE TITLE
Reproducible Builds: User-Agent contains build system kernel version

### ISSUE THREAD

**Issue by kpcyrd** [transmission/transmission#1696]
The reproducible builds [rebuild system](https://reproducible.archlinux.org/) for Arch Linux has detected that the binaries contain a user agent that records the kernel version of the build system instead of using the version that is actually in use by the system running transmission:

```
│ │ │ -User-Agent: Linux/5.7.9-arch1-1, UPnP/1.1, MiniUPnPc/2.0
│ │ │ +User-Agent: Linux/5.11.16-arch1-1, UPnP/1.1, MiniUPnPc/2.0
```

This prevents independent verification of the compile step because the verification system can't ensure the same kernel version.

I've tried to prepare a patch but couldn't figure out where this is actually coming from.

Thanks for looking into this!

**Comment by ckerr** [comment]
Hi @kpcyrd, my first guess is that this is coming from a dependency rather than the Transmission code itself.

[This code](https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/minisoap.c#L93) in miniupnp looks like the same format string you're seeing:

>  "User-Agent: " OS_STRING ", " UPNP_VERSION_STRING ", MiniUPnPc/" MINIUPNPC_VERSION_STRING "\r\n"

Please report this upstream to the miniupnp maintainers.

I'm going to close this issue here since it's not something that can be fixed in Transmission's codebase, but if this is fixed upstream please file a new issue or PR here in Transmission to ensure we bump our deps to the new version. Thank you!

**Comment by kpcyrd** [comment]
@ckerr thanks! I sent a patch upstream: https://github.com/miniupnp/miniupnp/pull/547

**Comment by kpcyrd** [comment]
@ckerr miniupnp has commited a fix: https://github.com/miniupnp/miniupnp/commit/08ae9e9e71b13c1c09c9e10e315bafe999b1ad55 (I'm not proficient enough in C to say much about it though, including if it fixes the issue)

**Comment by mikedld** [comment]
The fix was made for miniupnpd (not miniupnpc) and is unlikely to help your case.
