### ISSUE TITLE
merge with cfpp2p fork?

### ISSUE THREAD

**Issue by blshkv** [transmission/transmission#1743]
Hi, first of all, thanks for the wonderful bt software!

I'm an Entware user and realised that there is a fork for transmission which seems fixed few bugs (https://sourceforge.net/p/transmission-daemon-cfp/wiki/Additional%20Feature%20Summary/), but stays on 2.x version.
I can also see that @cfpp2p is active here and reported multiple issues, but many of them are still opened.

So all this comes to a hard decision. Should I install the fork with lesser features (probably), but more "stable" or I should go with the official 3.x which was released long time ago (last year) and has  161 commits (bug fixes?) since then?

Perhaps, you should just merge fixes and take @cfpp2p onboard, so he could submit all fixes directly?
Thanks for all your hard work again!

**Comment by Pentaphon** [comment]
I wish, because the official version needs to have more people who develop for Windows contributing to it. 

I use his daemon fork but I'm willing to use 3.x if the project started releasing more versions instead of the 1-2 year releases we currently get. We need more people working on this project and I'm surprised that despite working on the main 3 platforms and moving to github that the project hasn't picked up the pace yet.

**Comment by depler** [comment]
@Pentaphon here is another build for Windows: https://github.com/depler/transmission. It is based on version 3.00 with minimum fixes. I'm using this for months without any problems. It is also uses native Visual Studio linkage, so there are no any cygwin dependencies.

I don't really like official repo because of dozens binaries, rare updates and outdated UI.

**Comment by Pentaphon** [comment]
Thanks @depler but I'd rather use something that has had more usage from the community before I start running it with my hundreds of torrents.

**Comment by ckerr** [comment]
https://github.com/cfpp2p/transmission hasn't been updated since March 2021. Given the high volume of code churn in `transmission/transmission` since then as the project moves to C++, the idea of an outright merge seems like it would be overwhelmingly complex just from a logistics standpoint..

If there are fixes or features that people would like to include and are willing to do the patchwork for it, I'd be happy to listen. If you want to sound out the maintainers before putting in porting work, please file an issue for the particular change with a description and an estimate on how big of a patch you expect it to be.

I'm closing this issue since the original question is "merge with cfpp2p fork" and that's logistically difficult, but as mentioned above, that shouldn't be interpreted as an unwillingness to discuss changes.

**Comment by Pentaphon** [comment]
Yes I think this is more up to @cfpp2p than anybody else. He will have to submit PRs into the main project or just continue his daemon-only fork if he wants.

**Comment by blshkv** [comment]
can you review his fixes and merge it? It would be pity to lose all his hard work.

Also, please release a new version so that all user would receive your fixes. Thanks!

**Comment by blshkv** [comment]
@Pentaphon as I mentioned, @cfpp2p participated in few PRs back in 2017 and 2018. But you never merged it:
https://github.com/transmission/transmission/pull/769
https://github.com/transmission/transmission/pull/654
https://github.com/transmission/transmission/pull/137

He also opened multiple bug reports which were never been addressed

**Comment by Pentaphon** [comment]
> @Pentaphon as I mentioned, @cfpp2p participated in few PRs back in 2017 and 2018. But you never merged it: #769 #654 #137
> 
> He also opened multiple bug reports which were never been addressed

None of those PRs are his, and as you can see, we have more bug reports than ever for this project. I think @ckerr is doing as much as he can on his free time considering he's currently moving the project from C to C++, but we also have to encourage other people to step up and submit more PRs if we want Transmission to move forward. Hopefully @cfpp2p and other people reading this become more active on github to ensure we get viable releases.

**Comment by ckerr** [comment]
> @Pentaphon as I mentioned, @cfpp2p participated in few PRs back in 2017 and 2018. But you never merged it:
> #769

This has gotten some discussion recently; today, actually.  See #2261.

Also, I don't think this is fair to cite here in the context you're using where you imply that it was just ignored. I responded to that comment three times explaining that I disagree with the feature.

> #654

I don't think vjunk ever finished the PR? Are you also upset that I didn't merge incomplete PRs?

> #137

I don't think I had any commits on the project at all in 2018, when that PR was filed. I don't see the point of bringing this up either in the context of "but you never merged it."

> He also opened multiple bug reports which were never been addressed

Searching for open tickets with cfpp2p, looks like they were 2017 / 2018, which... as mentioned before, I wasn't super active on the project at the time.

This list of PRs is not fair criticism since they are issues that were incomplete, or that I wasn't around for, or that I disagreed with in-ticket. But even if the _were_ valid... I'm human, and I have periods where I'm more interested in the project and less interested in the project, and I've absolutely let issues / PRs slip through the cracks. Attacking me for it like this is not productive.

So, ground rules going forward: as I already said,

> If there are fixes or features that people would like to include and are willing to do the patchwork for it, I'd be happy to listen. If you want to sound out the maintainers before putting in porting work, please file an issue for the particular change with a description and an estimate on how big of a patch you expect it to be.

The rest of this "but you didn't merge this PR five years ago when you weren't here" noise is ... just noise IMO.
