### ISSUE TITLE
Do not hash rpc-password in settings.json

### ISSUE THREAD

**Issue by sprnza** [transmission/transmission#1821]
I have rpc-auth disabled and use ansible to start and configure transmission-daemon. Due to transmission-daemon always hashes `rpc-password` (even if it's an empty string `"rpc-password": ""`) the local and the remote settings.json are always different which cases ansible always reupload the settings.json (with `when: settings_json.changed`)
Is there a way to disable rpc-password hashing somehow? Or tell transmission-daemon not to hash empty `rpc-password`?

**Comment by ckerr** [comment]
Storing the password in plaintext seems like a very risky idea in general, though.

I'm not sure I fully understand your use case about ansible. Is there some other way that we can avoid conflicting files?

**Comment by sprnza** [comment]
> Storing the password in plaintext seems like a very risky idea in general, though.
yes it is. I suggest not to hash it if it's an empty string.
> Is there some other way that we can avoid conflicting files?
ansible reports back if a file has been changed and it's possible to use this report to take another actions later on (restart transmission). As soon as `rpc-password` always changes (random string is being prepended) ansible always restarts transmission.

**Comment by damcav35** [comment]
Hello,
Maybe you can avoid this by using Ansible fact /var with the hashed value of your password, and use it in your setting.json templated file.
The hashing algorithm is probably available "somewhere" in the code :-)

**Comment by killemov** [comment]
> I have rpc-auth disabled and use ansible to start and configure transmission-daemon. Due to transmission-daemon always hashes `rpc-password` (even if it's an empty string `"rpc-password": ""`) the local and the remote settings.json are always different which cases ansible always reupload the settings.json (with `when: settings_json.changed`) Is there a way to disable rpc-password hashing somehow? Or tell transmission-daemon not to hash empty `rpc-password`?

To be clear, does this result in an endless loop?

**Comment by sprnza** [comment]
> To be clear, does this result in an endless loop?

Nope, just inconvenience because ansbile "sees" the settings.json file always being updated.

**Comment by ckerr** [comment]
I am really not understanding this issue and need some clarification. Why are the local and the remote settings.json are always different? What if you just stored the same hashed password in both `settings.json` files?

**Comment by damcav35** [comment]
Hi, could you link us the hashing function ? This is indeed an easy fix
    Le vendredi 11 février 2022, 07:51:03 UTC+1, Charles Kerr ***@***.***> a écrit :  
 
 


I am really not understanding this issue and need some clarification. Why are the local and the remote settings.json are always different? What if you just stored the same hashed password in both settings.json files?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ckerr** [comment]
Closing due to lack of response + the suggestion would be a potential security risk.

**Comment by nodiscc** [comment]
I am also affected by this "problem" (transmission configured from ansible, setting the password through a [template](https://github.com/nodiscc/xsrv/blob/master/roles/transmission/templates/etc_transmission-daemon_settings.json.j2#L51) in its unhashed form, the password is overwritten with the hash every time transmission-daemon is restarted, hence the next ansible run will overwrite it again, restart transmission-daemon, etc...).

I admit the solution proposed here (disabling hashing) is not satisfying.

But this should be fixable on the ansible role side:
- store the hash alongside the password in the ansible vars file

```yaml
# host_vars/my.example.org.vault.yml
transmission_password: CHANGEME
transmission_password_salt: CHANGEME
```

- modify the template to use a [filter](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html), for example

```
"rpc-password": "{{ transmission_password | ssha1('transmission_password_salt') }}",`
```

However there are 2 remaining question/problems I have not explored:
- Can we use any string as the salt, or does it need to be a specific length? (I think it needs to be 64 characters long [[1]](https://github.com/transmission/transmission/blob/8a35aa09036edb887b4f8d463e3666af47ba6d29/libtransmission/crypto-utils.cc#L92)?)
- Ansible has a [built-in `sha1` filter](https://docs.ansible.com/ansible/devel/collections/ansible/builtin/sha1_filter.html), but it does not take a salt parameter, so how should we apply the salt? In some programs the salt is simply appended at the end of the password, then the resulting string is hashed with SHA1. I don't know if that's the case here as I'm not proficient in C++ and there are not many comments in the code.

Closing this issue is totally OK since it's not a problem in transmission, however any advice on how to properly implement this is welcome.

You can find the role [here](https://github.com/nodiscc/xsrv/tree/master/roles/transmission)
