### ISSUE TITLE
download data from web interface

### ISSUE THREAD

**Issue by nschloe** [transmission/transmission#192]
After having added a torrent to the web interface and watched it complete, you always have to go back to `scp` & friends to actually get the data from the server.

I'd be great if one could actually get the data via a link from the web interface.

**Comment by mikedld** [comment]
Sorry but this is unlikely to happen. Transmission's web serving capabilities aren't meant for general-purpose use. Also, this will only work for separate files but not directories (and adding archiving functionality doesn't sound like a good idea). If you want to download files through the browser, set up a web server. Other options include downloading to network share instead of local disk.

**Comment by johnlane** [comment]
Just wanted to +1 this idea, I was looking for exactly this today. A simple addition to the context menu popup "Download zip" which downloads a zip of the torent's downloaded data. Not a browsing capability just leveraging the existing UI with an additional menu option.

If the zip idea is consiered a no-no then just having a "download" option on the individual items listed on the "files" pane ( select torrent, press "i" icon and then "files" tab ). 

Again not looking for a way to browse downloaded data beyond what is already available. Just a way to download what the existing UI shows you.

**Comment by fred727-temp** [comment]
Just to "up" this idea...
