### ISSUE TITLE
`doneDate` is `0` for a already completed torrent

### ISSUE THREAD

**Issue by Trim21** [transmission/transmission#1971]
If I downloaded a torrent with another download tool and add it to transmission, the `doneDate` is always 0 instead of the added time or verified time. 

Is this a bug or a expected behavior?

**Comment by valcomm** [comment]
If it's not 0, how would you separate torrents that you had and added from the downloaded ones?

**Comment by valcomm** [comment]
What would be gained by making `doneDate` to become 'addedDate` (or some other time) for such cases?

Now the meaning is: time when content is done (downloaded and ready to be used).  Or if it wasn't downloaded, then instead of some heuristic (the latest file modification time?  added time?  verified time?) it holds a clear known value.  I'm trying to understand the reason for the change (and why would I have to update all my scripts)

**Comment by Trim21** [comment]
I'm expecting it's set to when transmission knows all wanted data is available, so it's verification time in this case.

But current there's no detial document (spec and source comments) nor another issue about this, I m wondering is this a bug or expected behavior.

**Comment by ckerr** [comment]
TBH it's unintended behavior, rather than something clever for scripts to distinguish between torrents that were downloaded in Transmission vs another client. My first no-context expectation as a user would be same as @Trim21's, that the doneDate would reflect whatever time it was when Transmission first realized that there was nothing left to download in the torrent.

I'm leaning towards making this change. @valcomm tell me more how it would break your scripts, i.e. why you think it would be better to leave as-is? Would checking downloadedEver not work just as well?

**Comment by valcomm** [comment]
> 
> 
> I'm leaning towards making this change. @valcomm tell me more how it would break your scripts, i.e. why you think it would be better to leave as-is? Would checking downloadedEver not work just as well?

Right now I operate under assumption that `doneDate` provides indication of three content states:
downloaded - set to the timestamp when it was done
downloading - set correctly to some null (0) value
not being done at all by transmission - set again to some null (0) value.

And now my scripts use the fact that `doneDate` is less or equal to the max file modification time of the content.  So the actual doneDate to be inserted to database is `max( doneDate, max file modification time)`.  And that works for the content downloaded by transmission or just re-added/verified before entering it into database.

Now I will have to add an additional logic to figure out `doneDate` correctly as it wouldn't hold the meaning its name describes (no downloading done at all, but it's counted as 'done').

And if `doneDate` becomes to actually be `lastVerifiedDate`, would it be updated every time verification happens?

**Comment by ckerr** [comment]
I've put up a PR for this at #1971.

The use case of "is this torrent done because it's a seed, or because I just finished downloading it?" is solved by https://github.com/transmission/transmission/pull/2619
