### ISSUE TITLE
Download progress bar remains blue after finish downloading file in Linux instead of turning green

### ISSUE THREAD

**Issue by michaelkolesidis** [transmission/transmission#1998]
In the macOS version, after a download is complete the progress bar turns green to denote that the process of downloading has culminated successfully. In the Linux version the bar stays blue even after the download is complete. Could that be changed? Thanks

**Comment by ckerr** [comment]
IIRC the look and feel of a progressbar on GTK is dependent on the theme, so changing the color was nontrivial & would make Transmission look inconsistent with other GTK apps, e.g. by drawing our own color we would lose the theme gradient.

However it's been several years since I looked into this and my memory could be wrong and/or support for progressbar colors could have improved. So if anyone wants to do any hacking on this, I'd be happy to review the PR :slightly_smiling_face:
