### ISSUE TITLE
NULL checks practices

### ISSUE THREAD

**Issue by viennadd** [transmission/transmission#202]
our tool reported a case that I am wondering there are some inconsistent checkings? the function [get_fileset](https://github.com/transmission/transmission/blob/master/libtransmission/fdlimit.c#L408) has null check for parameter *session, but none of the callers of `get_fileset ` adding null check of return value. 

and, there are several null checks for function [fileset_lookup](https://github.com/transmission/transmission/blob/master/libtransmission/fdlimit.c#L308), but not in the following `fileset_get_empty_slot`

Could I assume that NULL *session will never passed into `get_fileset`, or some inconsistent (afer get_fileset, will a fileset lookup ensure success ?)

here is a piece might demonstrate a bit
```c
tr_sys_file_t
tr_fdFileCheckout (tr_session             * session,
         ...............
{
  struct tr_fileset * set = get_fileset (session);
  struct tr_cached_file * o = fileset_lookup (set, torrent_id, i);

  if (o && writable && !o->is_writable)
    cached_file_close (o); /* close it so we can reopen in rw mode */
  else if (!o)
    o = fileset_get_empty_slot (set);
```
![image](https://cloud.githubusercontent.com/assets/3396288/23443908/f9b688fa-fe6c-11e6-8e0f-5f1b0baee9bd.png)

**Comment by viennadd** [comment]
anyone?

**Comment by richardxx** [comment]
Hope anybody can have a look for this report. It's vital for helping us in conducting our research. Thanks.

**Comment by mikedld** [comment]
What research exactly are you talking about, if you don't mind me asking?

The checks are inconsistent as you well noticed. Generally, no `NULL` session is expected to be passed into those functions as the value (in existing code) is always coming from `tor->session` and that is never expected to be `NULL` either.

**Comment by richardxx** [comment]
Well, it's an academic research for creating code auditing tools. The picture is a screenshot of our tool.

Yes, we understand the correct situation is `tor->session` is not NULL. We reported this issue because the checks are inconsistent, which we believe it's a bad smell and it's worth to having a look.

Just hope to report the issue and help make transmission better.

**Comment by ckerr** [comment]
Hey, sorry for the four year lag in replying to this issue. Judging from the fact that you've gone and created Sourcebrella in the interim, my guess is that the lack of response wasn't too much of a blocker :laughing: 

Short answer is yes, there is inconsistent nullptr checking in libtransmission. For this specific example, we _should_ be able to assume that session is never NULL, so I'm at a loss as to why `get_fileset()` checks. It looks like [it's been that way since the code was originally written](https://github.com/transmission/transmission/commit/a04f92729e3e32bef1ed828025da0288afee4313#diff-afc52e08fde2460880cae4951bab761e7a14908212a6216ae00f79e58a63d24bR519).

Now that libtransmission is using C++, one approach we should try is to use references instead of pointers to eliminate most of the ways that this category of bugs can occur. :smiley:
