### ISSUE TITLE
Deleting a file should affect progress as returned by rpc

### ISSUE THREAD

**Issue by stuaxo** [transmission/transmission#205]
I'm using transmission via rpc to download videos.  

If I download a torrent, it's progress will show up in rpc as say 100.0

If I then delete the files that were downloaded, the progress is still 100.0

If transmission would recalculate this when files are deleted it would make life a lot easier, as the consumer of the API could just use the progress to decide what to do (possibly tell transmission to re-download).

**Comment by mikedld** [comment]
Transmission only checks if data is in place when this data is needed (e.g. peer connects and requests it), keeping track of each file (with filesystem changes watching or periodic polling) is otherwise inefficient as there could be a lot of files to watch over; note that this kind of watching would have to detect not only when files disappear but also when they [re-]appear or their content changes, otherwise it's a half-baked solution.

In case of deletion, when data is requested and it's not where it's supposed to be torrent enters error state waiting to be re-validated by user. If you need more fine-grained state reporting you'd have to check that files are in place some other way (like running torrents validation on schedule).

**Comment by stuaxo** [comment]
From my external program, if I find the files are not present, what should I do to make transmission return something reflecting the lack of file ?

Ask transmission to reverify the file ?

**Comment by stuaxo** [comment]
In my test, I downloaded a bunch of images via RPC.

Later on I deleted all this content (but still have the .torrent files)

Later on, I ask transmission to verify them.

Then I checked the status + progress.

For each of them, progress is 100.0, status is stopped.

Where can I find that they are in an error state ?
