### ISSUE TITLE
How can i set more than one downloads folder?

### ISSUE THREAD

**Issue by llloxxx** [transmission/transmission#2224]
there is no space on my 1st hard disk, i want to set another folder on another HD, but there is no way to set more than one downloads folder, anyone can tell me hao to do ?

**Comment by ckerr** [comment]
There's no support for having multiple download directories by default -- e.g. "try directory A, but if it's full, try directory B, and so on." and that feature's unlikely to ever be added because it would confuse more people than it helped :slightly_smiling_face: 

Generally the approach is to set a torrent's download directory right after it's added but before it starts downloading, e.g. manually if you're driving it manually, or via a script that's called when a torrent is added. That last option is available in the nighly builds (it was added in #1896) but isn't in in an official release  yet.

**Comment by ruijiexie** [comment]
123
