### ISSUE TITLE
Swedish word for "Paused" are different in plural and singular

### ISSUE THREAD

**Issue by JonatanWick** [transmission/transmission#2250]
In Transifex "Paused" is translatable but does not distinguish between plural and singular. For example. in the torrent list it should be the singular form and in the drop-down menu the plural form.

**Comment by GScottElshaw** [comment]
Similar comments regarding Norwegian and French. This is the general guidance. https://github.com/transmission/transmission/issues/2244#issuecomment-981206837

**Comment by mikedld** [comment]
IIUC this has beed fixed in Transifex and is already included in 4.0.x:
![image](https://github.com/transmission/transmission/assets/298203/4e6bb59f-00d8-4536-b3ff-40387b86095b)

Note that the second phrase there has a different context pointing to the filter drop-down:
![image](https://github.com/transmission/transmission/assets/298203/23c6324a-e29f-4624-9abf-c02448824947)

For other languages, similar fixes might be necessary but it's possible to do them purely in Transifex and no code changes are required, so I'm closing this.

**Comment by mikedld** [comment]
I'm actually not sure if the second form there is plural. But the fact remains, it's possible to fix in Transifex (unless I'm wrong, in which case feel free to reopen).
