### ISSUE TITLE
Add option to skip hash check

### ISSUE THREAD

**Issue by waynon** [transmission/transmission#2261]
### Description
When you are the first seeder for a torrent or you already have the data from somewhere else, Transmission will normally have to hash-check all files even if you just created the torrent file from them and thus know that they are correct. To eliminate this step, this feature can skip hash check.

There are three use cases where this would be extremely useful, and not at all a legitimate risk of sending bad data.

**1. For loading a torrent into transmission after creating it with some utility like transmission-create
2. For cross-seeding known equivalent torrents between trackers
3. For transfering a known torrent from another BitTorrent client to Transmission, or for loading a known torrent after reinstallation of Transmission**

The first case is rather obvious, you just created that torrent, and now you're putting it into transmission. The odds of a bitflip in that next 30 seconds you take to add it to transmission should be nil. There should be no need to hash the data again, it's just wasting CPU/Disk I/O.

The second case is a bit niche, but I believe it is legitimate. On private trackers, where you cannot add new trackers to a torrent, there are sometimes overlaps in the data that can be shared; so adding the same torrent twice to your client, one for each tracker, is a way to share the data with multiple trackers.
Sometimes piece sizes are different, and it would probably be best to ensure you rehash in that case, but other times trackers use the source field of the infodict to create a unique hash so that two identical torrents can be added to clients. If you know the piece hashes are the same, what is the point of rehashing the data?

The third case is also obvious, after a reinstallation of BitTorrent client, seeding a known torrent does not need rehashing. This is very useful after reinstallation of operating system or migrating to another BitTorrent client. 

I think it should come with some kind of warning that the option risks data corruption, and should absolutely never be the default, but personally I have legitimate use-cases for doing this and I think a lot of other people do, too.

Last but not least, **almost all mainstream BitTorrent clients support this feature, such as qBittorrent, µTorrent, BitTorrent, rTorrent, Vuze(Azureus), BiglyBT and Deluge.**

### related issues
https://github.com/transmission/transmission/issues/781

### related pull requests
https://github.com/transmission/transmission/pull/769
https://github.com/transmission/transmission/pull/1757

**Comment by waynon** [comment]
On the one hand, if someone deliberately wants to transmit wrong data, they can use qBittorrent, µTorrent, BitTorrent, rTorrent, Deluge or a modified version of Transmission. 

On the other hand, in order to prevent someone from unintentionally transferring wrong data, a warning dialog can be used.

**Comment by waynon** [comment]
Hashing large files in low performance hard drive can take several hours and significantly reduce hard drive life.

**Comment by cerebrallolzy** [comment]
Just use another client or compile it yourself. This feature is in every other popular client, so I can only conclude that they just think we are too stupid to use said feature properly/safely. Just saying... this client is really wonderful, but this simple over-sight absolutely murders transmission-create's usability.

Thanks for coming to my TED talk.

**Comment by Oleekae** [comment]
@cerebrallolzy That comment you make is to have no idea what this feature is all about at its best, many users don't choose transmission because of this fact, we can't afford to check our own torrents of many GB because we would be checking for days.

**Comment by ckerr** [comment]
See https://github.com/transmission/transmission/discussions/2414#discussioncomment-1986746 for some discussion on this.

To be very explicit about this, `transmission/transmission` I wiill reject PRs that have a "Skip hash check" GUI button. I still think this is an incredibly dangerous feature.

That said, the way Transmission determines what pieces to check is by remembering the files' mtimes and checking "what were mtimes of the files in this piece the last time I checked them" with "what are those mtimes now". I would be OK with adding a new optional parameter to the RPC `torrent-add` method that passes in an mtime array -- basically, the RPC client would be saying "I vouch for the state of this torrent as of these timestamps", e.g. "I just created this torrent and here were the file mtimes when I did it."

This still _could_ be used by irresponsible 3rd party apps as a way to implement a "skip hash check" button (by providing mtimes without actually checking the contents), but I hope that people would not do this. The intent of the mtime array would be to provide a way to vouch for the files' contents when some process outside of transmission-daemon has actually confirmed the files.

**Comment by LaserEyess** [comment]
I've been thinking about this, and using an array of mtime seems like a huge burden with little added buffer against people abusing skipping verification. First, you can change mtime very easily on any OS, on linux I can manipulate entire directories recursively with `touch -mt 197001010000`, I'm sure windows has something like this in the win32 API and what not.

Second, getting an array of mtimes to pass to RPC is not currently possible with the set of tools transmission provides. They could be implemented, sure, but where?
 - `transmission-create`: no JSON-RPC capability, where would you store the mtimes? An extra file output?
 - `transmission-remote`:  JSON-RPC, but no guarantee that the files are on the machine. How do you add mtimes to the RPC call?
 - A third, hypothetical tool that combines the functionalities of the above tools?


My idea is to use the creation date of the torrent file instead. By comparing the creation date inside of the torrent file you can essentially accomplish the same thing with less effort, while still keeping with the spirit of "you must make sure these files haven't been modified since they were checked". 

This has a couple of advantages:
 - Embedded into the torrent file and does not require adding a new RPC array, just a single field
 - Can be dropped if the creation date field doesn't exist, even if a user forces `--skip-verify` or equivalent
 - Requires minimal changes to utilities to support the functionality

This still isn't immune from rampant abuse via changing mtimes, or having 3rd party utils faking data to skip verification, but those abuses are also possible with passing an mtime array. Thoughts?

**Comment by liangqisen1** [comment]
May I ask when the version that can skip verification or the button function can be released? You may not use it, but you can't do without this function. QB already has it

**Comment by ckerr** [comment]
> Seriously, this option has not yet been implemented in transmission?

😕 this was released in 4.0.0
