### ISSUE TITLE
feat request: sort torrents by ETA

### ISSUE THREAD

**Issue by diogoeichert** [transmission/transmission#2279]
When downloading multiple torrents, it can be useful to know which one will complete first. So it would be helpful to be able to sort per ETA, like other popular clients do.

**Comment by echaskaris** [comment]
Does "sort by time left" help?

**Comment by diogoeichert** [comment]
> Does "sort by time left" help?

Yes, that would be helpful.

**Comment by elliotrushton** [comment]
Just an FYI. I think this is only missing in the macOS client. I came here looking for the same thing but then found it in the Qt code! I was confused (because I don't see this option in my macOS client) so installed Transmission in a Linux VM and sure enough, sort by ETA is an option. But in the macOS client it's not.

I'm not familiar enough with Objective-C to quickly put together a PR, but in case I either decide to later or if someone else comes along looking to do so, the relevant parts are here https://github.com/transmission/transmission/blob/db3d40d0edfab958b48f3413d2fce442420a65c2/macosx/Controller.m#L98 and here https://github.com/transmission/transmission/blob/db3d40d0edfab958b48f3413d2fce442420a65c2/macosx/Controller.m#L2535

**Comment by elliotrushton** [comment]
I couldn't resist and took a crack at adding it in https://github.com/transmission/transmission/pull/2302

**Comment by JacksonChen666** [comment]
> Just an FYI. I think this is only missing in the macOS client.

uhhh, i can't find any sort options like "sort by time left" in the web interface of transmission too.
