### ISSUE TITLE
Multiple issues with Web-UI in current Git head

### ISSUE THREAD

**Issue by Deathcow** [transmission/transmission#2301]
I noticed many problems with the web-ui that I think desserve some attention, in case they aren't already known. Most of these I have observed both in chromium and firefox and are regressions from things that work in 3.0:

* when firefox is in dark theme the fonts become unreadable (contrast)
* Changes in the All/Active/Downloading... filter require a manual f5 refresh to become active. Same is true for other display options (except name filter, which is fine).
* The 'Rename...' option doesn't work at all, can't click 'cancel' or 'okay'. Escape works
* Most dialogue pop-ups (like 'Set location...') don't respond to pressing enter/return
* the torrent details side-bar can only be closed by pressing escape, not in the same way it has been opened (double click on torrents or the 'i' symbol in the top bar)
* change of download priority of invididual files/folders doesn't work at all
* overzealous rounding of units: A torrent with size 1.9G shouldn't show up as 1G
* there's no clear indication how to confirm a change of download location in the "Edit Preferences..." dialogue. Pressing enter seems to work (with no feedback), esc aborts. Previous versions always committed changes.

**Comment by killemov** [comment]
+1
But there are alternatives.

**Comment by ckerr** [comment]
@Deathcow I take these bugs seriously, but it's difficult to triage & track multiple bugs in the same bug report. e.g. I would not be able to close this issue until all 8 problems were fixed, and any followup discussion of the 8 problems will all overlap in the issue's comment history.

Please file separate issues for each problem so that they can be addressed separately.
