### ISSUE TITLE
Feature Request: Port from Qt Widgets to Qt Quick

### ISSUE THREAD

**Issue by SaucySauce** [transmission/transmission#2396]

**Comment by ckerr** [comment]
Why?

**Comment by SaucySauce** [comment]
Update: I just checked a recent merge request to make the Qt Widgets based applications frameless in KDE although it's opt-in. That's about it, to make the design a bit more modern without relying on custom theming.

**Comment by ckerr** [comment]
This would require basically rewriting the entire Qt application and it's not clear to me that the end result would still look native on Windows? This seems like the work-to-payoff ratio is enormous.

I'm not going to close the door on this idea altogether because my knowledge of QtQuick / QML is a little dated, so maybe the native issue has been resolved, but I certainly don't want to do this work. If someone wants to make a PR for this, please file an issue to talk to the maintainers about the idea before you work up a multi-thousand-loc PR :smile:
