### ISSUE TITLE
feat: tr_assert should have platform-specific method of crashing

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2422]
Specifically, the goal would be to get more useful macOS crash reports since that seems to be what a majority of nightly build users are testing with.

https://developer.apple.com/documentation/foundation/nsexception/1569524-raise discusses how to raise an exception with a "human-readable message". If we used that mechanism, would that text show up in the crash reports?

- libtransmission should add public API to register an abort() method that takes a message argument.
- the macos client should have a simple method that calls `NSException raise` with this method
- libtransmission/tr-assert should call this registered method if possible, or just `abort()` as a fallback method

**Comment by ckerr** [comment]
Removing "good first issue" label, since it requires some platform-specific knowledge.

Though, for a macOS dev who wanted to get into Transmission, this probably would be a good first issue :slightly_smiling_face:

**Comment by fxcoudert** [comment]
Doesn't the assert display a diagnostic to the Transmission log file, already, that could be displayed? (I don't know how logging is handled in Transmission.)

For `[NSException raise:format:]` I'm not sure the message is going to end up in the crash report.

**Comment by ckerr** [comment]
Right now [the assertion code](https://github.com/transmission/transmission/blob/main/libtransmission/tr-assert.cc#L17) writes to stderr before exiting. As far as I can tell this isn't showing up in the crash reports. For example [this crash report](https://github.com/transmission/transmission/issues/2404#issuecomment-1015182486) shows that the app died inside an assert failure in `tr_assert_report()` but didn't show the actual assertion failure message.

I agree, I don't know either if `[NSException raise:format:]` would work either; I'm not a macOS dev. If someone else has a better way of doing this I'm 100% open to PRs with better fixes  :smile:

**Comment by fxcoudert** [comment]
OK, so I have now confirmed that calling `[NSException raise:format:]` will result in the following information in the crash report:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'toto foo bar'
```

So this is promising. Possible implementation could be:

- in `libtransmission/tr-assert.{h,cc}` we create a function to register the abort-like callback
- in `macosx/main.mm` we implement the callback function, raising `NSException`
- also in `macosx/main.mm`, in `main()`,  we register the callback before calling `NSApplicationMain`

It's very rare to do things before `NSApplicationMain` in macOS code, as event loops/etc have not yet been set up. But it's safe in this case I think, because raising an exception is allowed in that context anyway.

Does that sound like a plan? If so, I'll try to open a PR.

**Comment by mikedld** [comment]
According to [`NSAssert` docs](https://developer.apple.com/documentation/foundation/nsassert), failed condition results in `NSInternalInconsistencyException` being thrown from `NSAssertionHandler` object. I'd say we need to do the same, instead of throwing a generic `NSException`, maybe even using `NSAssertionHandler` and not throwing the exception ourselves.

As a sidenote, one can mix C/C++ and Obj-C/C++ in a single project, so it'll be okay to add an Obj-C++ file (say, "tr-assert.mm") to libtransmission containing Mac-specific implementation, so that dependent projects don't have to set anything up.

**Comment by ckerr** [comment]
Both are fine, but now that I know `tr-assert.mm` is possible, I have a slight preference to doing that over the callback, since it it's a slightly simpler public API.

I'd accept a PR that did it either way, though. If one approach is significantly easier to code than the other, that's fine

**Comment by fxcoudert** [comment]
Is there a macOS build guide? I cloned the repo, built from the Xcode project, but the resulting binary can't run, it's complaining about Sparkle:

```
dyld[51026]: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/fx/Library/Developer/Xcode/DerivedData/Transmission-fhkzihdcsrvdmbdwmcswybolmroa/Build/Products/Debug/Transmission.app/Contents/MacOS/Transmission
  Reason: tried: '/Users/fx/Library/Developer/Xcode/DerivedData/Transmission-fhkzihdcsrvdmbdwmcswybolmroa/Build/Products/Debug/Sparkle.framework/Versions/A/Sparkle' (no such file), '/Users/fx/Library/Developer/Xcode/DerivedData/Transmission-fhkzihdcsrvdmbdwmcswybolmroa/Build/Products/Debug/Transmission.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle' (code signature in <C51F1488-3855-3EF1-9A25-70A626BD85ED> '/Users/fx/Library/Developer/Xcode/DerivedData/Transmission-fhkzihdcsrvdmbdwmcswybolmroa/Build/Products/Debug/Transmission.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/fx/Library/Developer/Xcode/DerivedData/Transmission-fhkzihdcsrvdmbdwmcswybolmroa/Build/Products/Debug/Transmission.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle' (code signature in <C51F1488-3855-3EF1-9A25-70A626BD85ED> '/Users/fx/Library/Developer/Xcode/DerivedData/Transmission-fhkzihdcsrvdmbdwmcswybolmroa/Build/Products/Debug/Transmission.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (no such file)
```

**Comment by ckerr** [comment]
@livings124 @mikedld ^ do either of you know the answer to this

**Comment by fxcoudert** [comment]
I've found a hack (I disabled Sparkle in my local build), but it's really a hack. I still would welcome help on this…

**Comment by fxcoudert** [comment]
Reported in #2484 by another user

**Comment by fxcoudert** [comment]
So, the reason for the Sparkle issue is a mismatch between ID of signature for Sparkle and for local development, which is not allowed under the hardened runtime rules. I found that information in https://github.com/sparkle-project/Sparkle/issues/2056

I can confirm that adding an exception like this works fine:

<img width="658" alt="Capture d’écran 2022-01-24 à 18 20 53" src="https://user-images.githubusercontent.com/1980544/150832712-f28879a0-83fe-4275-88a9-c3c1d56f476c.png">

Now I'm not sure what's the best course to create a PR: adding that exception only for "debug" builds, or adding that exception globally?

**Comment by ckerr** [comment]
I'm going to close this issue just as a matter of housekeeping -- the issue in the title ("tr_assert should have platform-specific method of crashing") is already resolved.

@fxcoudert if the followup issue is still a problem, would you mind filing a separate issue for it? :bowing_man:

**Comment by fxcoudert** [comment]
The issue was reported separately at https://github.com/transmission/transmission/issues/2484, but then closed even though it's not fixed. If you close it here, please reopen that one?

I proposed a fix (https://github.com/transmission/transmission/pull/2497) which was declined, and an alternative fix (https://github.com/transmission/transmission/pull/2497#issuecomment-1025552691) on which I received no comment.
