### ISSUE TITLE
It should be easier for new contributors to make the Code Style CI bot happy

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2455]
With all the recent activity about attracting new devs, one issue is that it's difficult to navigate through our Code Style CI gatekeeper.

`code_style.sh` uses clang-format, which is great. The problem is that different versions of clang-format produce slightly different output from each other, so the current approach right now is just for devs to all have a copy of that version stashed away somewhere specifically for `code_style.sh`. That works fine for the two or three maintainers putting code in, but it's is not great if for attracting new contributors. For example, this morning I manually did this process for two PRs that have been submitted. (#1638 and #2453)

One possibility would be for the bot to generate a patch artifact if the test fails, and link to it somewhere where it will be seen, so that contributors can patch their branch. That's still a lot of process so I'm not in love with this idea, but I think it is better than saying "make sure to use clang-tidy version $foo" since installing multiple versions of the clang suite is a burden.

Better suggestions are encouraged.

**Comment by mikedld** [comment]
As I've mentioned [elsewhere](https://github.com/transmission/transmission/issues/1977#issuecomment-945146832), clang-format version is fixed (to the major) in the [Dockerfile](https://github.com/transmission/transmission/blob/main/docker/code_style/Dockerfile) that the bot uses to run it; one could build the same image locally and run the container. The probability of the result being different (due to minor version changes) is low as base image there is only updated once a day.

**Comment by ckerr** [comment]
Asking users to build a docker setup just to do code styling still seems pretty burdensome.
