### ISSUE TITLE
macOS scroll bar is too wide

### ISSUE THREAD

**Issue by ylluminate** [transmission/transmission#261]
I have been having this problem for quite some time (last few years) where the scroll bar is too wide when it appears and so it subsequently blocks the reveal magnifying glass on entries nearly completely. Could we please move the pause/magnify buttons over away from the scrollbar when it appears or something so that these are not right justified and under the scrollbar?

**Comment by mikedld** [comment]
Related to #1 and [TRAC-5706](https://trac.transmissionbt.com/ticket/5706).

**Comment by ylluminate** [comment]
So this is concerning.  So it seems to me that since apparently Apple is not going to fix this that we are going to have to address this ourselves in some fashion as noted above. 🤷‍♂️

**Comment by Coeur** [comment]
I'm not sure that we need to address this anymore in recent versions of macOS.
In macOS 12 Monterey, you go to System Preferences > General, and you get three settings to choose from:

- Automatic (which I recommend) will not hide the Magnify button
- When scrolling will hide the Magnify button
- Always will not hide the Magnify button

![Capture d’écran 2022-05-10 à 02 57 38](https://user-images.githubusercontent.com/839992/167479192-4363bd03-e7fd-4ea0-95a8-2bf2833fb3da.png)

If you choose the second option, you're hurting yourself system-wide.
If we move the buttons away, then it will negatively impact the UI for the majority of users because they are in the default Automatic configuration.
If we force the automatic mode by doing `self.enclosingScrollView.scrollerStyle = NSScrollerStyleLegacy;` in TorrentTableView's awakeFromNib, then we aren't respecting the user preferences anymore.

**Comment by Coeur** [comment]
I'm actually frequently annoyed by it, to say the truth.
![Capture d’écran 2022-12-26 à 01 52 53](https://user-images.githubusercontent.com/839992/209477776-3ad82a60-a450-4c4d-9b12-a843dca9e273.png)

**Comment by gingerbeardman** [comment]
Has this been addressed in v4?

**Comment by Coeur** [comment]
@gingerbeardman Not yet, but @sweetppro just opened a PR for it.
