### ISSUE TITLE
Random torrents added 3.0 despite RPC being passworded

### ISSUE THREAD

**Issue by Revenger** [transmission/transmission#2653]
Its been reported that random torrents are being added to a users download que on 3.0 despite the interfaces being usernamed and password protected.

Mainly these torrents.
[LockBlock] Xian Wang de Richang Shenghuo 1-15 VOSFTR [WEBRip][720p][X264]
[LockBlock] Xian Wang de Richang Shenghuo - The Daily Life of the Immortal King S2 1-12 VOSTFR [WEBRip][720p][X264]

Had it happen removed the torrents and this morning they were back again, I removed the torrents again just now so don't have them to share if the torrent file itself had anything in it.
None of my added torrents were changed.

Also other torrents are being added as I had some random 200 byte manga named empty rar file added as well as a text file that just had 88 in it.

Some threads on the issue.
https://forum.transmissionbt.com/viewtopic.php?f=2&t=20962&sid=49621376ddafb13a54bd9a0daf02c3ae
https://community.synology.com/enu/forum/1/post/151239

I changed my username and password just incase.

It seems theres a vunrability in 3.0 that allows torrents to be added regardless of password settings.

**Comment by ckerr** [comment]
OK, this is very concerning. I don't yet see the vector for this attack but the fact that it was an added torrent, rather than RPC commands, may be useful.

Can you ask the people in that transmissionbt forum thread to come here as well? I have some questions, e.g.

- What is the _exact_ version of Transmission that you're using, e.g. what does it say when you look at Help > About, or run `transmission-daemon --version`, etc. -- if there is a checksum in the version, please include it

- Would it be possible to pastebin your settings.json file _as it existed when the torrents were added_ so that I can see it; or if you don't feel comfortable posting it publicly, mail it to me at my first name at first and lastname dot com with the subject "transmission bug #2653" for visibility

**Comment by Revenger** [comment]
It's being reported on Reddit now for qbittorrent.

https://www.reddit.com/r/truenas/comments/swcuow/unknown_torrents_added_to_qbittorrent_plugin/

`root@server-download:~# transmission-daemon --version
transmission-daemon 3.00 (bb6b5a062e)`

Transmission was gotten from the official Debian Bullseye repo as I updated my Proxmox LXC Debian container the other day.

Paste is here changed the hash and username for privacy.
https://pastebin.com/f1pZtdWW

I noticed despite changing the username and password my android client can still connect with the old info I had in there.

**Comment by Revenger** [comment]
I just checked the webui and seemed I could get in without a username and password.
I will send you a email.

**Comment by Revenger** [comment]
Somehow RPC authentication was set to 'false', I possibly overlooked this when setting up my LXC or something changed it I don't know.
But double check your settings and I am going to keep a eye on things.

**Comment by ckerr** [comment]
> It's being reported on Reddit now for qbittorrent.

*whew* OK this looks much less like a zero-day in Transmission then. I looked at that code for an hour yesterday trying to figure out how I would break it. :laughing: 

> Somehow RPC authentication was set to 'false'

Maybe there is something that we could do in the UI to signal connection security level, e.g. have an icon to show security level and base it upon whether authentication is on, whether IP whitelists are enabled, etc.

**Comment by ckerr** [comment]
I'm going to close this one as a false alarm for now but **please reopen** if it looks like there is a Transmission bug to be fixed.

I've filed a new ticket #2664 with the icon idea to make it easier to see when security settings are accidentally turned off.
