### ISSUE TITLE
webseed torrents can download too much excess data

### ISSUE THREAD

**Issue by krichter722** [transmission/transmission#267]
Errornous torrents like http://mirror.aarnet.edu.au/pub/sage/spkg/upstream/singular/meta/singular-3.1.5.tar.bz2.torrent can cause a large amount of download data to be transferred (eventually infinite) which doesn't make sense because they never seem to be finished. There should be configurable limit of this checksum error data volume to be downloaded.

experienced with 2.92-2ubuntu1 on Ubuntu 17.04

**Comment by cfpp2p** [comment]
This bug and https://github.com/transmission/transmission/issues/268 are within a range of known webseed issues.
Perhaps this one: https://github.com/cfpp2p/transmission/commit/6f88e155b04059bdba22b54cb67603b88d07d563

Included within https://trac.transmissionbt.com/ticket/5923#comment:21

**Comment by Coeur** [comment]
Since that bug isn't a regression from Transmission 3, can we move the milestone to 5.0 instead?

**Comment by ckerr** [comment]
I'd rather leave it targeting 4.0.0 stable, but if this were the last remaining 4.0.0 issue it's not a blocker.

**Comment by Coeur** [comment]
I'm honestly pushing for a release of Transmission 4 as soon as possible. Then we can just prioritize remaining expected changes for a subsequent release.

I even previously had set #3040 to be 5.0 despite having a working pull request because I wanted to minimize non-blocking changes for 4.0.

In my opinion, we should now only merge fixes for regressions from 3.0 to 4.0. Any other fixes, improvements or features should go to another release.

**Comment by ckerr** [comment]
Why?

**Comment by Coeur** [comment]
Because last stable release was May 23, 2020.
And security improvements were done that should have been into a stable release for a long time:
https://github.com/transmission/transmission/pull/1638#issuecomment-1113553318

**Comment by GaryElshaw** [comment]
@Coeur I get it, but i'm not sure Transmission (the project) has a tracking/roadmap in a conventional way. It's no shade on anyone, but it's always appeared iterative wherever the love might be at any particular moment.
