### ISSUE TITLE
pieces time-checked incorrect, and saved in resume files

### ISSUE THREAD

**Issue by cfpp2p** [transmission/transmission#292]
This at torrent.c `stopTorrent()` and session.c `onSaveTimer()`

When adding a new torrent (no existing files) verify.c `verifyTorrent()` sets for non-existent files `pieces[pieceIndex].timeChecked = tr_time()` via `tr_torrentSetPieceChecked(tor, pieceIndex);`

This leads to resume.c `saveProgress()`, `mtime` is set to 0 for a non-existent file. There is no logical path where `has_zero` can be set true.

```c
        ...
        bool has_zero = false;
        time_t const mtime = tr_torrentGetFileMTime(tor, fi);
        ...
            if (p->timeChecked == 0)
            {
                has_zero = true;
            }
        ...
        if (!has_zero && mtime <= oldest_nonzero) /* all checked */
        {
            tr_variantListAddInt(l, oldest_nonzero);
        }
```

/* **all checked** */ is the result.

Additionally, modified times for future downloading files are not always correctly synchronized to the pieces `timeChecked` stamps. This leads to further logical errors in `saveProgress()` and continuing errors in the resume file's time-checked entries.

```c
        if (!has_zero && mtime <= oldest_nonzero) /* all checked */
        {
            tr_variantListAddInt(l, oldest_nonzero);
        }
        else if (newest < mtime) /* none checked */
        {
            tr_variantListAddInt(l, newest);
        }
        else /* some are checked, some aren't... so list piece by piece */
        {
```

**Comment by ckerr** [comment]
I think this is resolved in `main` under the new progress approach, there is no longer any `/* all checked */` shortcut, since we no longer are writing per-piece timestamps.

Because of that, I'm closing this issue as resolved. If this is in error, please open a new issue based on the current codebase so that we can figure it out all over again.

I realize this is about five years too late, but since I wasn't active on the project in 2017 I wasn't here to appreciate these details at the time. This is a very good bug report. Thanks for going into the details of the preconditions to trigger the bug.
