### ISSUE TITLE
transmission-create should warn about non-portable filenames

### ISSUE THREAD

**Issue by aoand** [transmission/transmission#305]
Some 10 years ago transmission-create was modified to silently ignore files with names starting with dot (.).
https://trac.transmissionbt.com/changeset/2162

The reasoning was: "because IMO there's no good reason for dotfiles to be in torrents".
This argument is not right.

Files starting with a dot are nothing special on Windows, so there are plenty of torrents out there with files named like:
.NET in depth.pdf
.NET and XML for programmers.chm
etc...

I got caught by transmission-create when re-creating a public torrent from a private one: transmission silently dropped some files from the new torrent. Very irritating. :(

I agree, that by default .dotfiles should not be added, because this will bring more trouble than profit (think of .DS_store on Mac, for example), but once in a while you really need to add a file, starting with a dot in your torrent (see above).

So, here is a feature request: add a command-line option to transmission-create to include dotfiles in the torrent.

If this request is considered sensible, I can try to draft a pull request.

**Comment by mikedld** [comment]
By all means, I like the idea of giving users control here as long as current behavior is preserved as a default.

I think it would also be beneficial to improve default behavior on Windows (even without using the proposed new flag): instead of dotfiles ignore files which have "hidden" attribute (which could be seen an dot files counterpart), which would ignore e.g. "Thumbs.db" (although [not very relevant with Vista+](https://en.wikipedia.org/wiki/Windows_thumbnail_cache#Centralized_thumbnail_cache)).

**Comment by andreymal** [comment]
Even if "there's no good reason for dotfiles to be in torrents", Transmission should notice about existing dotfiles to allow user to rename or delete them.
