### ISSUE TITLE
Flag "Stay within the global bandwith limits"

### ISSUE THREAD

**Issue by vpww** [transmission/transmission#3078]
In torrent setting the flag "Stay within the global bandwith limits" is always enabled by default for new torrents and it is impossible to turn it off
mac os 11.6.5, transmission: Last build (#7911)
<img width="260" alt="image" src="https://user-images.githubusercontent.com/34859751/168147815-8d2aa6e3-1c79-40aa-ba05-883628699249.png">

**Comment by sweetppro** [comment]
this also occurs on macOS 12.3.1

**Comment by GaryElshaw** [comment]
I always assumed it was because of the values set in the preferences. That the values there were the baseline, and then individual torrents can be set up or down in the inspector.

I am also frequently wrong and told so.

![SCR-20220513-h92](https://user-images.githubusercontent.com/69029666/168188345-d0d5f838-2501-4548-956d-56328a5255bf.png)
