### ISSUE TITLE
How to find the correct version?

### ISSUE THREAD

**Issue by zhengxinhn** [transmission/transmission#310]
I use  svn co -r  to get  14714 and 14160 version of the source code .
but after I  cross compiled it on LEDE/OpenWrt ,they become 14712 and 14156.
I checked the generated file version.h ,that's true.

**Comment by mikedld** [comment]
Make sure that you have `svnversion` executable in your path. Otherwise revision is (was) being calculated based on comments in sources files, and if none of the source files containing the comments were changes between 14712 and 14714 (or 14156 and 14160), the result may well be lower. For details, look into update-version-h.sh script in repository root of your svn working copy.

**Comment by zhengxinhn** [comment]
My fault,the download.mk  in LEDE/OpenWrt use export not checkout, .svn folder excluded.
