### ISSUE TITLE
entered number of peers not saved and wrong number shown

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3116]
Usually when I finish downloading, I set priority low and peers fewer but still seed.  If I select multiple that have different priority (like some I already set low) then the priority box is correctly blank, but the peers box isn't, rather than showing the lower number of older (fewer peers) torrents and not the number of newer (default more peers) torrents.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If you select multiple torrents with different numbers of peers, it should show a blank for that, like priority does, and then set them all to the new number you entered.  However, in this case, it doesn't set any of them at all: leaves the old ones as they are (which is typically the number one might enter in this case) and doesn't even set the new ones to the new (lower) number after pressing <ENTER> or close, like it does when you enter a new priority (for ones beforehand had mixed priorities.)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You should probably check whether other things (limits) selected multiple torrents with different values are correctly blanked then actually set.

**Comment by ckerr** [comment]
Which version of Transmission are you using, and on what OS?

**Comment by dchmelik** [comment]
transmission-qt 3 (bb6b5a062e) on Slackware64 15.1-current GNU/Linux... may have noticed same on FreeBSD UNIX.

**Comment by ckerr** [comment]
Transmission has undergone a massive rewrite since 3.00 as part of the migration from C to C++ on the backend. If you're comfortable with building from tarballs or from a git repository, would it be possible for you to test from the github repo or from a nightly snapshot at https://transmissionbt.com?

**Comment by ckerr** [comment]
Transmission has undergone a massive rewrite since 3.00 as part of the migration from C to C++ on the backend. If you're comfortable with building from tarballs or from a git repository, would it be possible for you to test from the github repo or from a nightly snapshot at https://transmissionbt.com/?

**Comment by ckerr** [comment]
Closing due to lack of response and due to lack of actionable info.

If anyone is still encountering this issue, please file a new ticket with updated info. Thank you! :bowing_man:
