### ISSUE TITLE
100% CPU on macOS

### ISSUE THREAD

**Issue by forthrin** [transmission/transmission#32]
I'm experiencing frequent 100% CPU usage on macOS 10.12 (also earlier) with only a single file transfer. Let me know how I can provide more information to help developers locate and resolve the problem.

**Comment by margjakob** [comment]
I'm running homebrew's daemon and have the same problem.

**Comment by varunmehrishi** [comment]
Facing continuous 100% cpu use on macOS Sierra, removed and reinstalled from homebrew.
<img width="1440" alt="screen shot 2016-09-27 at 6 19 42 pm" src="https://cloud.githubusercontent.com/assets/16867037/18874565/e082cce2-84df-11e6-9e3c-6013d54a210b.png">

**Comment by mikedld** [comment]
If someone could download a nightly build from https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/ and sample the process? I'm going to check it out myself sometime soon, but just in case it won't reproduce for me, and for bookkeeping purposes.

**Comment by mikedld** [comment]
Okay, so as far as I could see the CPU is being used by `poll()` system call inside libevent. Tried updating libevent to 2.1.6-beta and the problem was gone. Noted that 2.1.6-beta calls `kq_dispatch` while 2.0.22-stable (which we currently use) calls `poll_dispatch` despite the fact that `_EVENT_HAVE_KQUEUE` and `_EVENT_HAVE_WORKING_KQUEUE` are being defined and kqueue has priority over poll. Seems like they fixed something that prevented kqueue initialization...

**Comment by forthrin** [comment]
Well, I was using the CLI version, which does not seem to be included in the nightly build, but at least CPU is running at a snug 5% when using the GUI version. Let me know when the fix is available for Homebrew and I'll test the CLI.

**Comment by mikedld** [comment]
@forthrin, libevent 2.1.6-beta is available in Homebrew for some time... All you need to do is (re)install it with `--devel` option. Might also need to reinstall transmission with `--build-from-source` afterwards though.

**Comment by forthrin** [comment]
I haven't experienced this for a long time. Fixed?

**Comment by lovetheguitar** [comment]
Experiencing this on 10.13.3 with Transmission 2.92 (14714). :/

**Comment by forthrin** [comment]
Hasn't happened to me for a long time. Assumed fixed.
