### ISSUE TITLE
Netmask for bind-address-ipv4 option

### ISSUE THREAD

**Issue by Soullivaneuh** [transmission/transmission#322]
It would be great to specify a netmask or whitelist for `bind-address-ipv4` option.

Something like this: `10.8.8.*`

What do you think?

**Comment by mikedld** [comment]
AFAIK, there is no way to bind a socket to a subnet or even more than one IP address at a time. This would mean opening as many sockets (when accepting connections from remote hosts) and thus wasting system resources, and some kind of balancing between the addresses (when connecting to remote hosts); in both cases complicating things for no good reason (?). Correct me if I'm wrong.

Also I'm not exactly sure how many people will benefit from this, and it feels like not a lot.

It could well be that you want something entirely different and aren't expressing it right. I remember requests (and even patches) to support binding to a particular interface instead of IP address (see [TRAC-2313](https://trac.transmissionbt.com/ticket/2313)). If that's the case, try those patches out to see if they work for you and open another ticket.

**Comment by Soullivaneuh** [comment]
> AFAIK, there is no way to bind a socket to a subnet or even more than one IP address at a time.

@mikedld In this case, maybe permit the bind change on the fly with the cli-remote?

> Also I'm not exactly sure how many people will benefit from this, and it feels like not a lot.

For my case, I'm using a third-party VPN and the provided local IP is not the same at each connection. So I have to update it manually.

I don't think I'm the only one using this. :wink:
