### ISSUE TITLE
Potential buffer overflow

### ISSUE THREAD

**Issue by legendtang** [transmission/transmission#361]
Hi, all

Our code scanners reported that the third library JSONSL might generate potential buffer overflow. Though seems you're not actually using the function. Could someone take a look at this?

Steps:
`mycopy` allocated at https://github.com/transmission/transmission/blob/4c00df9463ea4fd70b73c620e439f5c3ee5efa60/libtransmission/jsonsl.c#L742 but `path` is from user input. Assume `path` is a small string.
`mycopy` were passed to `cur`
https://github.com/transmission/transmission/blob/4c00df9463ea4fd70b73c620e439f5c3ee5efa60/libtransmission/jsonsl.c#L752
`c = in;c[3];` 3 is directly used as dereference offset. `end = in + strlen(in) + 1` can not guarantee the case.
https://github.com/transmission/transmission/blob/4c00df9463ea4fd70b73c620e439f5c3ee5efa60/libtransmission/jsonsl.c#L679

Wensheng,
Sourcebrella Inc.

**Comment by mikedld** [comment]
Yeah, we're not currently using JSON pointers (and so aren't calling `jsonsl_jpr_new`). You might want to check [upstream](/mnunberg/jsonsl) to see if the issue is present there though; the code still looks similar enough. I'm planning on updating jsonsl from upstream soon-ish and it would be nice to have another set of eyes (even/especially automated ones) look at it ;)

**Comment by cfpp2p** [comment]
https://github.com/mnunberg/jsonsl/issues/38
