### ISSUE TITLE
[gtk] "Open folder" sometimes tries to open a wrong folder

### ISSUE THREAD

**Issue by simonbcn** [transmission/transmission#373]
```
Arch Linux
transmission-gtk 2.92
GNOME Shell 3.24.3
```

I have a torrent with this info:
![captura](https://user-images.githubusercontent.com/428231/29357260-2cadebfc-8277-11e7-8def-f058e65adde1.png)

But when I select "_Open folder_" in this torrent, it does nothing and it shows this error in console:
```
gio: file:///home/juan/dunehd/Transmission/.temp/Derek%20Raser%20Andrei%20Karenin%20(Bel%20Ami): Error when getting information for file “/home/juan/dunehd/Transmission/.temp/Derek Raser Andrei Karenin (Bel Ami)”: No such file or directory
```

`/home/juan/dunehd/Transmission/.temp` is the folder for the incomplete torrents.
With `transmission-qt` works.

**Comment by ckerr** [comment]
I just tested this in a nightly build of transmission-gtk after downloading a torrent to 100% so that it got moved from the Incomplete dir to the Download dir, then clicking 'open folder'. When doing this, the Download dir was (correctly) opened so I'm not able to reproduce this yet.

If this is still happening for anyone in newer versions of Transmission, please file a new issue with updated information. Thank you!
