### ISSUE TITLE
3.00 GTK client memory leak 

### ISSUE THREAD

**Issue by xtremeqg** [transmission/transmission#3804]
So, been using the 3.00 (bb6b5a062e) client for a couple months now and its been a disaster. After just two days its again sitting at 4 gigs of ram. Within a week or two usually it ends up somewhere north of 12 gigs ram usage. I haven't done anything different from what I did before upgrading. Download a .torrent file occasionally, Transmission picks it up and a couple minutes later the download is done and let it seed. Every week or so I trim the list of downloads a bit and nothing more.

I've seen this issue reported repeatedly with all fingers being pointed at whatever upstream distro is providing this version yet on https://transmissionbt.com/download the latest version available is 3.00 (bb6b5a062e). Even right here, on Github the latest release is 3.00 (bb6b5a062e): https://github.com/transmission/transmission/releases/tag/3.00.

Instead of closing these reports as duplicate/wontfix/getoffmylawn and criticizing the reporting user for using the latest available version, maybe releasing an actual update is the better option?

**Comment by ile6695** [comment]
I'm sure you meant good, but your comment sounds more like a rant about wanting a new release than reporting a memory leak issue. For new release, you can see from github that milestone for `4.0.0-beta.1` is 98% complete and `4.0.0` has two issues with "pr welcome" label.

Closing the issues as duplicate is a sensible thing to do, since having tens of separate issues about same subject only makes tracking issues harder. There are likely none wontfix issues, but some are closed because they are already fixed and coming with 4.0.0

About the memory leak issue. Could you go to the download page you linked, choose `Nightly builds` and report if your issue gets solved with that?

**Comment by xtremeqg** [comment]
> About the memory leak issue. Could you go to the download page you linked, choose `Nightly builds` and report if your issue gets solved with that?

I would, if there were nightly Linux builds but sure, I can build it myself. Didn't get the GTK version as output for some reason but fair enough. Will report back in a couple days how the QT version performs.

**Comment by fredo-47** [comment]
I also had an issue that the GTK was not built during build process. Error message was something like „atkmm“ not found, or „atkmmconfig.h“ not found, iirc.

After some search on the internet, I found this fix which solved the problem.
After adding that one line in file „FindGTK2.cmake“ building of GTK client works.

**Comment by ile6695** [comment]
I've used `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_GTK=1 ..` to get an error if I'm missing some libraries for building gtk client. You were likely missing `libgtkmm-3.0-dev`

**Comment by xtremeqg** [comment]
Been using the Qt version I built from 3c8d8488ea some days ago, at most I've seen it use 200 megs. I would consider this a rather big improvement over the 3.00 GTK client.
