### ISSUE TITLE
Transmission does not find seeds and does not download torrents when other applications do

### ISSUE THREAD

**Issue by Gitering** [transmission/transmission#3821]
Transmission does not find seeds and does not download torrents when other applications do.

After checking Transmission in MacUpdate, a user said also that pointing to qBittorrent to overcome it. Amazingly, I tested it and indeed, now Transmission does not find any peer and does not download, whereas qBittorrent shows five peers and is downloading beyond (56% and increasing) what Transmission previously downloaded (40%).

I love Transmission simple beautiful interface and I wonder if that serious problem could be fixed, as other applications like qBittorrent has already fixed. Otherwise I will be forced to switch from Transmission to qBittorrent (which has a horrible complex interface). A shame for all.

System: Transmission 3.00 and qBittorrent 4.4.5 on macOS 12.6 (21G115) Monterey (latest versions of all) on Intel x86 Mac.

Thanks!

**Comment by GaryElshaw** [comment]
A lot has changed since 3.0, and i'd really recommend a nightly now that a beta is just around the corner. https://build.transmissionbt.com/job/trunk-mac/

**Comment by Gitering** [comment]
Thanks. I have updated to the latest Transmission 3.00+ (fe9aba702e) and it showed not only the only torrent that was previously showing, but also about 12 very old ones that were deleted long ago. I have deleted them again. I understand that it is a bug.

And the previous stuck torrent continues stuck with no peers, whereas qBittorrent shows five peers and is downloading now.

**Comment by Coding4Coffee** [comment]
@Gitering Try a clean install. Move Transmission to the trash, empty, then browse to:

`~/Library/Application Support/`

Delete the "Transmission" folder, reinstall the nightly and test again.

**Comment by GaryElshaw** [comment]
I do see the same thing with some torrents (it's why i keep utorrent around), and have never quite figured out why there are some torrents with seemingly better connectivity.

I wouldn't suggest deleting the Transmission directory, but move it to your desktop. Starting clean with a new version always feels good.

**Comment by Gitering** [comment]
Thanks. Done, but the same issue arises. Somehow, Transmission does not see peers for torrents that other applications like qBittorrent see and use to download. As said, others see also such issue and it would be great if it  could be fixed. This is a critical feature. Thanks again for all.

**Comment by Coding4Coffee** [comment]
Are you familiar with [WireShark](https://www.wireshark.org)? Would be interesting to see a pcap capture of qBittorrent vs Transmission with that torrent, pretty hard to troubleshoot otherwise. Only other suggestions before that are to put the same port number qbittorrent has in its settings into Transmission, and try with uTP off.

**Comment by zaquest** [comment]
Not sure if it's related, but I have a similar issue where Transmission 3.00 (bb6b5a062e) (daemon) won't find/show any peers and won't start a newly added torrent. I have noticed that it seems to be related to the "Max peers overall" (peer-limit-global) setting. Whenever Transmission isn't able to find any peers, I go to settings, increase that number and it finds peers and starts the download immediately. I am guessing it is because I seed a lot of torrents and they just take all the peer slots. Would be nice to have separate limits for upload and download.

**Comment by pmarsden** [comment]
You do have some control over upload v  download.
There are two settings - "peer-limit-per-torrent" & "upload-slots-per-torrent"

So you can (for example) you set them like this 

"peer-limit-per-torrent": 5,
"upload-slots-per-torrent": 2,

This means a torrent can have 5 peers max, but no more thn 2 of them can upload.
In otherwords, it can download from (up to) 5 peers, but will only seed back (upload) to a max of 2.

Its not exactly what you wish for, but it does give you some control.
Use it to limit uploading peers, thus having (more) free slots for new downloads.

**Comment by ckerr** [comment]
Duplicate of #3705.

**Comment by e8vww** [comment]
I can confirm that this issue is present in the latest version 4.0.6 for linux.

Firstly the app was causing my system to hang (found out it is only single-threaded).

Second, I had 50-60 stalled torrents that supposedly had seeds but Transmission couldn't find any.

Switched to qBittorrent and they all finished in 2-3 days.

**Comment by omnipitous** [comment]
Also confirming.. a year later.. that 4.0.6 is still having issues.. @ckerr Has this project stalled?? I started using Transmission when one of my other clients got blocked and it worked for about a dozen torrents.. now it can't seem to connect to *anything, doesn't remember my settings between sessions, never returns.. anything.. from test connections.. ??

**Comment by IonelLupu** [comment]
I am not sure what happened. Transmission worked before and now it doesn't see any peers anymore and it doesn't download anything. I had the port closed initially but opening it didn't fix the issue.

A popup with some message would be nice to have even if the error is not user friendly. Would be nice to see where it gets stuck or what API doesn't return the proper information for it to get started downloading

**Comment by VariantT505** [comment]
Same problem here. It was already the case with 4.0.6 (on Mac) but it's even worse with 4.1.0.
On 4.0.6, Transmission needed around 10 minutes before finding any peer and start the download (where any other software like uTorrent would start immediately), but now on 4.1.0, it won't start any download anymore at all.
