### ISSUE TITLE
That's not how it works...

### ISSUE THREAD

**Issue by kelbon** [transmission/transmission#3942]
https://github.com/transmission/transmission/blob/f1f55cc3df1105d03549251c6023726829179838/libtransmission/file.h#L215

**Comment by kelbon** [comment]
There are no _t postfix, no ::type, so no sfinae, enable if is useless, is_member... shit is useless, ::value is useless, its just equal to
typename = decltype(&T::c_str) and its bad, because c_str can be overloaded, it must be
typename = decltype(std::declval<T>().c_str())
And furthermore it must NOT BE
Just remove this string and nothing will change, there are no overload set for disabling / enabling functions

**Comment by nevack** [comment]
So why not just create a PR with fix at this point? Be useful 🥇

**Comment by ckerr** [comment]
Given your GitHub repositories I'm guessing you know what you're talking about, but what you're saying here is so difficult to parse it's nearly useless:

> "and its bad ... it must be ... and furthermore it MUST NOT BE"

It must and must not be `decltype(std::declval().c_str())`?

Gonna agree with @nevack here, please make a PR or a code snippet with what you're trying to express, because an issue that just says "That's not how it works..." and "shit is useless" is so hostile and vague that, if you're actually trying to help, then you're working against your own cause by being opaque and annyoing.

> This function must be not template with just two parameters T and U, it must accept two string_view s

On posix this is implemented using `stat()` which uses a zero-terminated string, so converting strings into string_views here would require us to make zero-terminated temporaries. Which wouldn't be _terrible_ but there is a reason here, you shouldn't just come in and say "it must accept two string_view s".

**Comment by ckerr** [comment]
I appreciate the feedback but it's difficult from your text to understand what you think the correct code should look like. :+1:  on @nevack's comment above -- please open a PR

**Comment by ckerr** [comment]
@kelbon ping

**Comment by xavery** [comment]
@kelbon Terry? Is that you?

**Comment by Coeur** [comment]
My understanding is that kelbon would prefer us to declare the specializations directly:
```
inline bool tr_sys_path_is_same(tr_pathbuf const& path1, tr_pathbuf const& path2, struct tr_error** error = nullptr)
{
    return tr_sys_path_is_same(path1.c_str(), path2.c_str(), error);
}
```

**Comment by kelbon** [comment]
> My understanding is that kelbon would prefer to declare the specializations directly:

No, https://godbolt.org/z/cWTa78r7r
