### ISSUE TITLE
[Feature request] Double-click tray icon to show Transmission

### ISSUE THREAD

**Issue by tedstoychev** [transmission/transmission#403]
The Desktop option 'Show Transmission icon in the notification area' must be turned on first and Transmission must be minimized.

**Current behaviour:**
When we click the tray icon with either the left or right mouse button we get a list of options. If we want to maximize Transmission, we have to select the first option ('Show Transmission').

**Desired behaviour:**
When we click the tray icon with the left mouse button, Transmission gets maximized.
When we click it with the right mouse button, we get the list of options.

**Tested on:**
Linux Mint 18 Cinnamon

**Comment by mnalis** [comment]
@tedstoychev can you comment on reason for close? has it been re-implemented? Or have you found an fix or workaround?

It used to work this was in Debian Stretch (transmission-gtk 2.92) but in Debian Buster with transmission-gtk 2.94 it broke the way you note:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901081

**Comment by tedstoychev** [comment]
@mnalis I closed the issue due to inactivity. I didn't find a fix or a workaround.

**Comment by sio** [comment]
In that case I think the issue should stay open to allow further discussion
and fixing if the project ever gets moving again.

>

**Comment by tedstoychev** [comment]
@sio I'm open to the idea of re-opening the issue if the maintainers of the project show interest in it. I closed the issue because there wasn't any activity on it for 2 years.

If the maintainers of the project would like to see the feature implemented but won't have time to implement it themselves, they can still label the issue to indicate this.

**Comment by sio** [comment]
Issues are useful not only to maintainers but to other users too. Closing
the issue without real solution will confuse people who may come here via
search engine later.

**Comment by mnalis** [comment]
@tedstoychev please reactivate the bug then, as it still exists.

Current lack on activity on project should not mean that all issues should be closed. This is IMO clear regression (ie. it used to work correctly, and then it stopped), and when someone decides to pickup or fork the project, it might get fixed (as long as it's status indicates the bug is still there). 

If it were deliberate project decision to change behaviour, then maintainers can tag it "wontfix" with explanation why it is desired behaviour and close it.

**Comment by elkoni** [comment]
Building from source ( transmission-2.94.tar.xz ) on Debian Buster solves this.

**Comment by mnalis** [comment]
@tedstoychev yes, please reopen the ticket as the bug is still there.

It bug seems to happen only when "libayatana-appindicator for Ubuntu-like tray" is enabled. On Debian Buster (and I guess, Ubuntu) systems, libayatana-appindicator3-dev installs library in nonstandard path, which default `./configure` does not recognize, and so builds without ayatana-appindicator support - and tray icon works correctly as before. Debian package build however will first patch correct path, so transmission-gtk will compile with ayatana-appindicator support, and left-click-in-trayicon bug will manifest itself (as detailed on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901081 )

I've worked around the issue on Debian Buster by rebuilding package without ayatana-appindicator support:

```
sudo apt-get install build-essential devscripts
mkdir /tmp/transmission
cd /tmp/transmission
apt-get source transmission-gtk
cd transmission*/
apt-get build-dep transmission-gtk
dpkg -r libayatana-appindicator3-dev
```

Then I've modified the `debian/control` file to have:
`Build-Conflicts: libayatana-appindicator3-dev`
instead of
`Build-Depends: libayatana-appindicator3-dev`

and rebuilt package with `debuild -i -us -uc -b`. After installing created packages, it restores correct behaviour  "left-click tray icon to show/hide transmission main window" 
(which is also how it was working in previous Debian releases).

Right-clicking the tray icon still shows window with: 
"Show Transmission / Open / Open URL / Pause etc" menu, as 
expected.

So I guess it is ayatana-appindicator support which breaks
left-click action and make it same as right-click action (at least in icewm which I use)

**Comment by KosmiK2001** [comment]
I can confirm that the "appindicator" is a problem.
OS: Gentoo.
USE = "- appindicator". Now the behavior when left-clicking the mouse is minimized to tray.

**Comment by kushraj** [comment]
@KosmiK2001 can you explain the workaround pls

**Comment by KosmiK2001** [comment]
@kushraj 
USE flag >> "appindicator : Build in support for notifications using the libindicate or libappindicator plugin"
transmission 3 ebuild: "-DWITH_LIBAPPINDICATOR=$(usex appindicator ON OFF)"

**Comment by kushraj** [comment]
@KosmiK2001 Is this gentoo specific ? can't figure out how to add this flag while compiling from source.
Can you explain in detail

**Comment by KosmiK2001** [comment]
@kushraj 
cmake -C /var/tmp/portage/net-p2p/transmission-3.00-r1/work/transmission-3.00_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_DOCDIR=share/doc/transmission-3.00-r1 -DENABLE_GTK=ON -DENABLE_LIGHTWEIGHT=OFF -DENABLE_NLS=ON -DENABLE_QT=OFF -DENABLE_TESTS=OFF -DUSE_SYSTEM_EVENT2=ON -DUSE_SYSTEM_DHT=OFF -DUSE_SYSTEM_MINIUPNPC=ON -DUSE_SYSTEM_NATPMP=ON -DUSE_SYSTEM_UTP=OFF -DUSE_SYSTEM_B64=OFF -DWITH_CRYPTO=openssl -DWITH_INOTIFY=ON -DWITH_LIBAPPINDICATOR=OFF -DWITH_SYSTEMD=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-p2p/transmission-3.00-r1/work/transmission-3.00_build/gentoo_toolchain.cmake  /var/tmp/portage/net-p2p/transmission-3.00-r1/work/transmission-3.00
**-DWITH_LIBAPPINDICATOR=OFF**

**Comment by mnalis** [comment]
@kushraj you can alternatively just remove your appindicator devel package (in Debian: `dpkg -r libayatana-appindicator3-dev`) and then build from source as you normally would...

**Comment by kushraj** [comment]
Well this workaround won't work anymore on arch/sway which deosn't support anything other that libappindicator-gtk3 now. 
As per #1387 , there is way to to bind two different toggle to tray-icon with different mouse buttons based on libappindicator api. can someone able enough take a look in this

**Comment by JpegXguy** [comment]
According the Arch bug report, the previous gtk tray ison API doesn't work under Wayland. As a Cinnamon user, I don't really use Wayland day to day, so I haven't tested anything
