### ISSUE TITLE
macOS upload not working

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4117]
### What is the issue?

Did #4116 re-add any of the previous code from the recent regression? Peers are receiving data from everyone but me :-(

### Which application of Transmission?

macOS app

**Comment by robd003** [comment]
I'm also seeing this issue @ckerr

**Comment by Coeur** [comment]
At least, the code change is small, so a temporary revert of #4116 can solve it for those building from sources.

**Comment by Coeur** [comment]
I found a one line change that can solve it. I made a PR.

**Comment by GaryElshaw** [comment]
Thanks for your work Antoine!

**Comment by ckerr** [comment]
@Coeur you are on the right track, I agree that's where the problem is, but #4119 causes a different error. I found a different one-liner, `is_running_ = is_repeating_;`, that seems to work.

https://github.com/transmission/transmission/pull/4121 has that one-liner plus another 300 lines for a new test suite to exercise this code :tada: 

Thanks both to @Coeur for getting 3/4 of the way to the fix and to @GaryElshaw for reporting the issue so quickly. :green_heart:
