### ISSUE TITLE
macOS warnings during cmake build

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4152]
### What is the issue?

It could be my lack of attention, but a couple of potentially new warnings during cmake build of the macOS client with TorrentTableView.mm and PrefsController.mm.

[PrefsController.txt](https://github.com/transmission/transmission/files/9996567/PrefsController.txt)

[TorrentTableView.txt](https://github.com/transmission/transmission/files/9996568/TorrentTableView.txt)

### Which application of Transmission?

macOS app

**Comment by Coeur** [comment]
- NSStringPboardType warning is because you were building with an incorrect deployment target, so it's fixed in #4156.
- NSUnarchiver warning is fixed in #4113
- other deprecation warnings were already there for a long time (especially when using Xcode)

I recommend closing this issue, as it's not a user-facing issue (those are just deprecation warnings), and it requires multiple pull requests to be addressed (one per warning type), and that is already an ongoing effort. Just pick the warning that you want to fix and attempt to fix it. :)
