### ISSUE TITLE
Crash on exit on d2125ee96 in tr_session::tr_udp_core::sendto: bad access to udp_socket_

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#4184]
### What is the issue?

Maybe in the destructor, we should set TR_BAD_SOCKET before closing the socket? Like:
```
auto udp_socket_ref = udp_socket_;
udp_socket_ = TR_BAD_SOCKET;
tr_netCloseSocket(udp_socket_ref);
```

![Capture d’écran 2022-11-16 à 02 47 53](https://user-images.githubusercontent.com/839992/202002443-9da60e3c-2069-4393-a212-63b791c7f5a7.png)

### Which application of Transmission?

macOS app

### Which version of Transmission?

d2125ee96

**Comment by ckerr** [comment]
The problem is this block in `tr_session::closeImplPart2()`

```c++
    this->udp_core_.reset();

    stats().saveIfDirty();
    peer_mgr_.reset();
```

`peer_mgr_` depends on `udp_core_`, so this order of destruction is backwards.

If this code needs to exist, then these lines need to be reordered. It would be better first to figure out if the standard destructor handles this, since a lot of work has been done to order these fields in order of dependency in `tr_session`. Possibly more of these lines could just be removed in `closeImplPart2()`.

**Comment by ckerr** [comment]
This still isn't properly fixed, but the remaining pieces aren't a blocker for another beta.
