### ISSUE TITLE
macOS crash reporter is crashing

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4288]
### What is the issue?

I think it might be related to #4285, but quitting Transmission appears to be crashing the crash reporter. Console report below.
 
[ReportCrash-2022-12-01-113600.ips.txt](https://github.com/transmission/transmission/files/10127823/ReportCrash-2022-12-01-113600.ips.txt)

### Which application of Transmission?

macOS app

**Comment by ckerr** [comment]
*Achievement unlocked*

**Comment by ckerr** [comment]
I found one more tr-utp crash on shutdown in https://github.com/transmission/transmission/pull/4287, so first thing is to make sure you're using a build that has that commit in it.

AFAICT there's nothing actionable in the macOS crash reporter report. :dizzy: If Transmission is still crashing on shutdown, maybe run it in a debugger in Xcode and manually get a trace out of it that way instead of relying on the crash reporter?

**Comment by GaryElshaw** [comment]
> _Achievement unlocked_

I was going to say the same thing! :-)

**Comment by GaryElshaw** [comment]
Yep, that last change to utp has fixed the issue. Yay!
