### ISSUE TITLE
can't resume magnet tasks added in 3.00

### ISSUE THREAD

**Issue by trim21** [transmission/transmission#4295]
### What is the issue?

I have some almost dead tasks added from magent url in 3.00 and haven't downloaded torrent info successfully. 

And when I upgrade to 4.0.0 beta 2 these tasks are not resumed, they just disappear, and when I downgrade to 3.00, these tasks come back.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0 beta 2

**Comment by killemov** [comment]
What are dead tasks and magents?

Does this happen to magnets only? In non-metadata-complete form or always? (So a torrent has 100% metadata complete and STILL disappears after upgrading?)

**Comment by trim21** [comment]
> What are dead tasks and magents?
> 
> Does this happen to magnets only? In non-metadata-complete form or always? (So a torrent has 100% metadata complete and STILL disappears after upgrading?)

magnet only task without torrent metadata

**Comment by killemov** [comment]
Maybe this issue could be seen as a note to the devs to check if something broke during development of this new major version. BUT ... magnets in Transmission-daemon are supposed to have a very limited lifespan until they are transformed into torrents. It's like having Transmission-daemon remembering the URL from where you downloaded a torrent from. Once you have the torrent, it's kind of useless for you. So copy the magnets to a text file before you upgrade and re-add them after.

**Comment by ckerr** [comment]
Magnets generally "graduate" into fully-fledged torrents very quickly so I don't think this is a high priority. This probably isn't going to get fixed unless somone really cares about this and wants to submit a patch.

The easiest workaround would be to re-add the magnet links in 4.

**Comment by WowbaggersLiquidLunch** [comment]
> The easiest workaround would be to re-add the magnet links in 4.

It's not really easy when I have lots of links added months ago. It's basically impossible for me to find all the original links.

> This probably isn't going to get fixed unless somone really cares about this and wants to submit a patch.

Could someone points me to the relevant files/components/subsystems that might be causing this bug?

**Comment by trim21** [comment]
> It's not really easy when I have lots of links added months ago. It's basically impossible for me to find all the original links.

you can use api to get infohash and concat a magnet link I think...

**Comment by Coeur** [comment]
My quick investigation:

- In Transmission 3, you can add paused magnets, close the app, re-open the T3 app, and the magnet will still be there. 👍

- In Transmission 4, you can add magnets, pause them, close the app, re-open the T4 app, and the magnet will still be there. 👍

- A paused magnet added in T3 will be lost when updating to T4. 👎

- A paused magnet added in T4 will be missing when downgrading to T3 (but well, we don't give downgrading support). 👎

The issue seems to be a Core issue because when going T3 -> T4, the function `tr_sessionGetAllTorrents` is already missing the T3 magnets, so it's unlikely caused by the macOS code.
