### ISSUE TITLE
Feature Request: "last known location" for torrents with missing data

### ISSUE THREAD

**Issue by enken** [transmission/transmission#4388]
### What is the issue?

It would be helpful if the Torrent Inspector - General Info tab could show where the data *was*, rather than just displaying "N/A" for Where, Data File field.
![Screen Shot](https://user-images.githubusercontent.com/4615650/208242342-bd899008-8962-4c4d-8562-9d4e8f0ba4f5.png)

My suggestion is that "Data File: N/A" be amended to display where Transmission is set to look for the data (basically where the data was last known to be), something like: "Data File: N/A — Was: /Volume/Name/Folder"

### Which application of Transmission?

macOS app

### Which version of Transmission?

3.00 (f4489c982e)

**Comment by Coeur** [comment]
@BogdanArdelean
@enken 
Can you clarify in which situation does this happen (or which situation you want to address in priority)?
- was it because you moved the file somewhere else using Finder?
- was it because you deleted the file using Finder?
- was it because you unplugged some external hard drive?
