### ISSUE TITLE
with many torrents: slow interface (GTK|QT) (mainly moving location)

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#4399]
### What is the issue?

With many torrents (something up to 3,200+) the interface is intermittently usually somewhat slow (when other desktop things aren't): opening and searching may just be barely slow, but altering a torrent (location, maybe some other things) might take all day/night to complete.  WIth moving location, it'll complete after a time (such as disappear from /home/user) but then the action/progress boxes stay open hours longer or all day/night.
        I usually test while keeping 1/32 to 8/32 threads mostly free (might average to 4/32 each 4+GFlops) and anything from four to 50+GB RAM free but can tweak the threads at least (most RAM just gets used by transmission itself).

### Which application of Transmission?

GTK+, QT apps on Linux, BSD, etc.

### Which version of Transmission?

e694c3e and many earlier versions this year

**Comment by mikedld** [comment]
https://github.com/transmission/transmission/issues/4193#issuecomment-1317024057

**Comment by killemov** [comment]
@dchmelik The UI gets slower the more torrents you have. There is only so much that can be done with restructuring the used UI components. The web UI also has a similar problem, but in that case the communication with Transmission daemon is the bottleneck. If I recall correctly, it became unusable for me at ~500 torrents. I had to solve that problem by rolling my own. [Shift](https://github.com/killemov/Shift) now manages 20k+ torrents on that same VERY limited hardware. (QNAP, Kirkwood)

Oh, and on the subject of moving content with Transmission: That should work fine within a single filesystem. If you're moving content across filesystems, you can expect a delay because TM is copying that data, which takes resources away from anything else, including UI updates.

**Comment by ckerr** [comment]
I'm running about 25k torrents on transmission-qt and do not see a problem scrolling through the list, so I don't think it's a rendering problem there.

I do think there is a scrolling problem in the web client and @killemov if you want to add a virtual scroll to the web client to solve it I would be *very* happy to review that. But I don't think the issue you're describing here is the same as 4399.

**Comment by killemov** [comment]
> I'm running about 25k torrents on transmission-qt and do not see a problem scrolling through the list, so I don't think it's a rendering problem there.

Ok. So filesystem boundaries crossed?
 
> I do think there is a scrolling problem in the web client and @killemov if you want to add a virtual scroll to the web client to solve it I would be _very_ happy to review that. But I don't think the issue you're describing here is the same as 4399.

I haven't used or touched the included web UI for many years, but THE problem that broke it was transmitting semi-static data (torrent hash, torrent name, ...) every time. Shift suffers from a related problem where sometimes fields do not get updated due to dropped response messages. And at 20k torrents even Shift shows a massive delay when a large number of torrents get initialized. So I'm considering chunking the initialization process to 512 (configurable) torrents a chunk. A lot more optimization could be done if the rpc-spec supported a query based way of fetching data from the daemon. Now it is all filtering on the client side.

**Comment by ckerr** [comment]
> but THE problem that broke it was transmitting semi-static data (torrent hash, torrent name, ...) every time

Yep, both tr-web and tr-qt used to be bad about this. 3.00 fixes it for tr-qt and 4.0.0 fixes it for tr-web.

The main window is still filled with a _ton_ of divs if there is a large number of torrents though. It needs to be using a virtual scroll instead.

**Comment by ckerr** [comment]
>  There are no more details I can explain unless you want me to get some sort of debug/log file.

https://github.com/transmission/transmission/issues/4193#issuecomment-1317024057

**Comment by dchmelik** [comment]
> > There are no more details I can explain unless you want me to get some sort of debug/log file.
> 
> [#4193 (comment)](https://github.com/transmission/transmission/issues/4193#issuecomment-1317024057)

What does that mean?  Do you want a gdb backtrace?  If so, how do I do that for transmission?

**Comment by ckerr** [comment]
```sh
$ gdb transmission-qt
(gdb) handle SIGPIPE nostop noprint pass
(gdb) r
# use Transmission normally until it freezes...
# when it freezes hit ctrl-c to get the (gdb) prompt again ...
(gdb) thread apply all bt
```

and the output of that command is what you'll attach to this ticket

**Comment by killemov** [comment]
@dchmelik A lot of Linux/BSD/... installs have a separate /home partition. So you could be moving content across filesystem boundaries without you even knowing about it.

**Comment by dchmelik** [comment]
In this [gist](https://gist.github.com/dchmelik/73ebfb80e2493bcd1a1810e688307942) I tried to move FreeBSD UNIX ISO one directory up, which worked, then when I pressed 'close', it wasn't responding, when it used to respond to that fast in the past.

**Comment by ckerr** [comment]
@dchmelik could you re-run the test again  https://github.com/transmission/transmission/pull/4625? I am wondering if that fixed this issue.

**Comment by ckerr** [comment]
@dchmelik could you re-run the test again #4625? I am wondering if that fixed this issue.

**Comment by dchmelik** [comment]
Seems fixed sometime by transmission 4.n.
