### ISSUE TITLE
Third-Party deps: libpsl v0.21.2 available

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4476]
### What is the issue?

Just a headsup of a new release. https://github.com/rockdaboot/libpsl/releases/tag/0.21.2

### Which application of Transmission?

All

### Which version of Transmission?

beta 2

**Comment by ckerr** [comment]
> Fix stack buffer overflow WRITE 1 in domain_to_punycode()
(Relevant only when built without any IDNA library.)
>
> Fix undefined behavior in library code

Potentially worth picking up

**Comment by ckerr** [comment]
Unfortunately f2bdc1709d662c3d6af56b019def0b9410cd974a means 0.21.2 fails to build on Windows.

There is a fix at c47cf796fcf98641cb34929d17de041b26c54447 but it's not in a released version. We should revisit when 0.21.3 is released.

**Comment by GaryElshaw** [comment]
It's not like the project doesn't already use non-release versioning.

**Comment by ckerr** [comment]
> It's not like the project doesn't already use non-release versioning.

 :confused:  Where? I think our third-parties all pin to stable upstream releases where possible. IIRC we've deviated from that only when upstream is doing something that makes it impossible, e.g. libutp and wide-integer which don't actually do releases.

**Comment by GaryElshaw** [comment]
> e.g. libutp and wide-integer which don't actually do releases.

Yes, those you mention above; and wide-integer has also had some significant updates this last week. I'm still very confused why project dependencies, and updating them, are treated as being so 'optional'. And i've never completely understood if you or Mike were actively watching for updates? I'll stop monitoring them if you are.

**Comment by ckerr** [comment]
> Yes, those you mention above; and wide-integer has also had some significant updates this last week.

OK so if we're agreed that the project is using snapshots instead of stable releases only when it's unavoidable, then you understand why I disagree with "It's not like the project doesn't already use non-release versioning" as a rationale to use snapshots for a project like libpsl, yes?

> I'm still very confused why project dependencies, and updating them, are treated as being so 'optional'

I think we've discussed this before, e.g. https://github.com/transmission/transmission/issues/3019#issuecomment-1113468102 and https://github.com/transmission/transmission/issues/2997#issuecomment-1111015716 and in particular https://github.com/transmission/transmission/issues/2997#issuecomment-1112448139

> And i've never completely understood if you or Mike were actively watching for updates? I'll stop monitoring them if you are.

I check from time to time, but you usually catch them before I do :racehorse: so I usually appreciate the heads-up
