### ISSUE TITLE
to continue firefox partial downloads

### ISSUE THREAD

**Issue by qdinar** [transmission/transmission#4505]
### What is the issue?

idea of a new feature. to be able to continue firefox and other browser partial downloads. if it is already possible, then write a tip about that in the interface. i see there is some feature to choose local file, but i am afraid it supports only torrent downloaded file. torrent downloaded files are different from browser downloaded files, torrents' are of full size immediately, and browser file grows with time.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

2.94

**Comment by ckerr** [comment]
I don't understand this request. What does it mean to be able to continue browser partial downloads? Literally to finish downloading a file that someone started to download with a browser?

**Comment by qdinar** [comment]
yes. why not, is there some problem? today i downloaded an iso with browser
and it was terminated somehow, and browser could not continue it. why not
to use that data? second time, today, i terminated it by myself by mistake,
it was other mirror, and i could not continue it again. i made third try
with torrent to be sure.

(i write this reply via email).

2023 Yanv 1, Yaksh 20:45 Charles Kerr ***@***.***>:

**Comment by ckerr** [comment]
It just seems like a different use. For example a torrent client isn't going to know the URL that the browser was using to download the iso, so how could a torrent client resume it?

Also, why would a torrent client be the go-to tool for resuming a browser download, instead of e.g. `wget --continue`?

Sorry, I think I'm misunderstanding your suggestion :slightly_smiling_face:

**Comment by qdinar** [comment]
the old url should not be used, only local file address. user maybe
required to manually rename the local file, removing part extension, and
maybe adding proper extension, i do not remember.

wget also may not be able  to continue. it depends on server. user may not
know proper url, for server that supports continuation. but torrent always
supports continuation.

(i write this via email, deleted the suggested cite this time).

**Comment by ckerr** [comment]
If a .torrent exists of the iso,  you should be able to add it and resume the download that was started with the browser. If you have 'partial filenames' enabled (e.g. the `.part` file suffix for incomplete files) then you may need to rename the partially-downloaded file for Transmission go pick it up.

But Transmission needs that metainfo in order to continue downloading; e.g. the info hash is needed in order to announce to a tracker or to handshake with other bittorrent peers. 

So, in the sense of adding a .torrent file that already has partially-downloaded data from a browser -- that already exists. In the sense of just completing a file without knowing its metadata, I don't think that's possible in the BitTorrent protocol without at least an info hash.
