### ISSUE TITLE
Fails to build on Freebsd - undefined symbol: libiconv

### ISSUE THREAD

**Issue by GunbleR** [transmission/transmission#4547]
### What is the issue?

unable to build in freebsd after 57e6b06921841c02d99e4a517b050d4bbb6e73bf commit.
```
[ 64%] Building CXX object libtransmission/CMakeFiles/transmission.dir/webseed.cc.o
[ 65%] Linking CXX static library libtransmission.a
[ 65%] Built target transmission
[ 66%] Building CXX object tests/libtransmission/CMakeFiles/subprocess-test.dir/subprocess-test-program.cc.o
[ 66%] Linking CXX executable subprocess-test
ld: error: undefined symbol: libiconv_open
>>> referenced by utils.cc:378 (/root/Transmission_4b3/libtransmission/utils.cc:378)
>>>               utils.cc.o:(tr_strvUtf8Clean(std::__1::basic_string_view<char, std::__1::char_traits<char> >)) in archive ../../libtransmission/libtransmission.a
>>> referenced by utils.cc:378 (/root/Transmission_4b3/libtransmission/utils.cc:378)
>>>               utils.cc.o:(tr_strvUtf8Clean(std::__1::basic_string_view<char, std::__1::char_traits<char> >)) in archive ../../libtransmission/libtransmission.a

ld: error: undefined symbol: libiconv
>>> referenced by utils.cc:387 (/root/Transmission_4b3/libtransmission/utils.cc:387)
>>>               utils.cc.o:(tr_strvUtf8Clean(std::__1::basic_string_view<char, std::__1::char_traits<char> >)) in archive ../../libtransmission/libtransmission.a
>>> referenced by utils.cc:387 (/root/Transmission_4b3/libtransmission/utils.cc:387)
>>>               utils.cc.o:(tr_strvUtf8Clean(std::__1::basic_string_view<char, std::__1::char_traits<char> >)) in archive ../../libtransmission/libtransmission.a

ld: error: undefined symbol: libiconv_close
>>> referenced by utils.cc:388 (/root/Transmission_4b3/libtransmission/utils.cc:388)
>>>               utils.cc.o:(tr_strvUtf8Clean(std::__1::basic_string_view<char, std::__1::char_traits<char> >)) in archive ../../libtransmission/libtransmission.a
>>> referenced by utils.cc:388 (/root/Transmission_4b3/libtransmission/utils.cc:388)
>>>               utils.cc.o:(tr_strvUtf8Clean(std::__1::basic_string_view<char, std::__1::char_traits<char> >)) in archive ../../libtransmission/libtransmission.a
c++: error: linker command failed with exit code 1 (use -v to see invocation)

```
have libiconv-1.17 pkg installed (as dependencie)
806491232b commit does build and work

running TrueNAS core-13.0-U3.1
jail 13.1-RELEASE
intel cpu based machine

### Which application of Transmission?

None

### Which version of Transmission?

57e6b06921841c02d99e4a517b050d4bbb6e73bf

**Comment by mikedld** [comment]
Is that with a clean build, or could you try doing one?

**Comment by GunbleR** [comment]
i did 

$ cd Transmission/build
$ make clean
$ git submodule foreach --recursive git clean -xfd
$ git pull --rebase --prune
$ git submodule update --recursive
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ make

later substituted git pull --rebase --prune      for      git reset --hard <commit>

**Comment by mikedld** [comment]
Please try deleting the build directory and configuring from scratch, `make clean` might not be enough.

**Comment by GunbleR** [comment]
didnt help. 
i tried cloning git to new dir and building from there, same errors

**Comment by mikedld** [comment]
What does it print if you run `grep -i iconv CMakeCache.txt` in your build directory?

**Comment by GunbleR** [comment]
//Details about finding Iconv
FIND_PACKAGE_MESSAGE_DETAILS_Iconv:INTERNAL=[built in to C library][v()]
//Test Iconv_IS_BUILT_IN
Iconv_IS_BUILT_IN:INTERNAL=1

**Comment by mikedld** [comment]
So it thinks that iconv functionality is built into your libc and no additional libraries need linking. Trying to compile the [test program that CMake is using](https://github.com/Kitware/CMake/blob/b2a6527f37f159b089579303899bda004cdc9877/Modules/FindIconv.cmake#L102-L111) on our CI machine manually (which is FreeBSD 13.1) confirms that libc indeed provides the `iconv_open`, `iconv`, and `iconv_close` functions.

What's weird though is that the error message you're getting refers to those symbols as having a `lib` prefix, and I'm not sure where that is coming from.

**Comment by mikedld** [comment]
I guess those symbols might be coming from that libiconv package that you've installed, which apparently shouldn't be necessary. Did I say that I hate FreeBSD with its /usr vs. /usr/local shit?..

**Comment by GunbleR** [comment]
well, apperantly libiconv required by glib in freebsd.
comment from 2014 on glib freshports:
```
Add patch from upstream to fix crasher in open-vm-tools [1]
Add back depend on libiconv. This is needed because our base iconv
doesn't do utf-8 -> wchar_t apparently. [2] wchar_t is used by glibmm.
```
force removing libiconv and clean building does work, but i dont want to install it in that jail.
I will try in new jail later today.

**Comment by mikedld** [comment]
If you're not building transmission-gtk I see no problem since none of the other targets depend on glib/gtk and libtransmission (which is what's using iconv) doesn't need `wchar_t` support, so using the libc version is fine and preferred.

If you are building transmission-gtk, you want us to either a) pick up libiconv version and use it for everything (easier) or b) make it so that libtransmission uses libc version and transmission-gtk uses libiconv version (harder). We could work it around with a) on our end (not sure if we want to...) or leave it up to you (because it's a platform-specific quirk). Basically, I'd try passing `-DIconv_IS_BUILT_IN:BOOL=OFF` to cmake when configuring the build system to see if that makes it better.

**Comment by GunbleR** [comment]
Thanks. I was able to build transmission with
 - without building gtk (-DENABLE_GTK=OFF) and without installing glib and libappindicator
 - with those packages installed and -DIconv_IS_BUILT_IN:BOOL=OFF.
in both jails, i was able to start the daemon, connect to it from web and remote gui and download a file without errors in message log.
I dont use gtk, as its running in NAS jail.
I will re-build my main instance without GTK and QT and with minimum packages.

apperantly it happened because i skim-read  "required development tools for GTK" as "all the packages you need to build everything" and installed all those. ffs.
you can close the issue if you want

**Comment by mikedld** [comment]
As mentioned above, I'm not that keen on adding a workaround for FreeBSD (and potentially other BSDs, and potentially having to make it more robust because we might still pick up wrong headers even if we don't build transmission-gtk). I do however think it's a positive change that core no longer depends on libiconv package.

Your thoughts, @ckerr?

**Comment by ckerr** [comment]
On the topic of libtransmission using iconv:

Looks like iconv is only used by `tr_strvUtf8Clean()`, which in turn is only used by `torrent-metainfo.cc` for use in handling .torrent files that incorrectly use a non-utf8 encoding. It's used to sanitize the following fields:

- comment
- creator
- source
- name

It's increasingly rare to see non-utf8 torrents; and even when if one was encountered, all of these fields are informative -- they exist to be displayed in the Details Dialog / Torrent Inspector, rather than changing the behavior of the torrent.

@mikedld I'd appreciate a second opinion on that but if that sounds right to you, I can make a PR that removes iconv use from libtransmission/utils.cc and removes `HAVE_ICONV` from our tooling. It's not a big change either way, but it would simplify the build a little and remove one place where Transmission's behavior can differ based on how it's compiled.

**Comment by mikedld** [comment]
IIUC name actually affects file/directory names, so it's better be valid UTF-8 (valid filesystem encoding in the end, to be precise, but we assume it's always UTF-8). For the other 3 I don't care that much if we just replace all invalid sequences with question marks or some other filler. If that filler turns out to be a char suitable for file/directory names (so, probably not an actual question mark but something like �), sanitizing the name the same way is okay too. I bet utf8cpp's capabilities should be more than enough for that.
