### ISSUE TITLE
Colour and contrast in the GTK client 4.0.0-beta.3.dev

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4667]
### What is the issue?

A couple of issues with the font and graphics colours in the GTK client (Manjaro 43.2 w/ Wayland).

The peers window
![Screenshot from 2023-01-26 15-29-31](https://user-images.githubusercontent.com/69029666/214745529-3bcce425-0dc3-4c52-999b-b667a107e296.png)

The contrast with the buttons when a torrent is selected is too light.
![Screenshot from 2023-01-26 15-31-31](https://user-images.githubusercontent.com/69029666/214745641-04eca9c2-676b-469a-81ef-6f89f7304ea6.png)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0-beta.3.dev (b055b98d0f)

**Comment by ckerr** [comment]
AFAIK transmission-gtk isn't doing anything to these fonts or colors. 

If this is an actual theme bug (maybe? IDK?) then it should be reported upstream to the repo of the theme you're using. You can find its name with `$ gsettings get org.gnome.desktop.interface gtk-theme`

Since this isn't a Transmission issue per se I'm closing as 'declined'

**Comment by GaryElshaw** [comment]
This is with Adwaita, and it's not a problem in dark mode.

![Screenshot from 2023-01-26 17-05-21](https://user-images.githubusercontent.com/69029666/214756438-0192edc2-fdbd-4eb1-84fd-89b124857f81.png)

**Comment by ckerr** [comment]
> This is with Adwaita, and it's not a problem in dark mode.

transmission-gtk doesn't do anything with the fonts or colors for these buttons in Adwaita or other themes, so :man_shrugging: 

> As an aside, is there no way to change the column order in the peers view?

No there's not.
