### ISSUE TITLE
Crash to desktop when deleting torrent+file on Windows 11

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#4713]
### What is the issue?

Description
Faulting Application Path:	C:\Program Files\Transmission\transmission-qt.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	transmission-qt.exe
Application Version:	4.0.0.0
Application Timestamp:	63dd3c28
Fault Module Name:	transmission-qt.exe
Fault Module Version:	4.0.0.0
Fault Module Timestamp:	63dd3c28
Exception Code:	c0000005
Exception Offset:	000000000017eaee
OS Version:	10.0.22621.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	6462
Additional Information 2:	646296149e703fd391247367808ba666
Additional Information 3:	2665
Additional Information 4:	2665d9cecc74c2f27ccb28830274864c

Extra information about the problem
Bucket ID:	3753fc1207b90c32f0527d3a3050d7ce (1176140141569300430)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.0-beta.3.dev (fbb98ada4a)

**Comment by ckerr** [comment]
WIthout a crash report or a recipe to reproduce the issue, there's not much to go on.

Is the problem reproducible?

**Comment by Pentaphon** [comment]
> WIthout a crash report or a recipe to reproduce the issue, there's not much to go on.

How do I get a crash report from Windows? I naively thought the event viewer would be enough.

**Comment by ckerr** [comment]
@mikedld is there a preferred way of generating crash reports on Windows?

**Comment by mikedld** [comment]
Based on the provided information, crash seems to have occured in `tr_announcerNextManualAnnounce` somewhere between these lines (most probably 744): https://github.com/transmission/transmission/blob/fbb98ada4ae8b90f9d76a91fbc0de4ff18662669/libtransmission/announcer.cc#L741-L746

```
0017EAE0 | 48:8B89 00070000 | mov rcx,qword ptr ds:[rcx+700]    | announcer.cc:741
0017EAE7 | 48:C7C0 FFFFFFFF | mov rax,FFFFFFFFFFFFFFFF          |  
0017EAEE | 4C:8B41 08       | mov r8,qword ptr ds:[rcx+8]       |  
0017EAF2 | 48:8B09          | mov rcx,qword ptr ds:[rcx]        |  
0017EAF5 | 49:3BC8          | cmp rcx,r8                        |  
0017EAF8 | 74 29            | je transmission-qt.7FF75AF9EB23   |  
0017EAFA | 66:0F1F4400 00   | nop word ptr ds:[rax+rax],ax      |  
0017EB00 | 80B9 0C010000 00 | cmp byte ptr ds:[rcx+10C],0       | announcer.cc:746
0017EB07 | 74 0E            | je transmission-qt.7FF75AF9EB17   |  
0017EB09 | 48:8B91 D0000000 | mov rdx,qword ptr ds:[rcx+D0]     | announcer.cc:748
0017EB10 | 48:3BD0          | cmp rdx,rax                       |  
0017EB13 | 48:0F4CC2        | cmovl rax,rdx                     |  
0017EB17 | 48:81C1 10010000 | add rcx,110                       | announcer.cc:744
0017EB1E | 49:3BC8          | cmp rcx,r8                        |  
0017EB21 | 75 DD            | jne transmission-qt.7FF75AF9EB00  |  
0017EB23 | C3               | ret                               | announcer.cc:753
```

Exception code 0xC0000005 means access violation (a.k.a. segmentation fault). Exception offset 0x17EAEE (3rd line from the top in disassembly above) seems to suggest that `tor->torrent_announcer` (pointed to by `rcx`) is either null or points to otherwise inaccessible memory.

**Comment by Pentaphon** [comment]
> is there a preferred way of generating crash reports on Windows?

And can we put this info in the readme since it doesn't seem to be anywhere on this github project page?

**Comment by mikedld** [comment]
For the preferred way, one might configure automatic debugging (https://learn.microsoft.com/en-us/windows/win32/debug/configuring-automatic-debugging), or add a few registry keys (per https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps; we may even include these in the installer, if necessary) so that minidumps are generated automatically and then use WinDbg (https://apps.microsoft.com/store/detail/windbg-preview/9PGJGD53TN86 or an older version) after the fact, to get a stacktrace and maybe some other info (on the user's side, because even minidumps may contain PII). Might be there's an easier tool, as WinDbg isn't particularly fun, or we may be able to provide a script that extracts necessary info.

Microsoft provides access to WER reports (https://learn.microsoft.com/en-us/windows/win32/wer/windows-error-reporting), but only to people willing to pay for an expensive EV code signing certificate from a selected list of providers, so a no-go.

Tools like Google's Crashpad (https://github.com/chromium/crashpad) work on minidumps as well, and since those may contain PII we wouldn't want to upload them anywhere, so people would still need to somehow analyze the dump locally.

**Comment by ckerr** [comment]
@mikedld that's some pretty nice detective work!

Happily, `tr_announcerNextManualAnnounce()` only has one caller and `tor->torrent_announcer` is only set to null in one place: in the session thread when the torrent is being destroyed. From these two clues, the race condition is pretty clear:

The root issue is that `tr_rpc_request_exec_json()` is getting called from outside the session thread does not have a session lock.

`tr_rpc_request_exec_json()` takes a tr_variant and that class doesn't have good copy/move semantics, delegating all this work to the session thread is problematic. The shortest-path fix would be to get a session lock instead to ensure that we don't execute this RPC while also destroying a torrent.
