### ISSUE TITLE
consider removing the `ENABLE_UTP` build option

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#4751]
### What is the issue?

Inspired by https://github.com/transmission/transmission/issues/4748.

Maybe the `ENABLE_UTP` build option to compile without UTP isn't needed anymore. It was added IIRC a decade ago when one distro had reservations about libutp but I think the library has proven itself safe since then. Also, the overwhelming majority of BitTorrent clients use UTP and so users who don't have it would be at a disadvantage.

We should probably just unconditionally build with UTP.

### Which application of Transmission?

None

### Which version of Transmission?

4.0.0

**Comment by mikedld** [comment]
One other thing was that libutp was the only C++ dependency, with all other dependencies and most of our own code written in C, making C++ compiler optional as well if there was such a need. No longer relevant.

**Comment by ckerr** [comment]
@mikedld I'd like a second opinion. Is removing the ability to disable libutp a breaking change?

I don't think this will affect many (any?) users but if we're going by the book I think this is arguably a breaking change and so it would need to wait for the next semver-major bump

**Comment by mikedld** [comment]
If someone was purposely disabling uTP support for some very good reason and won't be able to do so after the option is removed, I'd say yes, this looks like a breaking change. On the other hand, I'm not sure being unable to disable it at configure time is that critical for the end result (unless it fails to build) as the option to disable it at runtime would still be there. It also feels less than major because we bundle our own version to fallback to, so it doesn't even have to be present in the system, and it won't bring in any other requirements because it doesn't have any dependencies of its own and its code is C++98/03 which is less than our own C++17.

I guess what I'm saying is, I'd be okay with it being a minor release (if there will be one), but I'm not that good with semver :-P It's not like there're other builds that depend on Transmission (it being the end product, not an intermediate link in the chain of someone else's dependencies), and it's probably not like the majority of users even know/care what semver is.

**Comment by reardonia** [comment]
Strongly prefer the WITH_UTP / ENABLE_UTP option.  For a variety of safety issues, particularly with respect to private trackers, it's good to keep this disabled and reduce attack surface-area.

It's not difficult to properly disable.  It requires a few more #ifdef 's

**Comment by ckerr** [comment]
That's a reasonable argument.

@reardonia do you want to make a patch to properly disable?

**Comment by reardonia** [comment]
The logic in tr_peerIo::new_outgoing() seems to have changed.  In Tr3, it would open BOTH UTP and TCP sockets, starting with UTP.  But in Tr4, it tries UTP and returns, looks like it never tries TCP?  Is this intentional?

**Comment by ckerr** [comment]
@reardonia I don't think that's correct? It looks to me like it tries TCP if udp_connect fails?

As it happens there is an adjacent PR for new_outgoing at https://github.com/transmission/transmission/pull/4826 which does change this control flow but AFAICT even in 4.0.0 TCP is tried if utp_connect fails

**Comment by reardonia** [comment]
> @reardonia I don't think that's correct? It looks to me like it tries TCP if udp_connect fails?

Sorry, yes, you're right.  for Tr3, after connection or handshake timeout, it retries as TCP. I think I confused this with the IPv6 "upgrade" case, where IPv6 address is received via PEX.

**Comment by ckerr** [comment]
Okay.

Closing this ticket since the job of considering removing ENABLE_UTP is done.

If you want to do a patch to improve disablikg that feature that would be great but this ticket doesn't need to block on that work.

**Comment by ckerr** [comment]
Reopening this issue after the looping discussion in #4882. To break out of that loop I'd like to loop on this issue instead :laughing: 

Going back to the rationale for allowing UTP to be removed altogether:

> Lastly, "disabling" means not including code. Making it a runtime option means that it remains part of the attack surface area, even if you don't see it on first glance.

I don't think this is necessarily true. Maybe superficially so in that the code will be linked into Transmission so it exists there, but if we never call `utp_init()` then surely there is no runtime surface area?

After the discussion in 4882 I'm wondering if it wouldn't just be simpler to always build with utp but have an option to not invoke it at all.

**Comment by mikedld** [comment]
> ... if we never call `utp_init()` then surely there is no runtime surface area?

IIUC the code might still be executed if jumped to from another (compromized) part of the program.

---

I can't support the claim of libutp code in particular being more vulnerable to further exploitation (once execution is transferred there) than any other piece of code without specific proof. For example, libdht, libnatpmp, and miniupnpc are all external libraries similar to libutp in that they work with sockets and have some additional logic around, yet we're not providing options to disable their use other than in runtime. Moreover, prebuilt Windows and Mac packages always include libutp, and if we're that serious about security then those packages should come in 2 variants too, which is overkill.

Other (more or less obvious) options for those who care about security of their systems more than usual I can think of include:
* install libutp built with additional compiler/linker flags enabling various runtime checks and make sure it's found/used by Transmission build
* use shared version of libutp and enable ASLR
* invest in learning about apparmor/selinux/etc.
* don't ever run Transmission as root (which I don't believe we ever suggested anyway).

We may also support loading the [shared] library dynamically, so that if `utp_init()` isn't called the code is indeed not loaded, although this adds complexity I'm not at all sure we want.

**Comment by ckerr** [comment]
> For a variety of safety issues, particularly with respect to private trackers, it's good to keep this disabled and reduce attack surface-area.

@reardonia can you expand on this? I've never heard of any tracker disallowing UTP

**Comment by reardonia** [comment]
Frankly, this goes back many years to the bug I discovered and fixed in the libutp code (check the old old logs).  That bug was easily turned into a ROP exploit.  I don't think anyone has ever fuzzed or otherwise checked the UTP code, unlike the TCP-based codepaths. (if you want to discuss privately we can do so).  For my own part I'll keep my disable-UTP patches live and available to others. I still think it's worth maintaining the UTP+/- code option.

As for the thesis that runtime-disabled code has the same attack surface area as non-compiled code, mikedld makes great point that this isn't much different than other socket-accessing code.  That's why I also have patches for dht ;) 

the natpmp and miniupnpc code have been pretty well security tested, but not dht.

also, apologies that I cannot be consistent in my engagement here. as you've been launching Tr4, I've only got time 1-2 days/week.

**Comment by ckerr** [comment]
> (check the old old logs). 

I mean this politely, but I'm not sure how to phrase this in a polite way, so ... this is going to sound wrong but understand that I don't mean it that way:

This isn't how this works. I'm doing triage on maybe a dozen issues + PRs a day and don't have time or interest in going hunting for that. You're the one making the assertion that libutp is unsafe, so the burden is on you to provide citations for that. I'm not going to go do your research work for  you.

**Comment by reardonia** [comment]
https://www.cvedetails.com/cve/CVE-2012-6129

**Comment by reardonia** [comment]
> > (check the old old logs).
> 
> I mean this politely, but I'm not sure how to phrase this in a polite way, so ... this is going to sound wrong but understand that I don't mean it that way:

No worries, I appreciate the directness and apologize that I can't engage here with more bandwidth.

**Comment by ckerr** [comment]
I've been thinking about this one again ... 

@reardonia has done a lot of good patches and that sweat equity makes me look on this idea more favorably.

So does the CVE linked above.

... but as a practical matter, no distros are going to disable UTP support. So I don't see an audience for this build option. And if that's the case, IDK if it makes sense to have it in `transmission/transmission`.
