### ISSUE TITLE
Unable to connect to headless transmission-daemon

### ISSUE THREAD

**Issue by viggy96** [transmission/transmission#476]
I am unable to use any remote interface for the transmission-daemon I have running on my server. This occured after the DNS rebinding patch. I am using version 2.84-3ubuntu3.1. When going to the web interface, I get the message: Could not connect to the server. You may need to reload the page to reconnect.

When going to /transmission/rpc, I get the following: 
```
421: Misdirected Request
Transmission received your request, but the hostname was unrecognized.

To fix this, choose one of the following options:

Enable password authentication, then any hostname is allowed.
Add the hostname you want to use to the whitelist in settings.
If you're editing settings.json, see the 'rpc-host-whitelist' and 'rpc-host-whitelist-enabled' entries.

This requirement has been added to help prevent DNS Rebinding attacks.
```

Here is my configuration file: 
```
{
    "alt-speed-down": 50, 
    "alt-speed-enabled": false, 
    "alt-speed-time-begin": 540, 
    "alt-speed-time-day": 127, 
    "alt-speed-time-enabled": false, 
    "alt-speed-time-end": 1020, 
    "alt-speed-up": 50, 
    "bind-address-ipv4": "0.0.0.0", 
    "bind-address-ipv6": "::", 
    "blocklist-enabled": false, 
    "blocklist-url": "http://www.example.com/blocklist", 
    "cache-size-mb": 64, 
    "dht-enabled": true, 
    "download-dir": "/home/box/Downloads", 
    "download-limit": 100, 
    "download-limit-enabled": 0, 
    "download-queue-enabled": true, 
    "download-queue-size": 5, 
    "encryption": 2, 
    "idle-seeding-limit": 30, 
    "idle-seeding-limit-enabled": false, 
    "incomplete-dir": "/home/debian-transmission/Downloads", 
    "incomplete-dir-enabled": false, 
    "lpd-enabled": true, 
    "max-peers-global": 200, 
    "message-level": 1, 
    "peer-congestion-algorithm": "", 
    "peer-id-ttl-hours": 6, 
    "peer-limit-global": 3000, 
    "peer-limit-per-torrent": 500, 
    "peer-port": 56451, 
    "peer-port-random-high": 65535, 
    "peer-port-random-low": 49152, 
    "peer-port-random-on-start": true, 
    "peer-socket-tos": "default", 
    "pex-enabled": true, 
    "port-forwarding-enabled": false, 
    "preallocation": 1, 
    "prefetch-enabled": 1, 
    "queue-stalled-enabled": true, 
    "queue-stalled-minutes": 30, 
    "ratio-limit": 5, 
    "ratio-limit-enabled": true, 
    "rename-partial-files": true, 
    "rpc-authentication-required": true, 
    "rpc-bind-address": "0.0.0.0", 
    "rpc-enabled": true, 
   "rpc-password": "{b333454f6cec9cd102c6bfcf1105b71ad2c37213vdSoVwhK", 
    "rpc-host-whitelist": "*", 
    "rpc-host-whitelist-enabled": true, 
    "rpc-port": 9091, 
    "rpc-url": "/transmission/", 
    "rpc-username": "box", 
    "rpc-whitelist": "*", 
    "rpc-whitelist-enabled": true, 
    "scrape-paused-torrents-enabled": true, 
    "script-torrent-done-enabled": false, 
    "script-torrent-done-filename": "", 
    "seed-queue-enabled": false, 
    "seed-queue-size": 10, 
    "speed-limit-down": 100, 
    "speed-limit-down-enabled": false, 
    "speed-limit-up": 100, 
    "speed-limit-up-enabled": false, 
    "start-added-torrents": true, 
    "trash-original-torrent-files": false, 
    "umask": 18, 
    "upload-limit": 100, 
    "upload-limit-enabled": 0, 
    "upload-slots-per-torrent": 14, 
    "utp-enabled": true
}
```

**Comment by mikedld** [comment]
Your settinsg.json file looks okay. Since you have authentication enabled, you shouldn't receive this HTTP error. Make sure the settings you're showing are in fact those that daemon is using (did you edit the correct file? did you stop the daemon before editing the file?)

**Comment by Dustee** [comment]
Hi, i'm facing a similar problem on 2.92-2+deb9u1 (Raspbian stretch).

transmission-remote on the same host works fine, but trying to connect from a different computer results in: 

> 403: Forbidden
> Unauthorized IP Address.

Here are the relevant parts from settings.json

`"rpc-authentication-required": true,
"rpc-host-whitelist": "*",
"rpc-host-whitelist-enabled": true,
"rpc-whitelist": "127.0.0.1,192.168.0.*",
"rpc-whitelist-enabled": true,`

**Comment by viggy96** [comment]
@mikedld, the file shown is the `/etc/transmission-daemon/settings.json` file. That's the correct file, isn't it? 
Transmission is running on Ubuntu Server 16.04.3 LTS.

**Comment by mikedld** [comment]
@viggy96 This answers (well, tries to answer) only one of my two questions. I can't say whether the file is correct or not as I'm not using Ubuntu and don't have access to your system, but the package version you mentioned installs "/etc/transmission-daemon/settings.json" as a symlink to "/var/lib/transmission-daemon/.config/transmission-daemon/settings.json", just for your convenience, and if it's not a symlink then you're editing the wrong file.

@Dustee It can't be "similar problem" if the error is completely different. Debian package installs the very same link though, so make sure you're editing the correct file as well.

All in all, GitHub is not the place for support questions. I'm not closing this only because there is still a tiny room for concern, but I tested the changes myself and they're working fine on my end.

**Comment by lnicola** [comment]
I also had this issue, but I noticed a `transmission is undefined` error in the browser console, which led me down the wrong path. I'm writing this in case anyone else runs into this.

**Comment by Dustee** [comment]
@mikedld It was user error in my case, probably the file not being a symlink as you suggested (i did a reinstall).
Apologies for abusing the issue tracker.

**Comment by viggy96** [comment]
@mikedld, on my install '/var/lib/transmission-daemon/.config/transmission-daemon/settings.json' is a symlink to '/etc/transmission-daemon/settings.json'. Even after editing the JSON file to the above, it doesn't work. I made sure to stop the daemon before editing, and start it after saving the file.

**Comment by mikedld** [comment]
@viggy96 What and how exactly "doesn't work"? Are you sure there's only a single instance of transmission-daemon running on the system? If this (presumably) single instance is running with `-g` option passed, does the path following it corresponds to the location of settings.json file? What user is the daemon running as? Where's the daemon located and where are you trying to access it from (network-wise)? What URL are you using to access the daemon (e.g. are you using an IP address or a hostname)? Does the web UI (if you're using the web browser) load at all (at least the toolbar, not the torrents list) or even ask you for a password (given that you have authentication enabled)? What if you try another web browser or another machine to access it? Does it work if you try to access the daemon from the host it's running on (with either web browser or transmission-remote)? Did you consider to update to 2.92 (I presume patched version is already accessible at least in some PPA)?

**Comment by viggy96** [comment]
@mikedld By "doesn't work", I'm referring to the remote control functionality. I am unable to connect to the remote web ui, or use any other remote control application. Transmission itself works, but I can't control it except by ssh-ing into the machine its running on with transmission-remote. 

I have not tried version 2.92. I shall try that now.

**Comment by viggy96** [comment]
@mikedld Just tried version 2.92. The remote functionality now works as expected. I guess the Ubuntu PPA version has that bug (version 2.84). 

Thanks

**Comment by mikedld** [comment]
Glad it worked. Probably a good idea to report to Ubuntu about that ;)

**Comment by Nat0ne** [comment]
I just added my dns to the "rpc-host-whitelist" field and it worked.

**Comment by sanglyb** [comment]
> I just added my dns to the "rpc-host-whitelist" field and it worked.
Great, worked for me too.

**Comment by sanglyb** [comment]
> I just added my dns to the "rpc-host-whitelist" field and it worked.

Great, worked for me too.

**Comment by jokester** [comment]
Thanks to hint in https://github.com/transmission/transmission/issues/476#issuecomment-379410324 . My transmission daemon (behind reverse proxy) was hosted at `https://trans.example.com/transmission/web/`, so setting ` "rpc-host-whitelist": "trans.example.com"` did the trick.

**Comment by jvt** [comment]
@jokester's solution worked well for me.

**Comment by toloveru** [comment]
> 
> 
> I just added my dns to the "rpc-host-whitelist" field and it worked.

Incredible how they have so many checks and valves just to make the thing work. Thank you for mentioning this, it worked for me as well (a local DNS is maintaining local hostnames here).

Transmission really needs an option to disable all these checks and valves and make it rely on system security like iptables altogether.

**Comment by lnicola** [comment]
@toloveru DNS rebinding allows web sites to connect to services on your local network. You can't really block them with iptables.

**Comment by toloveru** [comment]
> 
> 
> @toloveru DNS rebinding allows web sites to connect to services on your local network. You can't really block them with iptables.

It so happens that I control and trust all the hosts on this network, so DNS rebind attacks aren't a problem that I can't deal with. I'm sure that I'm not the only one who's having such a scenario in which system security would be preferred over application security.

If anything, DNS rebinding isn't even my main issue, whitelisting is too. I whitelisted every IP with wildcards because I choose to rely on the iptables security of the server's local network and the 3 VPN servers that it will be connected to. If I launch a service, I do it knowingly of it being accessible on all interfaces unless configured otherwise. Transmission really is an oddball in this regard.

**Comment by lnicola** [comment]
> It so happens that I control and trust all the hosts on this network, so DNS rebind attacks aren't a problem that I can't deal with. [...] Same thing with whitelisting. I whitelisted every IP with wildcards because I choose to rely on the iptables security of the server's local network and the 3 VPN servers that it will be connected to.

I'm not sure I follow. DNS rebinding originates from outside your network, but is used to access hosts from LAN. If you can control Transmission from your computer, a random website will be able to do the same, using your browser. It won't connect to Transmission directly.

To protect against this you'd need to run a DNS resolver that filters out such responses.

**Comment by toloveru** [comment]
> 
> 
> > It so happens that I control and trust all the hosts on this network, so DNS rebind attacks aren't a problem that I can't deal with. [...] Same thing with whitelisting. I whitelisted every IP with wildcards because I choose to rely on the iptables security of the server's local network and the 3 VPN servers that it will be connected to.
> 
> I'm not sure I follow. DNS rebinding originates from outside your network, but is used to access hosts from LAN. If you can control Transmission from your computer, a random website will be able to do the same, using your browser. It won't connect to Transmission directly.
> 
> To protect against this you'd need to run a DNS resolver that filters out such responses.

My DNS server resides inside my network (I maintain my own DNS), so rebind attacks are limited to only within there, except for the DNS server itself which can be set to listen only to services on 53/udp that I set it to trust.

DNS rebinding works by allocating a rogue DNS server and somehow getting clients to interface with it. Which would require 1) someone to allocate the resources to make a DNS, and 2) for that someone to infect my clients so that they use that as a resolver. I would quickly notice this as the primary purpose of my local DNS is private zones, which if frequently use and aren't supported by any external resolvers. This inability to resolve local zones is a pretty obvious red flag.

Simply put, if someone is using a FQDN of any kind to resolve their Transmission server, I'd be hard-pressed to believe that they are not a system administrator of some kind. It is safe to assume that such system administrators are unlikely to catch malware like this, let alone not notice it.

As for your edit, yes my DNS resolver is local and because its purpose is easy host maintenance, all my hosts are using it.

**Comment by lnicola** [comment]
> DNS rebinding works by allocating a rogue DNS server and somehow getting clients to interface with it. Which would require 1) someone to allocate the resources to make a DNS, and 2) for that someone to infect my clients so that they use that as a resolver.

Um, no? Say I'm running `mycoolblog.org`. You navigate to my blog to read some article which has a bunch of JavaScript loaded. Since that's my site, I control its DNS server, and I can make `static.mycoolblog.org` sometimes resolve to `192.168.1.100`, which happens to be your Transmission instance. You have your own DNS resolver, but it won't know anything about `mycoolblog.org`'s subdomains, so it will still have to ask the server I control.

> 1) someone to allocate the resources to make a DNS

That is, anyone running a web site.

> 2) for that someone to infect my clients so that they use that as a resolver

No. Your resolver still needs to ask Google what `maps.google.com` is, just as it needs to ask Facebook about `static.xx.fbcdn.net` when you open `facebook.com`. It happens on every web page you load.

> Simply put, if someone is using a FQDN of any kind to resolve their Transmission server, I'd be hard-pressed to believe that they are not a system administrator of some kind.

Transmission's FQDN doesn't matter here. We're talking about `static.mycoolblog.org` pointing to your LAN IP, not about someone making `trasmission.toloveru` resolve to a random IP that I'm controlling.

> As for your edit, yes my DNS resolver is local and because its purpose is easy host maintenance, all my hosts are using it.

Sometimes this stuff happens: https://news.ycombinator.com/item?id=19170671.

**Comment by toloveru** [comment]
I'm currently running a DNS rebind attack against my network. My DNS resolver is refusing all the queries as REFUSED unexpected RCODE.

**Comment by toloveru** [comment]
Please don't get me wrong, I won't state that I'm familiar with DNS rebind attacks. These statements very much prove that I'm not. However, the fix to all of it in my scenario at least seemed to be just putting the external DNS resolvers in the forwarders{} section for BIND and calling it a day. Is my case really an edge case? I mean I've got both BIND and NoScript (latter in most cases, not all) going for me. Seems pretty solid, despite the vulnerabilities of DNS and UDP alike.

That being said, my primary reason for commenting here was to thank the person who posted that DNS rebind option earlier. I probably would've uninstalled the Transmission daemon on that host if it weren't for that, as its FQDN interfering out of DNS rebind protection would've been the last thing I'd have looked at. This is definitely something that I don't tend to see in other services like sshd, named, samba, or openvpn, just to name a few. Hence why Transmission's (re)configuration seemed a bit cumbersome to me, needlessly so. It's configured now though and all I could wish for is that it wouldn't require systemd unit modification (which I already knew of, I just changed it to my user) but most importantly, whitelisting every little thing when I'm not asking for it. That's been a main concern of mine every time I deployed Transmission in the last few years (which fortunately only happened only a few times in that time span).

**Comment by lnicola** [comment]
> However, the fix to all of it in my scenario at least seemed to be just putting the external DNS resolvers in the forwarders{} section for BIND and calling it a day.

I'm not sure that actually protects you against DNS rebinding, or how it could. It's a pretty subtle (but mind-blowing) attack, and running your own resolver won't help.

> I mean I've got both BIND and NoScript (latter in most cases, not all) going for me. Seems pretty solid, despite the vulnerabilities of DNS and UDP alike.

You might be assuming that someone who installs Transmission and wants to control it from outside of their network (your FQDN remark, not that this is relevant to DNS rebinding) has the same set up as you. I certainly don't.

> That being said, my primary reason for commenting here was to thank the person who posted that DNS rebind option earlier.

Yeah, we're probably spamming a lot of people with this conversation. I posted above because the error I got wasn't making it obvious what was wrong.

> This is definitely something that I don't tend to see in other services like sshd, named, samba, or openvpn, just to name a few.

Transmission talks HTTP, which makes it an easy target. Other services that do the same could be vulnerable to the same attack.

> It's configured now though and all I could wish for is that it wouldn't require systemd unit modification (which I already knew of, I just changed it to my user)

You might know that, but you can override (`systemctl edit`) the user instead of changing the packaged unit. That works better on updates.

Also, I don't think it's necessary to change the user. Add yourself to the `transmission` group and set `umask` to 3 or 7 in `settings.json`. It will save the files with a mask of `770`.

**Comment by toloveru** [comment]
>> However, the fix to all of it in my scenario at least seemed to be just putting the external DNS resolvers in the forwarders{} section for BIND and calling it a day.

> I'm not sure that actually protects you against DNS rebinding, or how it could. It's a pretty subtle (but mind-blowing) attack, and running your own resolver won't help.
I'd like to point out that I did successfully ran a DNS rebind attack against my network with no results stating vulnerability. If in doubt, I'd appreciate your own site as an input and I shall whitelist it in NoScript and run it directly on one of my hosts.

> You might be assuming that someone who installs Transmission and wants to control it from outside of their network (your FQDN remark, not that this is relevant to DNS rebinding) has the same set up as you. I certainly don't.
As stated before, I'd appreciate your attacker server and your levels of potential attack into my network. Keep in mind that in this attack I'll be running my regular security levels and won't allow JavaScript.

> Yeah, we're probably spamming a lot of people with this conversation. I posted above because the error I got wasn't making it obvious what was wrong.
We might take this to PM. I'm available at github.transmission.476@nixmagic.com.

> You might know that, but you can override (systemctl edit) the user instead of changing the packaged unit. That works better on updates.
I'll be sure to take that into account on the next update.

> Also, I don't think it's necessary to change the user. Add yourself to the transmission group and set umask to 3 or 7 in settings.json. It will save the files with a mask of 770.
I'm downloading directly to that file server's user directory. Using group control in that node seems like a needless abstraction. The container is an unprivileged user on the host and the Transmission node is an equally restricted user. All it has access to is a home directory, which is frequently backed up. Even ransomware (which good luck affecting this setup with) doesn't affect this.

Maybe we should indeed take this (IMO) dick measuring fest elsewhere. I'm here to thank someone for mentioning an option, that's all. If you want to taint a thread because of that, go ahead.

**Comment by rogergithubbing** [comment]
In my case I fixed it using the -t option to enable authentication; I was already using -u and -v to set the username and password for rpc access...
