### ISSUE TITLE
Make the foreground color in dark mode less taxing on the eyes

### ISSUE THREAD

**Issue by MechMK1** [transmission/transmission#4785]
### What is the issue?

Currently, the foreground color for the UI is pure white (`#fff`), but that is actually unpleasant to look at. I would suggest using a more muted foreground color (e.g. `#d9d9d9`). I've attached screenshots below on what either of these would look like.

With the old white text:

![Screenshot with High Contrast](https://user-images.githubusercontent.com/979843/217966004-2c172cd5-2449-42b1-a745-d7f358348d3a.png)

![Screenshot with Muted Contrast](https://user-images.githubusercontent.com/979843/217967186-fde384e6-7841-47ad-84ac-0f117a590d68.png)

----

With the reduction of brightness would also come a loss of contrast, which could negatively impact readability for vision-impaired users. However, I would say too high contrast, as it is now, *also* negatively impacts readability.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.0

**Comment by Pentaphon** [comment]
No offense but in my opinion, you went too far on the muted white and now it makes the text look too faded and you acknowledged that in the comment about loss of contrast. It already looked fine to me but if you want it to not be pure white, I'd dial down the white only a tiny bit next time. Perhaps you should provide more screenshots of other different muted white values and maybe you can convince the team to go with some other value that strikes a better balance, if any.

**Comment by ckerr** [comment]
When doing an A/B test of the two screenshots by opening them in separate tabs, to me the `#d9d9d9` looks a little better. If @MechMK1 made a PR to change this in web/assets/transmission-app.css I'd be inclined to use it.

> You went too far on the muted white and now it makes the text look too faded

I freely admit I don't have the most critical eye when it comes to UI changes, but I'll be honest, to me `#fff` and `#d9d9d9` look _real_ similar in those two snapshots. 

So now we have two (three?) opinions on what this color should be, in a very narrow range. Anyone know of any objective measure we can use to know which is "right"? https://webaim.org/resources/contrastchecker/ is happy with both `#fff` and `#d9d9d9`.

**Comment by Pentaphon** [comment]
> Anyone know of any objective measure we can use to know which is "right"? https://webaim.org/resources/contrastchecker/ is happy with both `#fff` and `#d9d9d9`.

It's going to be happy with either of them but obviously #fff  will have the higher value no matter what since it is pure white. If we are going with what is "right" then we would go with something in between #fff and #d9d9d9 since that would produce a higher value than #d9d9d9, which I personally think looks too muted, and it would still not be "unpleasantly bright" as pure white. 

I think @MechMK1 should do some more a/b testing, present more options to the person in charge of the PR and make a case for it, so there's more chance of him getting what he wants.

**Comment by ckerr** [comment]
@Pentaphon  what value do you suggest?

**Comment by Pentaphon** [comment]
> @Pentaphon what value do you suggest?

I'm fine with the way it currently is.

**Comment by GaryElshaw** [comment]
Agreed. The criticism of the whiteness of the text and icons of the web interface might be valid, but agree with the comment that was made, it currently excels accessibility-wise and should remain as is unless something between those two values is pr-ed. Come to think of it, just turning down the monitor brightness would probably be just as effective :-)

**Comment by ckerr** [comment]
`#ececec` is halfway between `#d9d9d9`  and `#fff`. What do you three think of using that?

**Comment by GaryElshaw** [comment]
I have a really good monitor, and at that scale, _i think it might be better?_

**Comment by Pentaphon** [comment]
> `#ececec` is halfway between `#d9d9d9` and `#ffffff`. What do you three think of using that?

Probably works just fine, but it's hard to definitively say until somebody shows a nice color spectrum of different example texts in the current webUI and I think @MechMK1 should work on that and collect a consensus from the community since this matters the most to his eyes. I'll be happy to any examples people show off a good look and give an honest opinion about what foreground color looks best.

**Comment by ckerr** [comment]
Related #4303

**Comment by MechMK1** [comment]
@Pentaphon I'm unsure if there is anything I can do to gauge consensus, other than a poll.

Judging solely based on contrast, #ffffff is the best choice, but I personally consider it too high contrast.

In terms of "dark themes" in general, GitHub also uses a slightly muted white, and so do many other sites and apps, which employ a dark mode. Pure white is generally not used in other applications.

So in my opinion, "any muted white" would work for me, and likely for most users. I would like to avoid a bikeshedding, situation, with 10 people arguing over which specific shade of light gray to use. #d9d9d9 was really just chosen through trial and error until I found a shade of gray that *felt* okay. So if anyone has any strong desire towards any particular shade of light gray, that's fine by me.

What I think would makd more sense would be to establish consensus if there should be any change at all, as in "light gray" or "pure white", and not worry about the particular shade yet.

**Comment by Pentaphon** [comment]
> @Pentaphon I'm unsure if there is anything I can do to gauge consensus, other than a poll.

I think you should go for it. https://github.com/transmission/transmission/discussions is where you can create one. 

> Judging solely based on contrast, #ffffff is the best choice, but I personally consider it too high contrast.

You're probably on to something there. 

> In terms of "dark themes" in general, GitHub also uses a slightly muted white, and so do many other sites and apps, which employ a dark mode. Pure white is generally not used in other applications.

Then perhaps we should use what Github users as those people are professionals. 

> So in my opinion, "any muted white" would work for me, and likely for most users. I would like to avoid a bikeshedding, situation, with 10 people arguing over which specific shade of light gray to use. #d9d9d9 was really just chosen through trial and error until I found a shade of gray that _felt_ okay. 

In that case, I disagree with the change because it looks too muted to my eyes. 

>So if anyone has any strong desire towards any particular shade of light gray, that's fine by me.

Ok, sounds like we agree again. 

> What I think would makd more sense would be to establish consensus if there should be any change at all, as in "light gray" or "pure white", and not worry about the particular shade yet.

Then sure, start with a 2 part poll. 

If you want to get a project to make a change in the UI, you gotta do the legwork to convince them that the change is worthwhile.

**Comment by ckerr** [comment]
At least on my desktop, GH dark mode is

`#f0f6fc (--color-fg-default)` for the bright stuff and
`#8b949e (--color-fg-muted)` for the secondary stuff.
