### ISSUE TITLE
file parts missing after download.

### ISSUE THREAD

**Issue by Hardcore-fs** [transmission/transmission#4837]
### What is the issue?

I have seen feeds get to  98.xxx  , stop wait then proceed into 99.xxxx

Which is normal behavior.
however when /if I stop the download process by needing to quit the app, next time it is showing only 95%

Why has a large chunk of the file been dumped? potentially taking the file from readable to useless.

it might get to 99.99%, can be viewed using a video program, but if it is at 95%, there is visible corruption.

Chunk size does not account for all the missing %.
here is a quick DL of a random file.

Really the counter should only display exactly what you have & is safe.
![should_have](https://user-images.githubusercontent.com/1309004/218280794-b4053250-66aa-46fd-bb55-c1e46f894f7e.png)
![some gone](https://user-images.githubusercontent.com/1309004/218280841-c1f3043f-371a-4e7e-add0-2783be45d18e.png)
![restart app](https://user-images.githubusercontent.com/1309004/218280932-832c61a1-19c4-46bc-ad92-2714350f1db7.png)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ckerr** [comment]
I'm about 90% sure this is another symptom of the issues fixed by #4879, #4880, and #4890.

but there's still 10% unsure.... @Hardcore-fs I'm going to close this bug but obviously missing parts are an important issue. So  if this still happens for you either in the nightly builds (if you want to test now) or in `4.0.1` (scheduled for next Wednesday) please do file a new ticket and LMK. Thank you!
