### ISSUE TITLE
Don't include build directory in debug/error/info messages

### ISSUE THREAD

**Issue by fjaell** [transmission/transmission#4947]
### What is the issue?

Currently every debug/error/info log-message includes the build directory of transmission. This is annoying because usually it doesn't exist at run time. Here's as an example the start message of transmission-daemon:

[2023-02-19 11:17:53.553] inf session.cc:646 Transmission version 4.0.0 (280ace12f8) starting (/dat/temp/pkgmk/transmission/src/transmission-4.0.0/libtransmission/session.cc:646)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0

**Comment by Coeur** [comment]
That path is coming from:
https://github.com/transmission/transmission/blob/c5b1df0daa13ab36b09fd7d9df25ab7f5eb7f6f2/libtransmission/log.h#L102

Not sure how to ideally strip only the build directory out of `__FILE__`. But since our file hierarchy in `libtransmission` is flat, we could maybe simply keep the filename and its parent directory name.

**Comment by ckerr** [comment]
Yeah the place to make the change would be in `tr_logAddMessage()`
