### ISSUE TITLE
Downloads not completing/local data going missing?

### ISSUE THREAD

**Issue by xtamtamx** [transmission/transmission#4965]
### What is the issue?

Few issues:

1. Downloads start and act as normal but then eventually speeds completely drop until I pause/resume.
2. Then I get errors saying that local data is missing, I verify local data and then error clears and download will continue.
3. Random error: "Tracker returned warning: Steve Jobs has cursed this open tracker with ligma, press F to pay respects."
4. Local data going missing/downloaded percentage dropping over time; just like it says, I watched a torrent drop from 98% complete to 92% over 15 minutes.

Error image:
<img width="1027" alt="IMG_5169" src="https://user-images.githubusercontent.com/30088598/220170482-0261048a-d171-4504-9fbf-1fc1814d0c6a.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by ckerr** [comment]
@xtamtamx thanks for reporting this.

> "Tracker returned warning: Steve Jobs has cursed this open tracker with ligma, press F to pay respects."

That text isn't coming from Transmission. Sounds like some tracker somewhere has a childish sense of humor.

> Local data going missing/downloaded percentage dropping over time; just like it says, I watched a torrent drop from 98% complete to 92% over 15 minutes.

This sounds like the same bug that's fixed here:

>>  Fixed `4.0.0` bug that caused some torrents to have poor speed and some of their checksums to be incorrectly marked as failed. ([#4879](https://github.com/transmission/transmission/pull/4879), [#4880](https://github.com/transmission/transmission/pull/4880), [#4890](https://github.com/transmission/transmission/pull/4890))

...so I'm going to close this one as a duplicate.

However since losing (or at least, the app *thinking* it's losing) data is a pretty important issue so if you still get this in `4.0.1` (scheduled for Wednesday) @xtamtamx please do open a new bug. :bow:

**Comment by GaryElshaw** [comment]
https://github.com/transmission/transmission/issues/4967#issuecomment-1437784926
