### ISSUE TITLE
Transmission is showing a list of random files from WikiLeaks

### ISSUE THREAD

**Issue by mrded** [transmission/transmission#4967]
### What is the issue?

I've updated my Transmission to 4.0.0 (280ace12f8), and it starts showing a list of random files from WikiLeaks, every time I restart it.

I'm using macOS 13.2.1 (22D68). Do you have any idea where it's coming from? I've removed it once, but it appeared again. 

![image](https://user-images.githubusercontent.com/347098/220178856-90cdd85b-7e14-479f-83c5-a5fb037aed51.png)
![image](https://user-images.githubusercontent.com/347098/220178889-c19da26a-ce5c-4473-9548-37f7893f96d9.png)
![image](https://user-images.githubusercontent.com/347098/220178924-ed5bcf80-6d32-4ae5-a0d8-77d4869590ec.png)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by mrded** [comment]
Rolling back to 3.00 (f4489c982e) version doesn't have that problem. Seems like it's embedded into the transmission build.

**Comment by mikedld** [comment]
Watch directory?..

**Comment by mrded** [comment]
@mikedld I didn't set it myself. And I have never downloaded any WikiLeaks files. How do I check?

**Comment by mrded** [comment]
I suspect watch directory would be at "Auto add" setting, it's off. Also has some weird folder which I do not recognise and doesn't exist on my Mac.

![image](https://user-images.githubusercontent.com/347098/220185095-597897b2-6f48-4a24-81a5-1a4d8e094bbb.png)

**Comment by mikedld** [comment]
I believe I saw @ckerr mentioning session loading on Mac has changed between 3.00 and 4.0.0, the latter using common mechanism while the former using its own approach somehow.

**Comment by ckerr** [comment]
> Seems like it's embedded into the transmission build. 

FWIW the binary builds were all made by project maintainers and to the best of my knowledge there's nothing embedded into the builds. You're the only person to report wikileaks content so my Occam's razor guess is there's some issue with your system. :dizzy: 

> Do you have any idea where it's coming from? I've removed it once, but it appeared again.

That's even weirder, since you say auto-add is disabled (and your screenshot supports that).

> "cerac-cenep-colombia-conflict-videos-2009"

According to Google that is a foldername from a wikileaks file, too.

...this is just super weird.  TBH this is one of the weirdest bug reports I've ever gotten.

(Achievement unlocked, @mrded! :smile_cat:)

Some suggestions:

- Look at the entire path to that auto-add folder and ~~double~~ triple-check that it doesn't exist. See if any of the parent folders exist.

- Change that auto-add setting to something else, existing or not, so that Transmission doesn't look at it for torrents anymore.

- Try starting 3.00 one more time for comparison: does the auto-add folder look the same there?

- From your home directory there should be the subpath `Library/Application Support/Transmission/torrents` which is just a directory full of torrent files. That's where 4.0.0 loads torrents from. (side note: there is a sibling folder named `resume` that holds the state information for each of those torrents). Look there to see if any of the info hashes match the ones you don't want. Remove any that you don't want.

- You might even consider getting a genius to look at your system to make sure that it's secure. I don't think this is a Transmission issue but it's _possible_ that 4.0.0 is stumbling across some pre-existing files by virtue of 4.0.0 using a different directory to store its config files. For example if someone has `transmission-daemon` installed on your system and is using it to share wikileaks files. :dizzy:  This item sounds kind of tinfoil-hat territory but honestly I'm not sure what the plausible explanation might be.

**Comment by ckerr** [comment]
@mrded and whatever happens please do report back in. I'm very curious what could be causing this one :eyes:

**Comment by GaryElshaw** [comment]
Last night in properties i did see a tracker include a line with something to do with 4chan. I'll post if i see it again.

**Comment by ckerr** [comment]
@GaryElshaw that seems really off-topic and I'm tempted to hide the comment on that basis, but I'm also kind of sleep-deprived and  not really understanding your point so it _might just be me_ :sleepy: What does 4chan have to do with this ticket?

**Comment by ckerr** [comment]
@GaryElshaw that seems really off-topic and I'm tempted to hide the comment on that basis, but I'm also kind of sleep-deprived and so I might just be missing your point. :sleepy:  What does 4chan have to do with this ticket?

**Comment by GaryElshaw** [comment]
Completely random messaging that appears to be coming from some trackers right now.

**Comment by GaryElshaw** [comment]
The tracker is http://opentracker.i2p.rocks:6969/announce.

![Untitled](https://user-images.githubusercontent.com/69029666/220234638-d3a9d6d1-6733-4022-8d83-41ba21b7cb73.png)

**Comment by mrded** [comment]
I tried installing v4 on my spare old MacBook, and I don't see any WikiLeaks files there. Seems like a local problem, let me investigate.

**Comment by mrded** [comment]
@ckerr 

> Before changing anything, try starting 3.00 one more time for comparison: does the auto-add folder look the same there?
> Look at the entire path to that auto-add folder and double triple-check that it doesn't exist. Not just it but also any of the parent folders that you don't recognize.

Yes, it does. However, the actual folder doesn't exist.

> Change that auto-add setting to something else, existing or not, so that Transmission doesn't look at it for torrents anymore.

I tried changing the watch folder to something else, when I run v4 - WikiLeaks files are still added :/ 

> From your home directory there should be the subpath `Library/Application Support/Transmission/torrents` which is just a directory full of torrent files. That's where 4.0.0 loads torrents from. (side note: there is a sibling folder named resume that holds the state information for each of those torrents). Look there to see if any of the info hashes match the ones you don't want. Remove any that you don't want.

Aha! I see a lot of torrent files from WikiLeaks. I checked my time capsule and looks like I always had those torrents there, since the earliest backup.

Removing the files, solved the problem. 

There are few unclear things here to me:
1. How I got WikiLeaks torrents to my computer in a first place
2. Why v3 was ignoring `/Transmission/torrents` and v4 picked it up

Anyway, it doesn't look like a Transmission problem, I'm happy to close the issue. Thanks for support, everyone!
