### ISSUE TITLE
after 4.0.1 upgrade, some torrents think they are magnets and try to re-fetch metainfo

### ISSUE THREAD

**Issue by bartekuk** [transmission/transmission#5007]
### What is the issue?

In two of my transmission seedboxes ~50% of seeding torrents started redownloading.

Notably some which are broken in one server are not necessarily broken in the other. 

It seems like some magnet downloads resumed downloading their torrent payload while the downloaded file assets remain intact in place. The .torrent files corresponding to hash are also present in torrent data folder of the deamon

Deamon seems to ignore attempts to verify torrents (as they are in downloading state I guess).

The affected torrents report unknown  size in Transmision Remote GUI v.5.18.0 despite having full list of files presenting and none of them seems to resume downloading (which may be lack of seeds but feels suspicious)

I am using https://hub.docker.com/r/linuxserver/transmission

Update: I confirmed that one of the previously seeded torrents which is now stalled in the downloading state would download in different 4.0.1 tranmission deamon (via magnet link)  So it seems like I have a large number of previously seeding torrents in broken state.  Any clues or workarounds much appreciated. I am happy to help debugging this issue. 

Update2: It seems that the stalled .torrent files uploaded to different 4.0.1 don't download either and also report size unknown but they would download with version 3 (bb6b5a06)

### Workaround

In order to restore seeding torrents I downgraded to 4.0.0 and ran verification on all affected torrents

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1 e1c6e1b

**Comment by bartekuk** [comment]
It seems that the stalled .torrent files uploaded to different 4.0.1 don't download and report size unknown but they would download with version 3 (bb6b5a)

**Comment by bartekuk** [comment]
I am able to reproduce the issue switching between linuxserver/transmission:4.0.0 and linuxserver/transmission:4.0.1 docker images

**Comment by stefantalpalaru** [comment]
I see the same problem when upgrading to 4.0.1 - 6 out of 105 torrent no longer see their data and refuse to verify it. These are very old torrents, probably added from magnet links on 2.x, on 32-bit ARM.

A dozen other completed torrents felt the need to verify all their data at start.

**Comment by bartekuk** [comment]
Yes I can try, first of you need a file that is affected I will add this file to this ticket, it was rewritten last night when 4am my server automatically upgraded from 4.0.0 to 4.0.1 

```
  File: 13d615252282fd0a709c6df1256a6f06e533e9cb.magnet
  Size: 3564            Blocks: 8          IO Block: 4096   regular file
Device: 0,53    Inode: 12141593    Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/ polska2)   Gid: ( 1000/ polska2)
Access: 2023-02-23 04:00:19.650335796 -0500
Modify: 2023-02-23 04:00:18.937355056 -0500
Change: 2023-02-23 04:00:18.937355056 -0500
 Birth: 2023-02-23 04:00:18.937355056 -0500
```

When you add this file to 4.0.0 or last version of 3 the web info frontend says 

```
Details
Size:
50 MB (0 pieces @ None)
```
And the torrent will download OK, if you then upgrade to 4.0.1 the web info frontend says

```
Details
Size:
None
```
And the torrent will not download. 

@stefantalpalaru after downgrading to 4.0.0 I was able to restore seeding torrents by pressing verify

**Comment by bartekuk** [comment]
@ckerr please see previous comment for reproduction steps

**Comment by Formicacid** [comment]
Same here. On installation of 4.01, 175 of 580 magnetized transfers are "searching for torrent megadata." The files are in place but I can't verify local data. Not sure what they have in common. Approximately 500 were downloaded at roughly the same time in December 2018 over three days. The 175 stalled torrents are from the same period. In some cases, all torrents by the same musical group are stalled.

As some of the torrents find seeders, they are being restored, with up-to-date seeding ratios and seeding start dates intact.

**Comment by maxz** [comment]
I had the same or a very similar issue. All my torrents were finished and just seeding in 4.0.
When starting 4.1 many (all that were not paused or finished as far as I can tell) began fetching their metadata again and verifying all files. I'm not sure why this happened when moving from 4.0 to 4.1 and the verification is still ongoing.

**Comment by ckerr** [comment]
Could someone take a look in Transmission's `torrents/` folder and report back whether they see files with the same infohash but a different suffix, e.g. `${infohash}.magnet` and `${infohash}.torrent`?

- on macOS you would look in `~/Library/Application Support/Tranmsission/torrents`
- on Windows you would look in `%USERPROFILE%\AppData\Local\Transmission\torrents` (I think)
- on Linux you could look in `~/.config/transmission/torrents`

**Comment by stefantalpalaru** [comment]
I have 5 of those:

```sh
$ for F in /var/lib/transmission/config/torrents/*.magnet; do if [[ -e "${F%.magnet}.torrent" ]]; then echo "${F}"; fi; done | wc -l
5
```

**Comment by ckerr** [comment]
@stefantalpalaru are those the same info-hashes of torrents that turned back into magnets?

**Comment by stefantalpalaru** [comment]
Yes, and all .magnet files are newly created, for torrents that appeared as empty at some point during upgrade/downgrade.

I went back to 4.0.0 to recover five out of six, and I had to go back to 3.00 to get the final one back. Upgrading to 4.0.1 after this still leaves me with a few showing up empty, so I'm sticking to 3.00 on that machine.

**Comment by ckerr** [comment]
@stefantalpalaru this is very promising. Are there any torrents that reverted to magnet that *don't* have two files?

**Comment by stefantalpalaru** [comment]
> Are there any torrents that reverted to magnet that don't have two files?

No.

**Comment by ckerr** [comment]
Cool. As soon as I get to a keyboard I should have a PR for you too test. Thanks for the helpful info @stefantalpalaru

**Comment by Formicacid** [comment]
Just noting that when a seeder does arrive to provide the metadata for the stalled magnetic torrents, Transmission doesn't download a new file. It just verifies the original data and begins to seed again.

**Comment by ckerr** [comment]
I've put up a PR at #5025 that should help.

When CI finishes, the builds should be downloadable from https://github.com/transmission/transmission/actions/runs/4259774782

**Comment by Formicacid** [comment]
In case this needs confirmation, I can confirm that all of the torrents affected were initially downloaded as magnetic torrents. That is, of the 175 torrents affected here, there are no regular torrents involved that now think they are magnets.

**Comment by bartekuk** [comment]
@ckerr I tested 4.0.1-dev 66b771ea3c CI fedora build on my previously "magnitised" torrents and see no improvement - the torrents remain in "magnetic" state, when I remove magnetised torrent (one I listed in previous comment) it becomes "magnetised" again

**Comment by ckerr** [comment]
@bartekuk can you clarify this:

> when I remove and add the magnetised torrent (one I listed in previous comment) it becomes "magnetised" again with corresponding .magnet file existing until metadata is drawn from elsewhere

When you remove and re-add them, how are you adding them? Are you re-adding as magnets or as torrent files?

**Comment by bartekuk** [comment]
> @bartekuk can you clarify this:
> 
> > when I remove and add the magnetised torrent (one I listed in previous comment) it becomes "magnetised" again with corresponding .magnet file existing until metadata is drawn from elsewhere
> 
> When you remove and re-add them, how are you adding them? Are you re-adding as magnets or as torrent files?

Torrents see 13.....patch file attached to one of my previous comments

**Comment by ckerr** [comment]
Sorry, I'm not understanding your answer. When you remove and re-add them, how are you adding them? Are you re-adding as magnets or as torrent files?

**Comment by bartekuk** [comment]
As torrents.

**Comment by ckerr** [comment]
> when I remove and add the magnetised torrent (one I listed in previous comment) it becomes "magnetised" again with corresponding .magnet file existing until metadata is drawn from elsewhere

@bartekuk ok so to be clear

1. you have the local data for that torrent
2. the torrent isn't loaded in transmission in either magnet or torrent form
3. you add the torrent file via the web ui to a transmission-daemon 4.0.1 session
4. it shows up in the UI as a magnet that lacks metainfo.

Is all that correct?

**Comment by Formicacid** [comment]
I know this was not directed at me, but the four points accurately represent what is happening on my end.

**Comment by ckerr** [comment]
Are all the torrents displaying this behavior torrents that just have a single file -- e.g. an iso or mkv rather than a folder with multiple files?

**Comment by Formicacid** [comment]
Virtually all magnetic torrents I am seeding are music torrents, so they almost all contain multiple files by default. However, one is a "fill" containing just one song.

**Comment by Formicacid** [comment]
I did check to see if the affected torrent files were all MP3s, but one of the affected torrents contains FLAC files.

**Comment by ckerr** [comment]
OK part of this is coming from 649fd4d0d2088a9c38078c9c135ef3d899a9bbae from #4840 which was to fix #4295.  (CC @Coeur)

Please give it another try with the CI builds @ https://github.com/transmission/transmission/actions/runs/4267090805

**Comment by bartekuk** [comment]
> > when I remove and add the magnetised torrent (one I listed in previous comment) it becomes "magnetised" again with corresponding .magnet file existing until metadata is drawn from elsewhere
> 
> @bartekuk ok so to be clear
> 
> 1. you have the local data for that torrent in the default download folder
> 2. the torrent isn't loaded in transmission in either magnet or torrent form
> 3. you add the torrent file via the web ui to a transmission-daemon 4.0.1 session
> 4. it shows up in the UI as a magnet that lacks metainfo.
> 
> Is all that correct?

Yes these steps, and with 4.0.0 the torrent behaves correct. I will try new build tomorrow. You will find the torrent in my first repro comment.

**Comment by mypupsrgr8** [comment]
I am pretty sure all was working fine for me when I upgraded to 4.0.0 a week or so ago, however, as soon as I installed 4.0.1 this evening all of my torrents seem to have lost track of the fact that the data files ever existed (for completed transfers or those that were partially completed).  I downgraded by reinstalling 4.0.0, and it seems like the status of previously downloaded items is still missing.  Is there a location I could go to with Time Machine backups to attempt to restore the state information in Transmission regarding downloads?

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/actions/runs/4267090805 has a potential fix that I'd like to get testing feedback on, for @mypupsrgr8, @bartekuk, @Formicacid, or anyone else who is reading this ticket because they're experiencing the problem

**Comment by maxz** [comment]
Ok, so I built it from source based on commit [69c3b12](https://github.com/transmission/transmission/commit/69c3b121184197da112bb1652f1e845c95b7de4b) and it mostly seems to work (no problems with magnet links), but there this is a problem with unrecognised progress.

In most cases it displays as 99% complete torrents where it was 100% before. In one case it was 89% and in three cases 0%. The majority of the torrents have been at 100% since I started the instance with this version. The 0% torrents went back to 100% when I verified them.
The 89% and the 99% ones did not. They remained at 89% or respectively 99%. For the 89% file the included text files are still readable fine although they are displayed at 0% in Transmission and I also can't detect anything wrong in the video although that displays as 89% complete.
When activating the 89% file after verifying it, it starts redownloading the "missing" parts from the swarm.
The 89% and 99% torrents were all from one particular source and all based on torrent files instead of magnet links.

I just finished verifying all those files yesterday in release 4.0.1 and they were at 100%.

After getting them all back to 100% (except for the 89% torrent) and restarting `transmission-daemon`, one new torrent was at 0% instead of 100% and went back to 100% after verifying. And except for the 89% torrent everything was at 100%, where it should be.

**Comment by bartekuk** [comment]
@ckerr I tried 4.0.1-dev ebe9955bff tranmsission-daemon with following results

1.  the torrent that would load fine in 4.0.0 loads fine again with ebe9955bff - it has its payload in place so it goes straight into seeding 
2. torrents which went "magnetic" with 4.0.1 upgrade became regular torrents and remain in downloading state 10 out of 22 in my case
3. I was able restore seeding state on every one of these by executing verification

The issue seem fixe but for those affected verify may be necessary

**Comment by Formicacid** [comment]
Worked for me! Magnetic torrents were rectified using the "Verify" option, which was now permitted. Thank you!

**Comment by mypupsrgr8** [comment]
Hello,

I tried to download both the binaries-macos-11 and binaries-macos-11-tarball  builds from the supplied link and was unable to get the application to launch from either.  I tried using the default Archive utility on macOS, Unarchiver, and unzip from the command line.  I get a message indicating that the app can’t be opened when I try to open it (even with Ctrl-click and selecting “Open” from the context menu), of in the case of having deomressed it with Unarchiver I get a message indicating the file is damaged.

I am running macOS Ventura 13.2.1.

Best Regards,

Ted

On Feb 25, 2023, at 12:03 AM, Charles Kerr ***@***.***> wrote:



https://github.com/transmission/transmission/actions/runs/4267090805 has a potential fix that I'd like to get testing feedback on, for @mypupsrgr8<https://github.com/mypupsrgr8>, @bartekuk<https://github.com/bartekuk>, @Formicacid<https://github.com/Formicacid>, or anyone else who is reading this ticket because they're experiencing the problem

**Comment by GaryElshaw** [comment]
Documentation was added [last week](https://github.com/transmission/transmission/pull/5135#event-8663263642)

**Comment by Coeur** [comment]
@mypupsrgr8 yes, once "binaries-macos-11" is unarchived, you need to go into its "Application" folder and run two extra commands:
```
chmod +x Transmission.app/Contents/MacOS/Transmission
xattr -rc Transmission.app
```
If that still doesn't work and you're on Apple Silicon, you can try to repair Rosetta:
https://github.com/transmission/transmission/blob/main/docs/Testing-Transmission.md

**Comment by mypupsrgr8** [comment]
Thanks for that info, however, after performing both of those commands the application refuses to launch.  There is no dialog box presented regarding the app being broken, however there are both “User” and “System” crash reports created at the time I attempt to launch it.

Here is an excerpt of the exception in one of the crash reports:

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x000000010e121000
Exception Codes:       0x0000000000000032, 0x000000010e121000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

I am running on macOS Ventura 13.2.1 on an Intel-based MacBook Pro (2018)

Best Regards,

Ted

On Mar 5, 2023, at 7:25 PM, Cœur ***@***.***> wrote:



@mypupsrgr8<https://github.com/mypupsrgr8> yes, once "binaries-macos-11" is unarchived, you need to go into its "Application" folder and run two extra commands:

chmod +x Transmission.app/Contents/MacOS/Transmission
xattr -rc Transmission.app


If that still doesn't work and you're on Apple Silicon, you can try to repair Rosetta:
https://github.com/transmission/transmission/blob/main/docs/Testing-Transmission.md

**Comment by Coeur** [comment]
@mypupsrgr8 maybe, on top of steps given (so you still have to run the two commands above), you may have to (one by one):
- try "binaries-macos-11-from-tarball" instead of binaries-macos-11
- go to "Confidentiality and Security" > Security > Authorise apps from App Store AND identified developers

If any of those steps was helpful, please let me know and I'll update the documentation accordingly.

**Comment by mypupsrgr8** [comment]
Hello,

I tried downloading the “binaries-macos-11-from-tarball” zip file and running the aforementioned 2 commands after unarchiving.  This produced the same results as occurred when executing the same 2 commands against the unarchived “binaries-macos-11” zip file.

I have also verified that “System Settings”->”Privacy & Security”->”Security”->”Allow applications downloaded from” is set to “App Store and identified developers”.

Best Regards,

Ted

On Mar 6, 2023, at 6:35 PM, Cœur ***@***.***> wrote:



@mypupsrgr8<https://github.com/mypupsrgr8> maybe, on top of steps given (so you still have to run the two commands above), you may have to (one by one):

  *   try "binaries-macos-11-from-tarball" instead of binaries-macos-11
  *   go to "Confidentiality and Security" > Security > Authorise apps from App Store AND identified developers

If any of those steps was helpful, please let me know and I'll update the documentation accordingly.

**Comment by Coeur** [comment]
Note that you don't need to run commands if you take a nightly build from https://build.transmissionbt.com/job/trunk-mac/.
The only reason to take a build from CI would be for an unmerged PR. And that PR needs to have been updated/rebased after March 3 (after #5126), otherwise some other issues were present in the past. May I know which open PR you're trying to test, to verify that it got updated after that date?

**Comment by garoto** [comment]
I guess I can confirm that upgrading from v4.0.1 to v4.0.2 fixed this issue with this (stopped) public torrent of mine which would show garbled stats and/or missing critical information. Forcing a recheck didn't work, nothing happened.

json diff in case it might be useful to someone:
```diff
--- "NoFace.stats.v401.json"	2023-03-24 18:51:09.000000000 -0300
+++ "NoFace.stats.v402.json"	2023-03-24 18:51:02.774087800 -0300
@@ -21,9 +21,9 @@
         "group": "",
         "hashString": "0cff3e1b956a02a38951b31ce5187b7b1df54ea9",
         "haveUnchecked": 0,
-        "haveValid": 0,
+        "haveValid": 95807595024,
         "honorsSessionLimits": true,
-        "id": 366,
+        "id": 1,
         "isFinished": false,
         "isPrivate": false,
         "labels": [],
@@ -34,23 +34,23 @@
         "peersConnected": 0,
         "peersGettingFromUs": 0,
         "peersSendingToUs": 0,
-        "pieceCount": 0,
-        "pieceSize": 0,
+        "pieceCount": 33428,
+        "pieceSize": 4194304,
         "rateDownload": 0,
         "rateUpload": 0,
         "recheckProgress": 0,
         "secondsDownloading": 20140,
-        "secondsSeeding": 111095,
+        "secondsSeeding": 116992,
         "seedRatioLimit": 2,
         "seedRatioMode": 0,
-        "sizeWhenDone": 0,
+        "sizeWhenDone": 95807595024,
         "source": "",
-        "startDate": 0,
-        "status": 0,
-        "totalSize": 0,
+        "startDate": 1679688765,
+        "status": 6,
+        "totalSize": 140204302864,
         "uploadLimit": 20480,
         "uploadLimited": false,
-        "uploadRatio": -2,
+        "uploadRatio": 14.0078,
         "uploadedEver": 1342053947429,
         "webseeds": [],
         "webseedsSendingToUs": 0
```
