### ISSUE TITLE
In the French localization, the size of the button horizontally, do as in all other localizations

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#5031]
### What is the issue?

<img width="640" alt="196159004-8bd3d40d-a267-4c06-ac8b-a69be83979cd" src="https://user-images.githubusercontent.com/62497891/221251389-44765579-56d7-4492-8ec1-d99afaee5655.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by Coeur** [comment]
In InfoActivityView.xib, the NSSegmentedControl fPiecesControl has a constraint that says it should be of equal width as the fPiecesView above. Not sure why it's not working.

**Comment by Coeur** [comment]
OK, when pausing the app, the NSSegmentedControl has the right size, as seen in blue highlight. So the issue is with its NSSegmentItem not taking the whole width of the control.
![Capture d’écran 2023-02-26 à 23 11 06](https://user-images.githubusercontent.com/839992/221419216-585038ae-c090-4725-b717-8766f99ae62e.png)
