### ISSUE TITLE
Rpc compatibility with old versions

### ISSUE THREAD

**Issue by SNBogdanov** [transmission/transmission#5047]
### What is the issue?

With new version 4.0 rpc command for free space is changed.  This broke old clients which were not updated to new version. Please restore compatibility.

### Which application of Transmission?

transmission-daemon

**Comment by ckerr** [comment]
@SNBogdanov could you be more specific about what broke? e.g. specifically which method and which parameters in that method?

- `download-dir-free-space` has been marked as deprecated but wasn't removed
- `free-space` got a new parameter but the old parameters are still there

If something _broke_ it wasn't intentional but I don't understand what's broken?

**Comment by SNBogdanov** [comment]
Sorry to mislead you in original post. Problem was incorrect default download directory. Method free-space returned success status and -1 in sizes.
