### ISSUE TITLE
Transmission doesn't ack Cancel with RejectRequest

### ISSUE THREAD

**Issue by jech** [transmission/transmission#511]
When a peer successfully negotiates the Fast request, it should acknowledge every Cancel with a RejectRequest — a Cancel gets exactly one reply, either Piece or RejectRequest.

It would appear that Transmission dosn't do that, which causes other clients to timeout waiting for the acknowledgement.

**Comment by anacrolix** [comment]
I can confirm, this breaks other clients that are waiting for their cancels to be rejected. This is very surprising behaviour, and I've only encountered it because I'm now relying on the correct behaviour. The fix would go here: https://github.com/transmission/transmission/blob/2977636d58d7a21189dfb9e78141570f9f31a469/libtransmission/peer-msgs.cc#L1736-L1758.

**Comment by anacrolix** [comment]
It needs something like:
```
else if (fext)
    {
        protocolSendReject(msgs, req);
    }
```

**Comment by anacrolix** [comment]
Thanks @ckerr and @jech .
