### ISSUE TITLE
Windows Security flags Transmission executable as infected Potentially Unwanted App (PUA)

### ISSUE THREAD

**Issue by tsobczynski** [transmission/transmission#5200]
![image](https://user-images.githubusercontent.com/87488032/224506436-19f8be98-82bd-4e7c-a50d-2b2417b8ca20.png)

Detected: PUA:Win32/Vigua.A
file: C:\Program Files\Transmission\transmission-qt.exe

This occurred with Transmission 4.0.1, i.e. https://github.com/transmission/transmission/releases/download/4.0.1/transmission-4.0.1-x64.msi

**Comment by mikedld** [comment]
This is a duplicate of #4548.

**Comment by tsobczynski** [comment]
This is NOT a duplicate, @mikedld, because in this case it is flagged for harboring "Vigua.A" virus. A random link on this virus:

https://www.2-spyware.com/remove-vigua-a-virus.html

**Comment by mikedld** [comment]
A false-positive then? Every release is being uploaded to VirusTotal, links are available at https://transmissionbt.com/download. We don't release a binary unless all the checks are green, and they were at the time of the release. Windows x64 package does indeed currently show up with failed check from Microsoft[^1] but I doubt a virus known since at least 2020 somehow went undetected on the initial scan. We're building the Windows release packages on Microsoft's own environment (Appveyor) and uploading them directly from there for signing, so if there's an issue somewhere in this chain then I'd say we would've known about it by now.

I'd give it a few days for them to sort it out. If there's an action to report a false-positive, please do so.

[^1]: https://www.virustotal.com/en/file/b34d815be8bf34653b158220d6be33b368973c6cd502303fad8c79a25ca0761e/analysis

**Comment by tsobczynski** [comment]
That's good info, @mikedld. I agree that under those conditions it is unlikely. I also checked the SHA256 of the installer I used against the value posted on the download page, and that matches. Unless someone managed to slip a malicious commit into the source tree, it's likely a false positive.
