### ISSUE TITLE
Linux - 4.0.1 does not recognize system theme correctly

### ISSUE THREAD

**Issue by a-lameira** [transmission/transmission#5224]
Version 4.0.1 does not recognize the installation environment theme (custom gtk theme), while version 3.00 did. The environment variable 'GTK_THEME=adw-gtk3-dark', that reads ~/.local/share/themes/ does not work. The environment variable 'GTK_THEME=Adwaita-dark', that reads /usr/share/themes/ works.

![Screenshot from 2023-03-14 12-17-02](https://user-images.githubusercontent.com/121145674/225050711-e10f915a-3a09-4ceb-8f42-c7a5158b459b.png)
Version 4.0.1 - System theme is incorrect (the system theme is dark)

![Screenshot from 2023-03-14 12-21-35](https://user-images.githubusercontent.com/121145674/225050884-8ef8d4a4-ee89-4bb6-8063-b2828b376065.png)
Version 3.00 - System theme is correct (gtk dark)

I did some testing, and moved the theme 'adw-gtk3-dark' to /usr/share/themes/. The environmet variable works perfectly with other programs, but not with Transmission. Certainly there is some kind of regression regarding gtk theming in version 4.0.1. Previous version (3.00) had perfect functionality in this area.

Using Debian Sid 6.1.15, Gnome 43.3, Wayland

**Comment by a-lameira** [comment]
Thenks for the reply. I understand what you said, but the application became disfuntional regarding theming. I think that at least some kind of Light/Dark theme automatic detection should be expected behaviour. Many Gtk4 applications are capable of recognizing if the system theme is Light or Dark. I don't think that users should be changing their system themes that are consistent between all the other programs because theming is not working right in transmission.

In [this article](https://blog.gtk.org/2021/08/23/gtk-4-4/) GTK4 devs state that the default expected themes are named 'Default', 'Default-dark', 'Default-hc' and 'Default-hc-dark'. Using 'GTK_THEME=Default-dark transmission-gtk' works with 4.0.1. I am not an expert in GTK4 theming, but I know that theme detection can be properly configured at least with GNOME.

In the end user perspective, I think that this kind of thing should work out-of-the-box. Many user don't know what a toolkit or even a desktop environment is, They just expect that everything will function right.

**Comment by a-lameira** [comment]
On Transmission's official website it written: "Native for Your System: Unlike many cross-platform applications, Transmission integrates seamlessly with your operating system. The GTK interface has been carefully written to follow the GNOME Human Interface Guidelines and features."

If it is true today, it means that the GTK4 version of Transmission has to use libadwaita to conform to GNOME's guidelines. If the objective is a seamless integration with GNOME, the GTK version of the app has to be ported to the current GNOME reality, that is, libadwaita.

**Comment by mikedld** [comment]
@a-lameira we're not responsible for how other people build and distribute Transmission. I can easily say that Debian package maintainer(s) could have tested the app before releasing the new package version, and realise the same thing you did: that building against GTK 4 doesn't bring the best user experience for their distro; and they could have chosen to continue building against GTK 3. Bringing this issue to our attention is somewhat pointless because we're not the ones packaging it for Debian or any other distro out there.

There indeed are redesign suggestions which are tracked elsewhere, but they have little to do with the issue that you're reporting, and I don't see a line of people willing to volunteer their time to the implementation, or even a proper discussion based on @ckerr's feedback there. Time permitting, I'm doing what I can to make that redesign easier to do in the future, but I'm basically the only person on it.

**Comment by ckerr** [comment]
Closing this ticket as not a Transmission bug.

It probably is worthwhile to consider using libadwaita to act as a native GNOME app.

Calling the GTK client "abandoned" is just ignorant. A decent amount of work went into glibmm / gtkmm modernization for Transmission 4.
