### ISSUE TITLE
generate torrent peer-ids on launch; do not periodically recycle

### ISSUE THREAD

**Issue by Tockman** [transmission/transmission#5232]
### What is the issue?

Other month I merely get a ban on my favorite torrent tracker. The reason told by its admin, was the following: during all my part in beta testing process, since October, 25 2022 up to February, 8 2023, my Transmission client has reported more than 700 (!) different ID's (looking like peer_id=-TR4010-XXXXXX, where XXXXXX changed many times a day).  That lead to "Could not insert peer details; Error: Duplicate entry '862-782ebf57' for key 'PRIMARY'" error and violating tracker rules as a consequence.
Since beta testing will go on, may respected developers improve something to avoid such an inconvenient situation?
Thank you very much.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0 b1, b2, b3

**Comment by ckerr** [comment]
The TTL for a peer-id is currently 6 hours, though this is configurable in settings.json.

Although [BEP 020](https://www.bittorrent.org/beps/bep_0020.html) has some description about different clients' peer-id values, AFAICT therer are no spec-level guidelines for how often to recycle the peer -id. [This question](https://forum.bittorrent.com/topic/50977-question-about-peer-id/) from the bittorrent forums indicates that the BitTorrent app randomizes them on launch, as does libtorrent.

If this is what trackers are expecting, maybe it's time to use that behavior instead of 1f2bccd17

**Comment by garoto** [comment]
> This is very inconvenient for private trackers because the peerid is the only thing you can rely on for stat accounting.

Private trackers use a hash (aka `passkey`) which is sent as part of the announce URL to identify users and track stats.

**Comment by ckerr** [comment]
> @ckerr Do I understand correctly that transmission 4.0.0 to 4.0.2 do generate a new peerid every six hours?

For public torrents, yes. Private torrents, no. Private torrents do it once, upon launch.
 
> With #5233, is there still a chance for a peerid to change during a session?

No. 5233 simplifies the code by having public torrents behave the same way now, too.

**Comment by Tockman** [comment]
Should I correct my initial post regarding changing part of peer-id?
