### ISSUE TITLE
The real speed limit is one tenth of the set speed limit

### ISSUE THREAD

**Issue by gduckHUN** [transmission/transmission#5270]
### What is the issue?

For example, when I setting speed limit to 10000 KB/s, the applied speed limit is 1000 KB/s.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.2

**Comment by ckerr** [comment]
What tool are you using to set the speed limit?

**Comment by ckerr** [comment]
I'm not able to reproduce this.

![speed-limit-down](https://user-images.githubusercontent.com/70381/226746232-ea3938d0-3908-4039-9897-c4983b02a5a5.png)

Tested with a fresh install + transmission-gtk + transmission-web.

IDK what the issue is with your system's configuration, but two thoughts that might be worth looking at:

- Make sure that the config file you're looking at is the one being used by Transmission, e.g. if you start the daemon with `transmission-daemon -f -g /path/to/config-dir` does it work; if you change other settings do those changes set up, etc.

- transmission-remote-gui is a [3rd party app](https://github.com/transmission-remote-gtk/transmission-remote-gtk). It's a good app that I like a lot; but since it's not maintained by this project, IDK if there are or aren't any issues in 5.18. You might want to check out their issue tracker.

**Comment by gduckHUN** [comment]
Thank, you, I will try to find the reason ;)

This is a fresh install, the used config file is correct.  The hardware is a Zyxel NAS with armv5. The transmission is own build with cmake 3.13 and gcc 7.5.0. May be is this a  build problem?

**Comment by ckerr** [comment]
Since IDK what the problem is I can't rule out a build problem -- but I don't know what kind of build problem would cause this, so probably not? :man_shrugging: 

- If you exit, _then_ edit settings.json to double the speed limit, _then_ restart Transmission, does the value in the UI double too?

- Just to reduce the number of variables, what happens if you _only_ use transmission-web or _only_ use transmission-remote-gtk?

**Comment by gduckHUN** [comment]
Hmm... I made some test! 

So, sorry but in my first picture the settings.json file is not correct! Because, the file is in memory and is only updated when I stop the transmission-daemon. So, with the both "config tools" (settings.json editing or webclient or remote gui) the speed limits values are equal!

But the applied speed limits are different. If the setting is 10 000 KB/s = 10MB/s, but my max speed is **1.4 MB/s**. I tested this with 10 differrent torrents with hundreds seeders (my Internet speed is an optical 1/1 Gbit/s). If  I change to 100 000 KB/s, I can cross this limit immediately!

Strange...
