### ISSUE TITLE
4.02 Qt Win lost ability to edit tracker when connecting to server 2.84 (14307) 

### ISSUE THREAD

**Issue by megaslowpoke** [transmission/transmission#5314]
### What is the issue?

Windows 10/11 any

The new version has lost the ability to edit a tracker, the edit tracker button opens a window for adding rather than changing the highlighted tracker.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by ckerr** [comment]
I think you might be misunderstanding the dialog?

The 'Edit Trackers' popup dialog lets you edit any / all of the trackers in a single text window. You _can_ add trackers there, but you can also change them or remove them.

**Comment by megaslowpoke** [comment]
Well, in that case they won't be on this list, which can be edited, the input field is just blank.

But sorry, my bad, I forgot to add an apparently important detail: the GUI is only used to connect to the 2.84 (14307) server and the server is not running locally, apparently this is a compatibility issue.

**Comment by ckerr** [comment]
Yes, that's right.

Since Transmission is following semver (major version bump == breaking changes, minor version bump == backwards-compatible new features, patch bump == bugfixes), you'll generally want to have a frontend client with the same version as the backend and a minor version >= the backend.

I'm going to close this as not-a-bug since it doesn't really make sense for 2.84 to be able to serve API from 4.0.2 which was released seven years later, but I get it how it could be confusing.

**Comment by megaslowpoke** [comment]
OK, but sorry, one more thing, can you please advise which maximum version I need to stay on to work with the 2.84 server?
