### ISSUE TITLE
4.0.2-dev - do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error (peer-mgr.cc:618)

### ISSUE THREAD

**Issue by yolanjoy** [transmission/transmission#5320]
### What is the issue?

Transmision would fail to download with lots of dbg errors like this --

do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error (peer-mgr.cc:618)

In Remote GUI, "Done" stays at 0.0% but "Downloaded" increases. 

Is this a bug/known issue?

Thanks

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.2-dev

**Comment by ckerr** [comment]
`ERANGE, EMSGSIZE, or ENOTCONN error` could mean anything, e.g. peers in the swarm that are no longer online or that don't have an open port. That's why this is a debug message rather than an error message.

This sounds like you're trying to join a swarm that doesn't have any other reachable peers. Which is annoying, but not a Transmission bug.
