### ISSUE TITLE
How to report correct ipv6 address to trackers in transmission 3.00?

### ISSUE THREAD

**Issue by Rage6408** [transmission/transmission#5336]
### What is the issue?

On bare metal running transmission daemon 2.94, I am able to report the right ipv6 address to my trackers (the public ipv6 of the host machine). However, running transmission 3.00 in docker from linuxserver/transmission, the ipv6 address reported is the ipv6 address docker assigned to my container. This is not routable from the outside internet and thus most trackers don't report ipv6 connections even though I can connect to an ipv6 only tracker (tracker.ipv6tracker.ru). Is there any way to change the ipv6 address transmission reports to trackers on transmission 3.00 or higher? I tried "bind-ipv6-address" but then I couldn't connect to trackers at all. I also tried "announce ip" but that didn't seem to have any effect (maybe only works on transmission 4.0+).

I also tried the above methods with transmission 4.0.2 but transmission 4.0.2 doesn't seem to report an ipv6 address at all.

Sorry for any stupidity; I find ipv6 pretty confusing. Also if this is better addressed to the linuxserver/transmission docker team let me know.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00 in docker. (amd64-3.00-r5-ls126)

**Comment by tearfur** [comment]
I have been messing with the code in this area recently. I think I know enough to tell you how it works: 

- In `4.0.2`, with the default settings, Transmission will only announce with either one of IPv4 or IPv6, leaving it to the OS to decide which protocol to use. You have to set `bind-address-ipv6: ""` in `settings.json` to make Transmission announce both IPv4 and IPv6. This behaviour will change in `4.0.3` #5206.
- Starting from `4.0.0`, Transmission no longer reports IP addresses using the `&ipv4=` and `&ipv6=` parameters. This method is based on an older version of BEP-7 (BEP-* documents define the BitTorrent protocol standard). This is how `2.94` reports IPv6 addresses.
  Instead, when Transmission `> 4.0.0` is configured to announce both IPv4 and IPv6, it will announce twice: Once for IPv4, once for IPv6. Since this is a rather recent update to BEP-7, trackers that cannot deal with this is not uncommon.

**Comment by Rage6408** [comment]
Thank you for elucidating that. Some of the trackers can't deal with the 4.0.* method since I guess it is too new.  Is there any way to change the &ipv4= and &ipv6= parameters in transmission 2.94 or 3.00?

**Comment by tearfur** [comment]
For IPv6, Transmission will just take whatever the OS gives it. So you gotta give your container a global IPv6 address.
