### ISSUE TITLE
transmission-remote: options are position-dependent

### ISSUE THREAD

**Issue by sandrotosi** [transmission/transmission#54]
```
$ transmission-remote --version
transmission-remote 2.92 (14714)
```

i got:

```
$ transmission-remote HOST -n user:pwd -l | wc -l
942

$ transmission-remote HOST -l -n user:pwd | wc -l
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User-www-form-urlencoded

0
```

so if i dont set -n before -l i am not authenticated with the remote host; i would have not expected the options are position-dependent and so you have to specify them in a specific order

**Comment by mikedld** [comment]
This is by design. Options (like `-n`) which influence commands (like `-l`) should go before them, as each command is executed as soon as it's met in argument list. So in your first invocation, `-n` is being processed before `-l` and thus has its effect on `-l`; in your second invocation, `-l` is being processed first, and then `-n` is processed but has ho effect on anything as there are no commands following it.
