### ISSUE TITLE
Download do not start if torrent added through magnet links of private trackers,

### ISSUE THREAD

**Issue by cry0xen** [transmission/transmission#552]
daemon windows latest.
added magnet links through transgui. download did not start.download works Seeder /leechers no. shown is correct. when .torrent added directly or drag n drop it works just fine.

**Comment by vctls** [comment]
Problem with special characters, maybe?
There's an issue on that : #61

**Comment by ckerr** [comment]
This is likely because the magnet link did not contain the tracker announce information.

If the magnet link doesn't have the tracker announce URL, then it will just look through public peer networks trying to find someone who has that torrent -- which of course it never will, since it's not a public torrent.

Should work fine if you add the .torrent file directly _or_ if you create a magnet link that includes the tracker announce URL.
