### ISSUE TITLE
Transmission's new program and document icons are fuzzy in Windows 10

### ISSUE THREAD

**Issue by bananakid** [transmission/transmission#5567]
### What is the issue?

Transmission's new program and document icons are fuzzy in Windows 10, version 21H2 at 200% UI scale:
![Preview - 01](https://github.com/transmission/transmission/assets/17095595/ecdad662-b271-47cf-a70e-943b0eebc30f)

This is what the icons should look like (icon by [yw4z](https://github.com/transmission/transmission/issues/1360#issuecomment-783600708) with quick highlights +30 & shadows +15 edit using paint.net):
![Preview - 02](https://github.com/transmission/transmission/assets/17095595/480dddb0-6c98-4797-a710-dd8d68669dbd)
![Preview - 03](https://github.com/transmission/transmission/assets/17095595/629268bd-9094-4c7c-8786-6274ff8025b9)
[ICO files](https://github.com/transmission/transmission/files/11617508/Transmission.zip) (created with [paint.net 5.0.5](https://github.com/paintdotnet/release/releases) and [this plugin](https://forums.getpaint.net/topic/927-icon-cursor-and-animated-cursor-format-v37-may-2010/)) from these screenshots for reference on the icon sizes in Windows 10.

P.S. The default Start menu icon is different altogether for some reason: 
![Preview - Start Menu](https://github.com/transmission/transmission/assets/17095595/278d6c34-4ddc-4eb4-afca-e65346c512ae)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3

**Comment by GaryElshaw** [comment]
I've been sort of working on this with #4376 but will pr separately to address that issue.

**Comment by bananakid** [comment]
@GaryElshaw thank you, unfortunately it appears you're talking about different icon in [#5570](https://github.com/transmission/transmission/pull/5570).

See, for some reason Transmission binary transmission-qt.exe has one kind of icon in File Explorer, it has the resolution issue:
![File Explorer](https://user-images.githubusercontent.com/17095595/242363017-ecdad662-b271-47cf-a70e-943b0eebc30f.png)

But Transmission running executable is using a different outdated icon which doesn't have resolution issue:
![Transmission](https://github.com/transmission/transmission/assets/17095595/469a4166-bf2d-44c5-92b8-f18dbb170d14)

The icon mentioned in [4288b20](https://github.com/GaryElshaw/transmission/commit/4288b20c2f36405804131dba7b323826bf51332c) addresses only the second icon. However I'm talking about the first icon (and icon design consistency of Win32 build for that matter). I'm also taking about `.torrent` document file icon in Windows as well.

I will be happy if you could point out source file location (or at least 512×512 PNG) for updated Transmission icon since I can find no promo materials at Transmission website. I'd like to have a look if I can contribute proper ICO for Win32.

**Comment by GaryElshaw** [comment]
Hi @bananakid, there are a couple of different issues going on here which is why it often gets confusing. The application in your second image is the correct Transmission qt application icon, the other one, and the one you correctly pointed out had terrible resolution is actually the Transmission macOS icon and shouldn't have been part of the qt client at all.

Here's the differences:

Transmission GTK

![transmission-gtk](https://github.com/transmission/transmission/assets/69029666/cdcf2811-c7d3-48ee-84df-fd3d1d461623)

Transmission qt

![transmission-qt](https://github.com/transmission/transmission/assets/69029666/5134d8d6-9b17-4115-8892-ef86d196c1c0)

Transmission macOS

![icon_128x128](https://github.com/transmission/transmission/assets/69029666/35bae09c-5fd7-4003-a754-eb1d6e3ee9ac)

The other document icons are unfortunately something that is outside of control of the project and have been used by whomever is packaging Transmission. I don't have access to Windows, but if you build Transmission qt, i don't think you will see those icons being used.

**Comment by bananakid** [comment]
Thank you for taking time to explain this and for your continuous work on improving application, @GaryElshaw!

I think I have to take a look into building Win32 Qt version to see if it's possible to tinker Win32 icon and UI from there. I have managed to build Equalizer APO with Qt 5 last year, however Transmission appears to be a whole different kind of a beast. I hope following steps in current [Building-Transmission.md](https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md) is enough.

**Comment by GaryElshaw** [comment]
Those instructions in the file look up to date to me, but i imagine they have Windows 10 and 11 rather than Win32 in mind :-(
