### ISSUE TITLE
transmission-daemon goes 100% cpu after some time

### ISSUE THREAD

**Issue by blind-oracle** [transmission/transmission#5610]
### What is the issue?

After a day or less `transmission-daemon` starts eating 100% of one core and responds to the Web UI very slowly. Restart fixes it. 

I'm building it from the source on Ubuntu 22, tried 4.0.3 and then just latest master, no changes.

Built using:
```
cmake .. -DENABLE_DAEMON=ON -DENABLE_GTK=OFF -DENABLE_QT=OFF -DENABLE_MAC=OFF -DINSTALL_WEB=ON -DINSTALL_DOC=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/transmission
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.3 and 0ef58c2a20019096aed0ab639f2207b8e1c1b248

**Comment by ckerr** [comment]
@blind-oracle you indicated you're building from source on Ubuntu, so this is probably an easy reach for you: could you take a fresh build with debugging symbols and run it through perf -> hostpot?

Specifically, the steps would be

1. make a debug build on CMake so the following steps will have the debug info they need. Something like `cmake -DCMAKE_CXX_FLAGS="-gdwarf-4 -fno-omit-frame-pointer" -DCMAKE_C_FLAGS="-gdwarf-4 -fno-omit-frame-pointer" -DCMAKE_BUILD_TYPE=Debug` and then whatever other options you need for your system
2. run `perf` on the transmission-daemon build straight out of the build directory, no install step needed, e.g. `perf record --call-graph dwarf --freq=max ./build/daemon/transmission-daemon`
3. leave it running while the CPU goes to 100%. You want to record enough of the CPU spike so that the profile will show us what the problem is.
4. then `hotspot perf.data`. This will let you visualize what the issue is.

One thing I _don't _ know is how portable the perf.dat is, e.g. whether or not I'll be able to run hotspot on it from my machine if you attach perf.data to this ticket. Let's try and find out; because if that works, that would be ideal. Otherwise, we should still be able to figure it out from you looking at hotspot on your machine.

AppImage of latest hotspot release is @ https://github.com/KDAB/hotspot/releases

**Comment by killemov** [comment]
> hostpot?

Host + honeypot?

Anyway just mentioning that 100% CPU usage for no obvious reasons has happened with way older versions of transmission-daemon as well. I suspect some tight loop with no yielding somewhere.

**Comment by blind-oracle** [comment]
@ckerr I couldn't really use `perf` directly since with `--freq=max` it generates shitload of data, and even with like 1000hz it's anyway a lot. So I used `flamegraph-rs` which generates it directly by wrapping `perf`.

Here's the flamegraph, it looks like most of the time is spent in `tr_address::compare` for some reason. 
https://github.com/transmission/transmission/blob/76166d8fa71f351fe46221d737f8849b23f551f7/libtransmission/net.cc#L592

This looks like a simple `memcmp`, probably it gets called very frequently.

So it's caused by peer exchange?
![transmission](https://github.com/transmission/transmission/assets/592248/9257857a-6f17-4dc1-b3be-57160a9117e6)

**Comment by tearfur** [comment]
For `get_existing_atom`, why not use `std::map`? It does not invalidate pointers/references/iterators etc.

**Comment by blind-oracle** [comment]
Just to be sure - I've disabled PEX and can confirm that CPU load dropped from almost always 100% to some 20-30% when doing 100Mbit seeding.

The flame graph is also very different:
![transmission2](https://github.com/transmission/transmission/assets/592248/99514084-d312-4a93-86c7-d821e3ef878c)

**Comment by ckerr** [comment]
> For `get_existing_atom`, why not use `std::map`? It does not invalidate pointers/references/iterators etc.

Based on these heat maps it looks like a `map` is the better container here.

But to answer the question, I've never seen this kind of performance hit in atom lookup and was working from an assumption that the number of peers in the pool would be relatively small, so I defaulted to a container with contiguous memory for better locality + to avoid the node overhead of a map. And I chose a deque over a vector to avoid invalidation. Obviously this choice is less appropriate when N is large...

**Comment by ckerr** [comment]
(Also there may be another perf followup here to inline `tr_address` comparisons. Looks like we could especially improve when comparing IPv4 peers to each other just by looking at s_addr as an unsigned long)

**Comment by tearfur** [comment]
@blind-oracle Do you mind trying out #5645 and telling us your results?

**Comment by blind-oracle** [comment]
@ckerr I have `Global Peer Limit` set to 10k and a 10Gbit link, maybe this together somehow makes this data structure saturated after some time...

@tearfur thanks, I will try!

**Comment by tearfur** [comment]
> I have Global Peer Limit set to 10k and a 10Gbit link

Damn, if you also seed a lot of torrents, I imagine that's gonna give you *a lot* of peers. Then of course the linear search method currently in `main` will be slow.

> thanks, I will try!

Please enable PEX as well, of course. Appreciate your help.

**Comment by killemov** [comment]
> (Also there may be another perf followup here to inline `tr_address` comparisons. Looks like we could especially improve when comparing IPv4 peers to each other just by looking at s_addr as an unsigned long)

Again one of those implementation remnants that you'd assume was implemented that way from the start.

**Comment by blind-oracle** [comment]
All seems ok now, thanks for the fix!
Now, it seems, Red-Black Trees are occupying the stage 👍 

![flamegraph_fix](https://github.com/transmission/transmission/assets/592248/0f968bfa-369e-4a05-879d-da5ae74de95b)
