### ISSUE TITLE
Peers appearing and disappearing

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5816]
### What is the issue?

Noticed this quite a lot recently, regardless of the torrent. Peers blinking in and out of the inspector window. Not confined to macOS, i've noticed this behaviour in the Qt and GTK clients as well.

https://github.com/transmission/transmission/assets/69029666/ab3fc5fa-1e7c-424b-8044-60a305c8e132

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-dev (f758cb3597)

**Comment by Pentaphon** [comment]
I noticed this too on the 4.0.3 Qt client but i wasn't sure if it was just attempting another reconnect.

**Comment by tearfur** [comment]
If you are not inspecting a private torrent, then this is probably the effect of #5756.

You can try regress to the commit before that if you wanted to test. :)

**Comment by GaryElshaw** [comment]
> probably the effect of #5756.

I get errors (probably my misguided copy/pasting), i'll wait :-)

**Comment by tearfur** [comment]
Just to be clear, I don't mean that 5756 introduced an unwanted effect.

What it does (I think) is to allow Transmission to briefly connect to other peers to look for potential peers to seed to, even when itself and all other known peers are seeds.

**Comment by GaryElshaw** [comment]
Sure thing, it just seems like a lot of traffic for the same peer(s).

**Comment by tearfur** [comment]
That's probably because they were historically the "best" peers. Then, now that Transmission has finished downloading and activity for that torrent drops down, the stats for each peer don't get updated often, and the same "best" peers tends to get chosen every time.

**Comment by GaryElshaw** [comment]
In the video above, the peer had just completed something i was seeding.

**Comment by tearfur** [comment]
Makes sense.

That peer is the most recently active peer that you know of, so it is the place where you are most likely to get up-to-date information about the swarm. I think it is a logic decision to prioritise that peer.

And before you meet another even more active peer, you have no better choice.

**Comment by GaryElshaw** [comment]
> No. For that ticket, if you want something done about it, could you please explain why you think it is iffy and what the correct behaviour should be? I'm not understanding where you are coming from.

There should not be the amount of activity there is of the _same peers_ appearing and disappearing in the inspector panel. 

The clip above is of a peer who has just completed a torrent. A. Theoretically it should be showing 100%. B. If the peer has completed the torrent, why is Transmission appearing to open and close the connection to the peer?

This behaviour is also happening when there is no active seeding happening. The same peers cycle through over and over, infinitely.

**Comment by tearfur** [comment]
@GaryElshaw

I've already explained some of the reasons before, and I don't know which of those didn't make sense to you since you did not give me a rebuttal. It'd be great if you did, so the conversation can progress.

I'll try to explain them again and also add some more possible reasons to it. Hope it helps.

> Theoretically it should be showing 100%

Transmission stores the completed percentage of each peer *by connection*. This means as soon as the peer disconnects, we throws away this information.

**Reason:** By the BT protocol, we rely on the peer to tell us how much of the torrent they have, and that can only be done while we are connected. While we are *not* connected to the peer, they are free to delete the data at any time *and we won't know about it*. A simply way to handle this is to assume the peer has 0% of the torrent every time we start a new connection to them, and wait for them to tell us what they have, which is exactly what Transmission currently does.

We can actually see from your video clip, that a peer will always start with 0%, sometimes jumping to 100%. That's exactly what happens when the peer had just told us what they have.

> If the peer has completed the torrent, why is Transmission appearing to open and close the connection to the peer?

1. It may also be the peer constantly trying to connect to us.
2. Communication between peers *are not limited to* transferring torrent data. Even when both ends are seeding, there are still conversations to be had:
   - As explained above, while we are not connected to a peer, we don't assume anything about how much of the torrent they have.
   - Peers (seed or not) might be able to tell us about some other peers we don't know of, so it makes sense to ask around for new potential peers to connect to. This mechanism is named [PEX](https://www.bittorrent.org/beps/bep_0011.html).
   
   For these reasons, Transmission constantly attempts to open new peer connections, regardless of whether the peer was a seed the last time we connected to them.
   
   As for why you keep getting the same peers, assuming (1) is not the reason, there are still too many of them to explain. But most likely, those are the only peers that you were able to reliably connect to, so Transmission treats them as the "best" peers and keeps trying them.

**Comment by GaryElshaw** [comment]
What you have said is all completely reasonable, and i agree that the behaviour you are describing is probably what is occurring. My issue is that the behaviour seen in the clips is relatively new. 

Previously, this is how i would describe the activity cycle in the inspector panel:

1. The addition of a new torrent or resumption of an old one would involve the expected flurry of contact with trackers/pex etc --> relative calm of peers to upload/download to or from.
2. A trickle of peers appear and disappear, until...
3. Tracker updates (Repeat 1 -3)

That is still largely the case, but the two clips reflect, to me, that there is also some kind of loop that is happening between client and some peers. In my case, i am seeding around 10 torrents, and i'm seeing this looping behaviour regardless of time. It can happen when starting the seed and equally if the client has been running several hours.

**Comment by tearfur** [comment]
Does this looping behaviour have any negative impact?

**Comment by GaryElshaw** [comment]
Framing it like that can only elicit a subjective response. I would say yes, it means there is greater network activity than there should be. Either Transmission is behaving badly by trying to initiate unwanted/unnecessary connections, or Transmission is behaving poorly by unnecessarily responding to poor client requests.

**Comment by tearfur** [comment]
> Either Transmission is behaving badly by trying to initiate unwanted/unnecessary connections, or Transmission is behaving poorly by unnecessarily responding to poor client requests.

I have been looking over this part of the code in the past few months, and I've fixed whatever I can find. Whatever that's left, it will be beyond me unless someone point it out.

> Framing it like that can only elicit a subjective response.

If what you have is a reasonable belief and not just a hunch, of course not.

You can start investigating by capturing some packets using Wireshark. It can feel like tedious nitpicking, but they will amount to a fix if you spot something (see #5206 and #5825 for such examples).

**Comment by tearfur** [comment]
Related to #6910.
