### ISSUE TITLE
Option to add Manual Peer (feature)

### ISSUE THREAD

**Issue by Juniorsnet** [transmission/transmission#5851]
### What is the issue?

In case of a trackerless torrent some time I needed to add a manual peer to start the transfer sooner. So I its will be helpful to add the option to add a manual peer (ip:port).

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3

**Comment by killemov** [comment]
AFAIK there is a hack for this. Legend has it that adding `peer:127.0.0.1` (your IP there) as a tracker should work. Anybody from the team confirm/deny?

**Comment by Juniorsnet** [comment]
> AFAIK there is a hack for this. Legend has it that adding `peer:127.0.0.1` (your IP there) as a tracker should work. Anybody from the team confirm/deny?

Does not work, complain about malformed tracker url

**Comment by tearfur** [comment]
Duplicate of #808.

**Comment by purpleidea** [comment]
This would be very helpful. Why am I interested in this? I've noticed that on two separate torrent instances I'm testing don't connect to each other or initially connect and then lose the connection somehow. I assume this is due to the ISP's playing network management games and causing disconnects. I'd like to experiment more with this behaviour and this feature might aid that. Thanks!

**Comment by antnks** [comment]
I made a universal peer injector for all the clients that do not support adding peers natively.
The python script creates a fake tracker that responds with your given peer(s).
Then you simply add it as an additional tracker `http://127.0.0.1:1337/announce` - and your client picks the peers. After injecting the tracker can be shut down. A bit hackish way, but it works well with Transmission.
https://github.com/antnks/bittorrent_peer_injector
