### ISSUE TITLE
Change "Successfully updated source/global IPv4/v6 address" log message from "Info" to "Debug" log-level

### ISSUE THREAD

**Issue by fredo-47** [transmission/transmission#5864]
### What is the issue?

Currently, the source and global IPv4 and IPv6 addresses are written to the log file every 30 minutes.
They are written in log level "information".
This means 8 messages per hour to the log file

In my opinion, this is not really much important information most of the time.
In my case, I receive a new IP every 24 hours, so these messages report something new only every 24 hours for me.
I would think that this information is only relevant when something does not work.

How about changing these log messages to log-level "Debug"?
This way, the log file could be kept somewhat cleaner in the default "Info" level.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

a2849219f7

**Comment by tearfur** [comment]
The reason why I put that information in `INFO` is so that even people who didn't bother with log level have a higher chance of noticing if their Transmission configuration or network setup went wrong.

I'm not too sure what you mean by "clean" log and why that is important. Would appreciate some explanation.

**Comment by fredo-47** [comment]
> I'm not too sure what you mean by "clean" log and why that is important. Would appreciate some explanation.

I meant that on the default `Info` log-level, the log gets a lot of messages (8 messages per hour), even though nothing is actually happening or changing.
So I would find these messages unnecessary in the `Info`  level, but rather consider them in the `Debug` level

**Comment by tearfur** [comment]
Would you mind if we defer this discussion after the release of `4.1.0`, because I'm honestly not too sure which log level is the better one here.

I'm sure there are users that find it important to know that Transmission is listening on the interface they intend it to be listening on. There are already some people who've shown interest in showing the public IP in the GUI at #5618, and I'd imagine the closest equivalent location for the daemon is in the `Info` log level.

**Comment by tearfur** [comment]
You know what, I changed my mind. I am leaning towards this suggestion.
