### ISSUE TITLE
Tracker HTTP response 0 (No Response)

### ISSUE THREAD

**Issue by SteffanCline** [transmission/transmission#6035]
### What is the issue?

I am running into the issue with **dozens** of, _not all_, torrents all throwing this error "Tracker HTTP response 0 (No Response)". I have googled this issue extensively and have tried every single thing mentioned. I am running the latest Transmission version 4.0.4 and WireGuard within a docker from https://hub.docker.com/r/linuxserver/transmission on Ubuntu Server 22. 

From the config, this is what I have for the bindings.
```
"bind-address-ipv4": "10.13.x.x",
"bind-address-ipv6": "::",
```
For ipv6, I have tried "::", "::1" and "" but they do not seem to make a difference.

The inbound port mapping from WireGuard is working fine so I'm not sure what else to check.

I am using Google DNS 8.8.8.8. I grabbed the URL and tried it via curl.
```
curl http://domain.tld/announce.php?pid=xxxxxxxx
d14:failure reason119:Your client does not support the 'compact' tracker feature, please change/upgrade your torrent client to one that does.
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4

**Comment by SteffanCline** [comment]
I've continued to google for this error and can't find a solution. Surely y'all have seen this before. No suggestions?

**Comment by tearfur** [comment]
Your error usually means the tracker requests from Transmsision can't even reach the destination. Maybe `10.13.x.x` is a network interface from the host machine, but you didn't set Docker to use [host network driver](https://docs.docker.com/network/drivers/host/).

If you are sure you got your network settings right, then since Tranmission uses libcurl for HTTP requests, you could try mimic Transmission's behaviour with the commandline to see what exactly is wrong.

For example, you can start with trying `curl --interface 10.13.x.x -v` to find out if there are anything wrong with your IPv4 interface. You can find the rest of Transmission's curl parameters from `tr_web::Impl::initEasy()` in `libtransmission/web.cc`.

**Comment by alolalo** [comment]
> I've continued to google for this error and can't find a solution. Surely y'all have seen this before. No suggestions?

In today's psychology this kind of language-use is called "transference by incompetence" because it uses double binding to close the information-loop, that implodes on itself if you would have realized both statements you make cancel each other out.

In other words; practice what you preach, or perish when you poop

**Comment by starkgate** [comment]
What worked for me for a specific tracker is to change the tracker url from http to https.
