### ISSUE TITLE
outdated translation file ru.po in 2.94

### ISSUE THREAD

**Issue by stmc** [transmission/transmission#606]
The new transmission 2.94 contains an outdated translation file into Russian, although in the repository for more than a year is a new file https://github.com/transmission/transmission/blob/master/po/ru.po
How did the outdated file get into the new version of transmission? In this file there are incorrect translations that interfere with the normal use of the application. It needs to be somehow solved.

**Comment by Cye3s** [comment]
Same here, zh_CN po on 2.9x branch is 5 years ago
Why not merge po files on master?

**Comment by ckerr** [comment]
Hey, I know this issue was filed a long time ago so maybe this is no longer an issue.

But, to check in to make sure -- I don't think I understand this report. Before each release, we just download the translations in bulk from transifex and merge them in to `main` then as part of the prerelease procedure. Did 3.00 also have an outdated ru.po?

**Comment by Cye3s** [comment]
zh_CN is OK now, thanks.
