### ISSUE TITLE
Network port test does not support ipv6

### ISSUE THREAD

**Issue by davidshen84** [transmission/transmission#6060]
### What is the issue?

![image](https://github.com/transmission/transmission/assets/65741/f9ef253e-61ab-401e-858e-9c3d6fda6c25)

The UI does not indicate if it will use the detected external IPv4 or IPv6 address to test the open port. I suspect it only uses ipv4.

After checking some torrent downloading statuses, I can see many incoming connections using ipv6 addresses, not no incoming connections using ipv4 addresses. Because my ISP uses CGNAT for IPv4 addresses, there's no way the external world could connect to me via the IPv4 address, but they also support prefixed ipv6 assignment, so my devices can have a global unique ipv6 address.

So, I think the port testing tool should also support ipv6. Even better, allows users to choose which address they prefer.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by tearfur** [comment]
I have proposed a solution for the WebUI at #5953. If it gets accepted, then IMO all other UI should follow.

Related:
- #5496
- https://github.com/transmission/portcheck/issues/7
- #5607

**Comment by davidshen84** [comment]
@tearfur ,

The UI part of your PR only includes WebUI changes. But I think the CC changes you made can also be used by the QT UI component. Do we have a PR or Bug addressing this?

Thanks

**Comment by tearfur** [comment]
No, not at the moment.

If I were to port that feature over to the qt UI, I would wait until #5953 is merged, because it implies that the core developers have accepted the idea of having the feature in Transmission's UI on all platforms.

**Comment by theirongiant82** [comment]
This is still broken in Transmission 4.0.4 on macOS 12.6.8 (Monterey).  It appears to be more than just a UI bug, because trackers report my port as closed after a few days of Transmission running without issue.  Newly added torrents struggle to gain peers.  Only remedy is to quit & relaunch Transmission.

My ISP does not assign IPv6 addresses, and my router does not support IPv6 port mapping as far as I'm aware.  Other applications with statically mapped or UPnP ports continue to work, including: Plex Media Server, Air Video Server HD, Deluge 2.x, and a Synology NAS.  

Only Transmission seems to have this problem.
