### ISSUE TITLE
2.94 always verifying local data on startup (Windows x64)

### ISSUE THREAD

**Issue by Fr3dY2** [transmission/transmission#607]
Hi,

After updating to 2.94, I've noticed that torrents are verified each time I start the program.
I tried stopping the torrent before closing Transmission, but nothing changed.

Regards,

**Comment by Fr3dY2** [comment]
This is weird... even removed torrents come back again on restart (and local data is verified again).
I'll reinstall, removing the <USER>\AppData\Local\transmission folder first and report back.

**Comment by Fr3dY2** [comment]
After uninstalling and removing the app folder, everything came back to normal again.
This never happened to me when upgrading to nightly builds.

**Comment by lnicola** [comment]
I'm seeing the same thing. Removing the `resume` folder doesn't help.

**Comment by Fr3dY2** [comment]
I uninstalled the application and then removed the transmission folder completely before installing 2.94 again. It has been working fine since then, could you try?

**Comment by lnicola** [comment]
I'd rather not, because I don't want to lose my torrents and settings (: .

**Comment by Fr3dY2** [comment]
Then wait for your torrents to complete before doing it, or do a backup copy before playing with it.
Settings could be configured again without much trouble I guess.

**Comment by lnicola** [comment]
I don't think deleting the directory fixes anything directly. I tried to download a new torrent. It works fine (shows up as running after restart). But the old ones still get rechecked and come back if I delete them (they stay paused, though). I think this is why re-installing worked for you.

Since I already removed the `resume` directory, the only things left of those old torrents are the files in the `torrents` directory.

I also removed a torrent, then downloaded it again while keeping the files on disk. It worked fine, even though I didn't remove it properly (by deleting the two files from disk).

So I'm a bit stumped.
