### ISSUE TITLE
replace libtransmission/ConvertUTF.{c,h} with supported alternative

### ISSUE THREAD

**Issue by sandrotosi** [transmission/transmission#612]
Hello,
libtransmission/ConvertUTF.h,c are released with a non-free license (Unicode) and got flagged by this check in debian: https://lintian.debian.org/tags/license-problem-convert-utf-code.html

would it be possible to replace them with libicu, as suggested on that page?

thanks for considering!

**Comment by sandrotosi** [comment]
any specific results for speed issues? a lot of programs (just by a very quick look, even nodejs (the current hype lol)) use libicu, so it seems expected there could be speed concerns. they may also be addressed in the time being?

what about size? since it's going to be a shared library, i would expect size not to be an issue

thanks!

**Comment by xavery** [comment]
Transmission currently uses only three functions from ConvertUTF.h : `ConvertUTF8toUTF32`, `ConvertUTF32toUTF8` and `tr_utf8_validate`. The first two cannot be easily replaced with ICU, since it works with UTF-16 internally and requires any conversions to be made via UTF-16. I think this is the speed/size issue that Mike might be referring to. `tr_utf8_validate` can be probably directly mapped to a ICU call, unless the `g_utf8_validate` function that it's modelled on does some nonstandard things.
However, the remaining two functions are only used from within `variant-json.c`. Interestingly, the JSON parser is subtly wrong in the way it parses `\u` escaped values that can appear inside strings in JSON : it assumes that each of `\u` values represents an independent Unicode character, while [page 5 of the spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) says that it might also a UTF-16 surrogate pairs, so a sequence like `\uD834\uDD1E` is going to be parsed as two independent UTF-8 characters. Surrogate characters are marked as reserved for exclusive use in UTF-16 in the Unicode map, so the JSON parser is going to produce "reserved" (but readable) UTF-8 characters in the output. If this behaviour is fixed, moving to ICU is going to be arguably a bit easier.

**Comment by ckerr** [comment]
I've added "pr welcome" and tweaked this issue's topic to discuss the problem without endorsing a specific solution, since there appear to be some tradeoffs. @xavery's discussion from the previous comment sounds plausible to me.

**Comment by xavery** [comment]
I'd be willing to work on this, however there are some things which are still unresolved :
1. None of our other code does any advanced stuff with Unicode characters like querying their categories, switching normalization forms, finding out which ones influence the "visible" length of the string, and so on. I would thus be rather opposed to using ICU only for the purpose of checking UTF-8 validity (`tr_utf8_validate`) and extracting individual code points from an UTF-8 encoded string (that's really what `ConvertUTF8toUTF32` and `ConvertUTF32toUTF8` are used for in `variant-json.c`).
2. Unfortunately, there seems to be a weird shortage of freely available low-level encoding processing functions like those found in `ConvertUTF.c`, but maybe I just haven't looked hard enough. Other projects which formerly used the file in question include :
 * Ghostscript, where it was referenced in [this issue](https://bugs.ghostscript.com/show_bug.cgi?id=697121) and fixed in [this commit](http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=273a133110838ee5702e7eb6409a853c598211b2) by essentially deleting the original files and reimplementing the needed functions. 
 * Unicode's own `netcdf` library ([issue link](https://github.com/Unidata/netcdf-c/issues/349)), which moved to using [utf8proc](https://github.com/JuliaStrings/utf8proc). From a quick glance, it appears that the library does have all that's currently needed, however I'd need to verify if `tr_utf8_validate` can be properly implemented in order to have the behaviour that the rest of our code expects.
 * `replxx` library ([issue link](https://github.com/AmokHuginnsson/replxx/issues/12)), which moved to using [utfcpp](https://github.com/nemtrif/utfcpp), which - as the name suggests - is a C++ library and thus not really usable in libtransmission core. However, it's Boost-licensed, so we could just take the parts we need and adapt them to C.
3. This is getting into the lawyer-ish territory of licencing, but since the conversion algorithms are publicly known anyway, any reimplementation of `ConvertUTF.c` is going to be strikingly similar to the code that's already in that file. How does one know that the new code hasn't "originated" from ConvertUTF.c and as such isn't "tainted" by ConvertUTF's licence?

All in all, seeing how a rather high-profile open source project (Ghostscript) has simply taken the code already in ConvertUTF and adapted it to their needs, I don't see any reason why we couldn't take that route as well.

Please feel free to share your thoughts.

**Comment by ckerr** [comment]
https://github.com/ww898/utf-cpp and https://github.com/rmawatson/utf might also bear looking at

**Comment by ckerr** [comment]
I have only given it a quick look, but https://github.com/robhz786/strf looks very attractive to me. Our it appears to have utf8/32 support, and in addition our printf() calls are using ~4% of overhead, mostly due to json / benc serialization. The std:: replacement, `std::to_chars()` still has spotty support on older systems (e.g. std::chars_format isn't fully available even on Ubuntu 20.04) so `strf` might be a double win.

**Comment by ckerr** [comment]
Fixed by #2251
