### ISSUE TITLE
transmission - move to completed folder instead of copy.

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#6124]
### Discussed in https://github.com/transmission/transmission/discussions/6122

<div type='discussions-op-text'>

<sup>Originally posted by **josh-aliencode** October 17, 2023</sup>
Is there a way to configure transmission to move the downloaded torrent to the complete folder? -- instead of copying and removing the original? i wish there to be less delay since i use the same disk.</div>

**Comment by ckerr** [comment]
There are all kinds of edge cases, e.g. what happens when you have torrents that have the same top-level folder name.

Regardless, `tr_torrent_files::move()` _does_ call `tr_file_move()` which does try to use `rename()` on POSIX and `MoveFileExW()` on Windows, so it shouldn't require an actual file _copy_ when the destination is on the same filesystem.

So I'm not aware of any bug in the code right now but if someone has an example on how to trigger one please LMK.
