### ISSUE TITLE
`transmission-show` ignores 0 byte files

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#6190]
### What is the issue?

As the title suggests.

This issue is closely-related to #5112, but different.

### Which application of Transmission?

None

### Which version of Transmission?

4.1.0-dev (1c18737)

**Comment by Coeur** [comment]
When 100% of files are 0 bytes, then transmission-create crashes:
```
➜  Debug touch foobar.txt
➜  Debug ./transmission-create foobar.txt 
WARNING: no trackers specified
Creating torrent "/Users/User/Library/Developer/Xcode/DerivedData/Transmission-glecyzgymnuwedesedmretnukpnm/Build/Products/Debug/foobar.txt.torrent"
2023-11-02 05:50:02.489 transmission-create[48500:1788434] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'assertion failed: total_size != 0 (/Users/User/Development/transmission/libtransmission/makemeta.cc:366)'
```
https://github.com/transmission/transmission/blob/7d1a32c4719f0b54ede1a2046c2342608c9bbb35/libtransmission/makemeta.cc#L366C8-L366C23

When only a subset of files are 0 bytes:
```
mkdir foo
:> foo/bar.txt
echo "hello" > foo/bar2.txt
./transmission-create foo
./transmission-show foo.torrent
```
Then bar.txt is not listed because of:
https://github.com/transmission/transmission/blob/7d1a32c4719f0b54ede1a2046c2342608c9bbb35/libtransmission/torrent-metainfo.cc#L464-L467
