### ISSUE TITLE
Dark Mode Not Working?

### ISSUE THREAD

**Issue by wisnoskij** [transmission/transmission#6417]
### What is the issue?

Windows 11 Pro x64
V: 4.0.5 (a6fe2a64aa)

The website shows a dark mode in most of the screenshots.
The app does not seem to respect my system theme or supply a setting to set it manually.

Am I doing something wrong?

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by mikedld** [comment]
See #920. Short answer: [QTBUG-72028](https://bugreports.qt.io/browse/QTBUG-72028) is "fixed" as of Qt 6.5 (current `main` builds, and future 4.1.x release, are using Qt 6.6 on Windows) but Vista style still doesn't support dark mode out of the box. Other styles, in particular Fusion, should work, so installing a `main` build (e.g. pick the most recent one from https://github.com/transmission/transmission/actions?query=branch%3Amain+is%3Asuccess+event%3Apush; note those are development builds and so may be unstable) and running as `transmission-qt.exe -style fusion` (or adding `QT_STYLE_OVERRIDE=fusion` to user/system environment variables) should do the trick. There're no plans to add any explicit support for dark theme (e.g. custom palette and the like) to Qt client itself.

**Comment by maplefujian** [comment]
> See #920. Short answer: [QTBUG-72028](https://bugreports.qt.io/browse/QTBUG-72028) is "fixed" as of Qt 6.5 (current `main` builds, and future 4.1.x release, are using Qt 6.6 on Windows) but Vista style still doesn't support dark mode out of the box. Other styles, in particular Fusion, should work, so installing a `main` build (e.g. pick the most recent one from https://github.com/transmission/transmission/actions?query=branch%3Amain+is%3Asuccess+event%3Apush; note those are development builds and so may be unstable) and running as `transmission-qt.exe -style fusion` (or adding `QT_STYLE_OVERRIDE=fusion` to user/system environment variables) should do the trick. There're no plans to add any explicit support for dark theme (e.g. custom palette and the like) to Qt client itself.
> 
> EDIT: Apart from maybe improving the icons so that they don't look like shit :)

Confusing for me, I need to use a side build? not the regular 4.0.5? Its hard to make dark mode work in windows 11?

**Comment by maplefujian** [comment]
Resource Allocation: Open-source projects often have limited resources in terms of developers and time. The team might prioritize other features or bug fixes over implementing a dedicated dark theme.

Complexity: Creating a dedicated dark theme is not just about changing background colors. It involves designing a coherent color palette that works well in all parts of the application, ensuring readability, and possibly creating new icons and graphics. This can be quite complex and time-consuming.

Qt Limitations: The Transmission client uses the Qt framework for its user interface. As noted in your reference to QTBUG-72028, certain styles in Qt, like Vista, don't support dark mode out of the box. Although Qt 6.5 and later versions have improved support, there might still be limitations or additional work required to fully implement a custom dark theme.

User Demand: The development team might perceive that the demand for a dedicated dark theme is not high enough to justify the investment of time and resources, especially if there are workarounds like using the Fusion style.

Maintainability: Any new feature adds to the complexity of the software and needs to be maintained. This includes ensuring the dark theme works with all future updates and is compatible across different operating systems and versions.

Focus on Core Functionality: Transmission is primarily a BitTorrent client, and its core functionality revolves around downloading and sharing files. The development team might choose to focus on these core features rather than the aesthetic aspects of the application.

Community Contributions: In open-source projects, sometimes features like a dark theme are implemented by community contributions rather than the core development team. If no contributors have taken up the task, it might remain unaddressed.
