### ISSUE TITLE
Windows 11 - 4.0.5 - No Dark Mode 

### ISSUE THREAD

**Issue by maplefujian** [transmission/transmission#6469]
### What is the issue?

Looking for the dark mode in windows 11 

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.5

**Comment by maplefujian** [comment]
Love the cleanness of the program. Appreciate any suggestions.

**Comment by GaryElshaw** [comment]
Please delete any images of copyrighted material, now.

**Comment by GaryElshaw** [comment]
More information about Windows and dark mode [here](https://github.com/transmission/transmission/issues/6417).

**Comment by maplefujian** [comment]
![Transmission](https://github.com/transmission/transmission/assets/74486207/08b53b44-33b6-4ebd-b425-0495eb28dedf)

**Comment by ckerr** [comment]
Looks like this might be a factor of the Qt version that 4.0.5 ships with, which is Qt 6.4.0.0.

According to https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5, dark mode support on Windows got some new attention in Qt 6.5

**Comment by ckerr** [comment]
@mikedld would it be possible / make sense to use Qt >= 6.5 in the next release?

**Comment by mikedld** [comment]
As was already explained in #6417, Qt's dark mode support currently only works for Fusion style out of the box, and Vista style (which is the default on Windows) doesn't support it (yet? they say Windows doesn't provide the needed palette information). Even with Fusion though, icons don't automatically adapt and so it doesn't look that good; not sure if #4376 would've helped (specifically on Windows, where there're no icon themes support). I also don't think forcing the use of Fusion style on our side is a good idea as it's a generic style that basically will look alien on almost any system; that's why I suggested the use of `-style` or `QT_STYLE_OVERRIDE` for those who want it.

Current `main` builds (and so the upcoming 4.1) already use Qt 6.6 (might bump it a few more times before the release): https://github.com/transmission/transmission/blob/5000edef0191e5dc4ea5b8dec37da11510a08c16/release/windows/build-qt6.ps1#L3

**Comment by maplefujian** [comment]
Thanks everyone I’ll try and understand this when I get home.  I’m my head it would seem easy just to have an option to have either dark or light mode.  I’ve got lots to learn before I understand :)

**Comment by mikedld** [comment]
> Would it make sense to have the version ( Vista. Name next to the 4.0.5 ) in the information page of the program?

Good piece of info to have when troubleshooting, but not sure about showing it in the about dialog. Maybe hidden behind a button/tab/shortcut (a-la Easter egg)...

**Comment by maplefujian** [comment]
> As was already explained in #6417, Qt's dark mode support currently only works for Fusion style out of the box, and Vista style (which is the default on Windows) doesn't support it (yet? they say Windows doesn't provide the needed palette information). Even with Fusion though, icons don't automatically adapt and so it doesn't look that good; not sure if #4376 would've helped (specifically on Windows, where there're no icon themes support). I also don't think forcing the use of Fusion style on our side is a good idea as it's a generic style that basically will look alien on almost any system; that's why I suggested the use of `-style` or `QT_STYLE_OVERRIDE` for those who want it.
> 
> Current `main` builds (and so the upcoming 4.1) already use Qt 6.6 (might bump it a few more times before the release):
> 
> https://github.com/transmission/transmission/blob/5000edef0191e5dc4ea5b8dec37da11510a08c16/release/windows/build-qt6.ps1#L3
