### ISSUE TITLE
Speed limit doesn't work at 0

### ISSUE THREAD

**Issue by yunruse** [transmission/transmission#6552]
### What is the issue?

I'm using a script to enable Speed Limit on battery, but the setting to limit upload (and download) speed does not work when set to 0 – it assumes it is equivalent to an empty string, i.e. the limit is not applied.

While a fairly reasonable UI assumption, for battery longevity I'd really like to be able to completely disable upload on Speed Limit; setting it to zero, at least as it is for me now, does not seem to operate as it implies

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by Pentaphon** [comment]
> for battery longevity I'd really like to be able to completely disable upload on Speed Limit

This seems pretty counterproductive for the greater torrenting community and I don't think anybody should be able to disable uploading on any torrent client, for whatever reason.

**Comment by Yohmi** [comment]
I think there might be too many user cases to consider speed limit 0 as a negative thing. I know I use it because my hard drives make such a huge noise it prevents me from sleeping, so I scheduled a downtime for a part of the night. Not being able to do so would require me to manually pause and resume, which will result in many times not putting things back on in the morning (I know, because I tried, for months). The other solution would be to buy a bigger apartment, but I don't think it's part of the next Transmission milestone. I also tried to use macOS' Automator to automate the pause/resume as a calendar alarm, but it breaks after a few days. I also use that setting when I need to have the full activity of my disks available for a short amount of time, instead of pausing and reannouncing which can take a long time or create flood. 
Ultimately, not sure it's anyone's role to judge how one does torrenting giving his constrains. 

On my side though, I observed some occurrences when the limit set to 0 was malfunctionning, but most of the time it works (macOS version).

**Comment by yunruse** [comment]
> This seems pretty counterproductive for the greater torrenting community and I don't think anybody should be able to disable uploading on any torrent client, for whatever reason.

Why not? It's not like the user can't simply quit the application – or worse, delete torrents as soon as they download. Plenty of casual users do exactly that. Speed Limit is for people who want to fit their usage into a workflow, and helps benefit seeding.

I seeded to a ratio of 11 on a laptop, which helped shred its battery capacity to 40%. I now have a script quit Transmission when on battery — obviously I won't remember to reopen every time I connect to power, so uploading will suffer. I'd prefer to be able to just toggle Speed Limit.

**Comment by stevenengler** [comment]
If the intention is to not allow a limit of 0, this value should be made into an error instead of being ignored. From the issue description, currently a limit of 0 means "unlimited", which sounds like a bug to me.

**Comment by tearfur** [comment]
Although it is not by any conscious design choice, the behaviour described by the author is how Transmission originally worked, and it is now back to how it was in the latest dev commits.

**Comment by burner1024** [comment]
Is this in 4.0.6? Sorry, can't find the related commit.

**Comment by yunruse** [comment]
@burner1024 tested; no change to the behaviour in 4.0.6.

I just sort of patched a weird job to pause seeding torrents when I'm on battery using `transmission_rpc`. If you `pip install battery` the following is a pretty decent cronjob:
```
#! /usr/bin/env python3.12
import battery, transmission_rpc
c = transmission_rpc.Client()
do_seed = not battery.is_discharging()
f = c.start_torrent if do_seed else c.stop_torrent
ts = [t.id for t in c.get_torrents() if t.progress == 100]
f(ts)
```
It's worked without fail over the past half a year and keeps a tidy harmony to help foster both seeding and battery life; you could also use e.g. `do_seed = battery.percent() > 20` if that helps.

**Comment by tearfur** [comment]
IIRC 0 speed limit was "broken" in `4.0.5` and restored in a commit that isn't in any releases yet, but I forgot which commit it was.

Here you can see the behaviour restored in the lastest dev commit 1b57c294be08a21fbe42c5d01aed99b4c6fae67b:

![0](https://github.com/user-attachments/assets/c7e8d3f7-fde2-4be4-b175-cd3dc61e2b4a)

**Comment by burner1024** [comment]
I see, thanks @yunruse and @tearfur.
My use case is that I want to set up a node without any upload nor download, just serving as hole puncher helper for a rare torrent.
I'll guess I'll have to wait then.
