### ISSUE TITLE
sanitizer-tests CI has started failing in PRs

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#6697]
### What is the issue?

Not sure why, but the sanitizer-tests CI are crashing every time they try to run `libtransmission-test`. It's working for me on the same architecture + compiler. Seems to have worked recently, e.g. with the last commit from @mikedld for #6689 ([log](https://github.com/transmission/transmission/actions/runs/8265658989/job/22611849601)) but is failing in several unrelated PRs right now.

So the first likely answer is something has changed in either our CI recently or in GitHub's runners in the last couple of days, or even in the packages installed on GitHub's Ubuntu 22.04 images?

### Which application of Transmission?

None

**Comment by ckerr** [comment]
one difference from the successful log and the failures in PRs:

```diff
-   "name": "GitHub Actions 3",
+  "name": "GitHub Actions 4",
```

No idea if this is the cause or not; just leaving breadcrumbs

**Comment by ckerr** [comment]
both are using clang_1%3a14.0-55~exp2_amd64

**Comment by Coeur** [comment]
For instance, here is a failure (showing "Exception: SegFault" in 95 tests):
https://github.com/transmission/transmission/actions/runs/8291681790/job/22691897454

Which we want to compare to a success:
https://github.com/transmission/transmission/actions/runs/8265658989/job/22611849601

**Comment by Coeur** [comment]
Here are the diffs I could find so far:

In the success case:
>-- Performing Test clang_c_has_wexit_time_destructors
-- Performing Test clang_c_has_wexit_time_destructors - Success
-- Performing Test clang_cxx_has_wexit_time_destructors
-- Performing Test clang_cxx_has_wexit_time_destructors - Success

In the segfault case, those lines are missing (despite being both on Clang 14.0.0 and 3.22.1-1ubuntu1.22.04.2).

The rest is pretty much the same to me.

---

Just, due to the nature of the issue, I would speculate that it's related to the CMAKE_CXX_FLAGS or CMAKE_C_FLAGS:
https://github.com/transmission/transmission/blob/edc59ba5d8edfb6016fad3e2da2783ef3ab0bfd3/.github/workflows/actions.yml#L162

**Comment by Coeur** [comment]
Well, to me it seems unrelated to Transmission, since reverting the project to 10 days ago also causes a segfault:
https://github.com/transmission/transmission/pull/6701

So there may be an issue in GoogleTest? I'll attempt to bump it.

**Comment by Coeur** [comment]
OK, I found a workaround: #6703

**Comment by ckerr** [comment]
@Coeur nice investigation, ty!

We may want to revisit this once GitHub bumps to Ubuntu 24.05 in a month or two, but running on macOS as an interim fix WFM
