### ISSUE TITLE
Speed limits and extended limiting not working on v4.0+

### ISSUE THREAD

**Issue by Omeliax** [transmission/transmission#6736]
### What is the issue?

Hello! In version 4.0.5, the speed limit does not work, for example, you put a turtle, having previously set the necessary limits, but the speed remains unlimited and the position of the turtle is also not saved, when the client starts, the turtle button is also not saved

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment]
@Omeliax Could you make the title more meaningful?

Hmmm ... these issues don't happen on 4.0.4? The not saving status part might be a permission issue on the filesystem.

**Comment by Omeliax** [comment]
> @Omeliax Не могли бы вы сделать название более осмысленным?
> 
> Хммм... эти проблемы не возникают в версии 4.0.4? Часть состояния "Не сохраняется" может быть проблемой с разрешениями в файловой системе.

I don't understand what the title means. 
Yes, version 4.0.4 has the same problem, speed control does not work and extended limiting does not work, now version 3.0.0 is installed, everything works fine

**Comment by killemov** [comment]
@Omeliax With title I meant "Transmission v 4.0.5" which is very non-descriptive. You could change it to "Speed limits not working on V4.0+" for example.

**Comment by Tharn** [comment]
Can confirm on 4.0.5 with Windows transmission-daemon. Setting a limit of 3MB/s I get consistent speeds above 4MB/s.

**Comment by epitonium** [comment]
I confirm that neither "Global bandwidth limit > Download rate" nor "Speed Limit mode > Download rate" is working as expected. MacOS Venture 13.6, Transmission 4.0.5.
![CleanShot 2024-03-30 at 21 28 35@2x](https://github.com/transmission/transmission/assets/6273817/4c39e649-2131-43b8-9418-600f74f10163)

**Comment by Tharn** [comment]
The speed limit does seem to work but it overshoots by about 1/3rd, maybe because of overhead or who knows.

**Comment by Omeliax** [comment]
I also noticed that when you turn on the speed limit (turtles) and restart the application, the position of the speed limit (turtles) is not saved

**Comment by killemov** [comment]
That is too much to be overhead, a rounding error or a KB <-> KiB conversion or all of the above. Also next up by a power of two does not seem to fit here.

**Comment by jbarlov** [comment]
Yeah same here and both times I've said it the issue has been said "to be repaired". Obviously not. Thanks for others pointing it out as well! :)

Chews up all of bandwidth regardless of limit / turtle.

**Comment by tessus** [comment]
I can confirm. I'm using the transmission daemon on Linux and the web interface to connect to it. Setting the speed limit or the temporary speed limit does nothing.

This is a serious issue, because it often happens that transmission uses all my bandwidth. I hope the team will release a hot fix asap. Currently I have to stop the daemon during the day.

**Comment by tearfur** [comment]
@jbarlov:

> Makes one slightly angry that it was just brushed away by staff and made one feel like an idiot

1. None of the people here are "staff", we are volunteers, we aren't paid or employed. Please put down the hostile attitude, I don't want any people that were doing good work just flip the table and leave because of it.
2. I'm not trying to brush it away or make a fool out of anyone. I wrote the fix for your problem more than 5 months ago now. It's just waiting for a new release to include it.

Throwing shit at me does not help one bit because **I have no control over the release schedule whatsoever**. I may be a "Member" of the Transmission org, but the access rights I have isn't much different from any other contributor.

It is as frustrating for me and other members to see fixes for major issues stay unreleased for months on end being the norm here. If you look around, people (including myself) have been nagging the core developers to make a new release for some months now.

**Comment by tearfur** [comment]
For all others seeing this issue, it is reporting 2 separate problems:

1. The speed limit is overshooting. This was fixed by #6416.
2. The position of the turtle is not being saved. This was fixed by #6483.

We "just" need a new release. I have no idea when either...

**Comment by tearfur** [comment]
Closing this issue now. If anyone disagrees, feel free to speak up.

**Comment by pan-szymanowski** [comment]
My version 4.1.0-beta.2. Debian 13. Speed limit still does not work
Workaround.
1. Stop tansmission daemon.
2. In config file /etc/transmission-daemon/settings.json set 
**"utp-enabled": false**
3. Start transmission daemon.
4. Enjoy

**Comment by tearfur** [comment]
@pan-szymanowski You are probably experiencing #7491 instead of this issue.

**Comment by pan-szymanowski** [comment]
> [@pan-szymanowski](https://github.com/pan-szymanowski) You are probably experiencing [#7491](https://github.com/transmission/transmission/issues/7491) instead of this issue.

Right. Too many similar threads. Sorry.
