### ISSUE TITLE
auth issue

### ISSUE THREAD

**Issue by Mantou1233** [transmission/transmission#6755]
### What is the issue?

![image](https://github.com/transmission/transmission/assets/74487898/c6435e87-a982-4ce9-99f5-2eff49970490)
it kept saying auth wrong after i rebooted the server. what should i do?

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment]
Weirdly the `--no-auth` flag appears not to be functional. OR did you start one instance locally and used environment variables to connect to another instance.

**Comment by tearfur** [comment]
When no URL is specified, `transmission-remote` will always default to `localhost:9091`.

Pretty sure the daemon instance you started by `transmission-daemon --no-auth` either failed to bind to port `9091` because something else is occupying that port, or it isn't running on `9091` in the first place.
