### ISSUE TITLE
[suggestion] add different colors for progress bar if nothing loaded since 10mn, 1h, 24h..

### ISSUE THREAD

**Issue by renanyoy** [transmission/transmission#6763]
### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5

**Comment by Pentaphon** [comment]
Not feasible. There's too few colors for that many time changes and people already agreed that progress bar colors should match the status change colors on Mac for downloading, seeding, etc on https://github.com/transmission/transmission/issues/5648

If we ever get a columns mode in the compact UI I can see this being a "last activity" column category but otherwise,  we should not change the colors for anything other than status.

**Comment by renanyoy** [comment]
maybe adding a sorting system so: on progress, alphabetical order, last time download updated, etc..

**Comment by Pentaphon** [comment]
> maybe add a sorting system

We already have one...

![transmission-bittorrent-kde-qt-2](https://github.com/transmission/transmission/assets/49374058/b9a085c4-e5a7-4768-bbf3-fff943aef13d)

**Comment by aymey** [comment]
I dont think its necessary but we could do something as simple as darkening the base colour in relation to the completion percentage. That way each colour maintains its significance (like blue is downloading, green is seeding, etc.) but you still her a visual indication of its progress.

**Comment by Pentaphon** [comment]
@aymey we are going in that direction in https://github.com/transmission/transmission/issues/5648

We can probably close this issue since it is unfeasible. Too many colors for the times proposed by OP.
