### ISSUE TITLE
Transmission development is fading out

### ISSUE THREAD

**Issue by tiagoboldt** [transmission/transmission#701]
I've just went through the list of commits, issues and PRs and observed that there's little activity from lead devs in transmission repository right now. 

Given that there is no process for the community to allow transmission to move forward organically, the project's relevance will fade and people will move to other bittorrent clients. 

I would suggest that the project leaders made a call for volunteers to ensure this doesn't happen, as transmission has been an essential piece of software for most of us for years. And there are definitely interested parties to keep things moving as we're seeing private extensions from it being published by individual developers that can't get their changes into transmission. That ranges from redesigned web ui updates to iOS app clients. 

Hope this is received with the right mindset so that we can see transmission in our machines for the next decade as well.

**Comment by tiagoboldt** [comment]
CCing @mikedld @ckerr @jre @titer @jordanl @JohnClay @livings124

**Comment by Riotous** [comment]
@tiagoboldt Moving to github definitely helped but yes we need new blood to contribute to the project. 

I think there's other factors that we need to address as well, such as:

1) The lack of a stable Windows port. We need the current Windows port to be as rock solid as the Mac and Linux ports are, so that we can attract more users who need a lightweight alternative to uTorrent. Window is still the biggest platform right now and prioritizing the Windows port first in order to deliver a solid, stable client to Windows users is the best way to attract the largest number of new users as well as potential contributors. 

2) The lack of basic features that other clients have had for years. We should be able to restrict the number of upload slots from the UI, make torrent labels, and simply enter the infohash of a torrent to find it on the DHT network, for example. These little features add to to make Transmission as useful as the other clients are right now.

3) The multiwindow UI. This is our biggest hurdle right now since many people are turned off by it when they are used to working with a single-window, paned UI when managing torrents. I don't see this changing, however, so we have to find other ways to make Transmission more useful while keeping the current UI, like adding more commands to the context menu when right clicking a torrent, adding more information to the torrent properties page, and adding a few more vital options to the preferences page.

Once we address all these things, Transmission will flourish.

**Comment by tiagoboldt** [comment]
While I do agree that those items are important, I think that it can be address at any time by an healthy community. The issue that I see is around 50 open pull requests by people eager to contribute with little to no feedback. That not only disregards valuable contributions, but also demoralizes the community from contributing further. 

From my point of view, the most immediate change needed it to provide additional people with merge permissions to master, so that they can start reviewing those PRs and get the project going at least with organic contributions. By seeing activity and their work merged, people will be motivated to contribute further and the project will thrive.

**Comment by DevilDimon** [comment]
Is any of the project maintainers going to address the issue?

**Comment by Riotous** [comment]
@DevilDimon I don't think anything is going to happen until somebody steps up to push the project forward with active maintenance. There's a lot of work to be done and the leadership just isn't there right now. 

I personally think @mikedld should delegate somebody with enough passion for the project with the permissions needed to keep the project going when he doesn't have any time to work on it.

**Comment by tiagoboldt** [comment]
@mikedld recently committed to the project. It seams he's the only one with access who's sometimes coming around. Does anyone have access to him? It would be really important to get his input in this thread. For the sake for having transmission living on, if you know someone who knows a guy who can get his attention, please do take action.

**Comment by Nutomic** [comment]
@tiagoboldt This seems to be his website, and there is an email address. You could try to contact him that way: http://mikedld.com/

**Comment by Riotous** [comment]
@tiagoboldt I think the best course of action is to add at least one highly motivated maintainer who has plenty of time to devote to the project so we get new releases coming out at a more regular pace.

**Comment by tiagoboldt** [comment]
@mikedld any chance you can chime in here?

**Comment by svanstrom** [comment]
I came to github now just to check on the health of this project.

My take on the situation right now is that the active (and could be active) developers need a community manager to basically shield them from the load of dealing with us well-meaning users.

That way us users won't get cranky (which would make the devs cranky), and it would take some stress of the devs.

However, just calling for that someone should do that won't really solve anything; so it's mostly a question about whether or not there exists someone that sort of will take upon themselves to fight their way to the attention needed to officially get the job of doing that. Perhaps @tiagoboldt ?

**Comment by tiagoboldt** [comment]
A community manager filtering all the noise might be a good idea for a project the size of transmission. The need must be recognized and pursued by the core team though. My observation here is that unfortunately, they are not that open to community input right now. 

Addressing my potential collaboration, I'm wrapping up my Ph.D. this year, so as much as I would like, I'll have zero time for additional projects.

**Comment by svanstrom** [comment]
I won't try to convince anyone to do what I clearly won't do myself; but just to put some perspective on what the responsibilities of a community manager could be at a project…

Essentially the CM could act as a shield to take the heat of the developers, and at the same time somewhat placate the community by making sure that they know that they are being seen; and that work is being done.

This could be as little as stating that the CM is doing this with very little time, and then publish a weekly update as short as a tweet. We're talking maybe 30-60 minutes on the weekend reading through issues/comments/whatever where users are able to comment, hand out some emoji-reactions, and give a few "this issue is [this] important, thank you for the comment, and I've noted the continuing interest from the community"-replies; and then prepare that tweet-length update to publish Monday morning.

It makes the community a bit happier, and the devs don't have to feel like they want to stay away because otherwise they have to handle angry people. It can be extremely unthankful work; but it really can do wonders for keeping a community from spiralling into toxicity.

**Comment by ckerr** [comment]
For the short term, working through the outstanding PRs will do the most good. It will show signs of life in the project and, I hope, help encourage contributors to submit more PRs.

Past that, there are about a dozen topics in this issue and IMO the feature requests (e.g. better windows support, manual upload slot control, multiwindow UI) should be discussed in their own issues rather than here. Multitopic issues are always difficult to manage.

**Comment by andrasfuchs** [comment]
Could [the GitHub Sponsors program](https://github.com/sponsors) help resurrect the development of Transmission? Would it make sense to connect all maintainers and tell them about this new opportunity?

**Comment by alimony** [comment]
@tiagoboldt Did you ever have any luck contacting @mikedld via email?

**Comment by tiagoboldt** [comment]
@alimony I never got a response back.

**Comment by alimony** [comment]
Trying another ping at @ckerr @jre @titer @jordanl @JohnClay @livings124

**Comment by elvey** [comment]
1. @mikedld Is clearly active _on GitHub_, having made commits (to other projects) 6 days last week, every month an on two out of 3 days of the past year, so I think we can say he's clearly abandoned the project. Any other active members? Assuming not, **I think we can conclude that leadership and decision-making authority falls to @ckerr**.  Let's support him and his proposal. I do. I agree with him and OP re. feature requests.  

2. Do any active, previously successful PRers want to be members?   Should we ping some?  Including asking, "Would the [above-mentioned]( https://github.com/transmission/transmission/issues/701#issuecomment-518984702) GitHub Sponsors program motivate you?" (I'm guessing BT has critical security patches needed by now...)

3. He asks for specific assistance: "working through the outstanding PRs will do the most good."  I'm assuming that's something a member would need to do, hence my number two, above.  Or maybe I don't understand what "working through" means.  Anyone?  Maybe what's needed is for the folks with PRs to pair up or be paired up by a member, and agree to review each others PRs? 

(Sorry, I don't see a commitment to make that I'm confident I could fulfill.)

**Comment by svanstrom** [comment]
I recently gave the bt-server a lot more bandwidth, and that's when transmission showed itself it to have to be replaced. With transmission I'm easily stuck at a 1/10th of the available upload speed simply because the upload slots are tied to people on slower connections.

No one has even properly addressed this year and a half old issue of development fading out… so… transmission is dead now. :(

**Comment by ckerr** [comment]
Closing this issue for the reasons mentioned above -- this is a multi-topic ticket and those are problematic to manage. Specific bugs or issues should each be re-reported in their own tickets.

In addition, the main topic -- "Transmission development is fading out" -- is not really a bug with a concrete endpoint where one can say "problem fixed." Is Transmission development more active than it was a year ago? Yes. But is it as active as it was a decade ago? No.

I've added a `good first issue` label to the issue tracker to try and pick out some low-hanging fruit for people who might want to dip their toes into the water and give Transmission development a try.
