### ISSUE TITLE
Disable or change keyboard shortcuts

### ISSUE THREAD

**Issue by dj-louw** [transmission/transmission#7071]
### What is the issue?

This is mostly a feature request or an ask for some advice. Not a bug.

On the web client, the keyboard shortcut for "verify local data" is bound to `CTRL` + `V`. On Windows (and possibly most Linux) machines, this is the OS bound shortcut for paste.

A common use case I have is copying magnet links from various sources, and then pasting them in the "add torrents" dialogue. When I hit `CTRL` + `V`, it forces a verify on the item I had selected /behind/ the dialogue, and does not paste the magnet link that I have in my clipboard. 

Personally I don't have much use for keyboard shortcuts in Transmission, and when I do, I most certainly don't want it to override a deeply embedded muscle memory developed over more than a decade. It would be nice to disable the shortcuts via the web ui, or at the least change them to something less aggravating.

Thanks!

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by Daniel6372** [comment]
This has already been fixed (https://github.com/transmission/transmission/pull/5318, https://github.com/transmission/transmission/pull/5381). The fix is present in versions 4.0.3 and higher.

However, I have found a related bug with the paste shortcut. In the 4.0.x builds it's set to `Control + Shift + V`, however this does not work, which I'm assuming has to do with this funny typo: https://github.com/transmission/transmission/blob/c4fddc82fecfb6a7a7c67cc86875ce9c985d0c29/web/src/transmission.js#L462

The above is not relevant to the main branch, as the modifiers have been removed for keyboard shortcuts: https://github.com/transmission/transmission/pull/5331

**Comment by killemov** [comment]
I have seen a fix `event_.shitKey` => `event_.shiftKey` come by somewhere. Probably waiting to get merged.
