### ISSUE TITLE
Privacy flag respected when outside of the info dict

### ISSUE THREAD

**Issue by Rauxon** [transmission/transmission#7302]
### What is the issue?

If the bencoded information for a torrent includes 'private=1' at the root level (not within the info dict), transmission will treat this as being a private torrent.  This behaviour is not what the [spec](http://bittorrent.org/beps/bep_0027.html) seems to say, and is different to other clients (tested on qBittorrent & Deluge)

This allows a public torrent to be changed to private without affecting the hash 

To replicate:

1. Download a torrent file from:  https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/
2. Use a bencode/bdecode library to add 'private=1' to the root dict
3. Add file to transmission, confirm the status:  Privacy:
Private to this tracker -- DHT and PEX disabled
4. Try adding the unedited torrent - it will not add, since it is the same hash.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.6

**Comment by killemov** [comment]
Your analysis appear to be correct. But are the torrents that have a `private=1` on root level then also not out of spec?

**Comment by proton-ab** [comment]
See https://github.com/transmission/transmission/pull/7111#issuecomment-2357031178 for more detailed analysis on how Transmission reads bencoded data currently

**Comment by userwiths** [comment]
Isn't that behavior caused by the first condition used here https://github.com/transmission/transmission/blob/59c1c1e83bc61470f0f62083c14667a648d0015f/libtransmission/torrent-metainfo.cc#L222
The second condition I believe is supposed to make sure we are reading from the `info` dictionary. Tested locally with the linked torrent and I see the expected behavior as described above (ignore if on root level, accept the flag from `info` level).

I'm opening a PR with proposed changes.
