### ISSUE TITLE
transmission-qt on Linux try to load translations from app executable directory but install translations into standard Qt translations directory

### ISSUE THREAD

**Issue by marguerite** [transmission/transmission#736]
Hi, 

For reference, my bug report on the openSUSE side: 

https://bugzilla.opensuse.org/show_bug.cgi?id=1111323

<pre>
qt/Application.cc
void
Application::loadTranslations ()
{ 
  const QStringList qtQmDirs = QStringList () <<
    QLibraryInfo::location (QLibraryInfo::TranslationsPath) <<
#ifdef TRANSLATIONS_DIR
    QString::fromUtf8 (TRANSLATIONS_DIR) <<
#endif
    (applicationDirPath () + QLatin1String ("/translations"));
  
  const QStringList appQmDirs = QStringList () <<
#ifdef TRANSLATIONS_DIR
    QString::fromUtf8 (TRANSLATIONS_DIR) <<
#endif
    (applicationDirPath () + QLatin1String ("/translations"));
  
  QString localeName = QLocale ().name ();
  
  if (!loadTranslation (myAppTranslator, MY_CONFIG_NAME, localeName, appQmDirs))
    { 
      localeName = QLatin1String ("en");
      loadTranslation (myAppTranslator, MY_CONFIG_NAME, localeName, appQmDirs);
    }
  
  if (loadTranslation (myQtTranslator, QLatin1String ("qt"), localeName, qtQmDirs))
    installTranslator (&myQtTranslator);
  installTranslator (&myAppTranslator);
}
</pre>

appQmDirs will be the application executable directory. and qtQmDirs will be the standard Qt translations directory plus the application executable directory. 

If transmission can't load local translation from appQmDirs, it will load English "translation" from appQmDirs, and then load translations for "qt" term from qtQmDirs as fallback.

That is perfect on Windows and OS X because they have application specific directory, where our transmission executable installs into. so Program Files/Transmission/translations make sense.

But on Linux, transmission executable will be installed to /usr/bin, and its translations will be installed to /usr/share/qt5/translations (I didn't modify the code for such locations, it's the standard behavior of qmake on Linux). So the above strategy will not work, because no downstream distributions will install translations into /usr/bin/translations because according to FSB /usr/bin belongs to executables only.

A simple fix could be:

<pre>
Index: transmission-2.94/qt/Application.cc
===================================================================
--- transmission-2.94.orig/qt/Application.cc
+++ transmission-2.94/qt/Application.cc
@@ -307,6 +307,7 @@ Application::loadTranslations ()
     (applicationDirPath () + QLatin1String ("/translations"));
 
   const QStringList appQmDirs = QStringList () <<
+    QLibraryInfo::location (QLibraryInfo::TranslationsPath) <<
 #ifdef TRANSLATIONS_DIR
     QString::fromUtf8 (TRANSLATIONS_DIR) <<
 #endif
</pre>

append the standard Qt translations directory to appQmDirs. it will be useless for Windows and OS X because such directory doesn't contain transmission translations, but it will benifit Linux.

Greetings

Marguerite

**Comment by mikedld** [comment]
`TRANSLATIONS_DIR` macro serves exactly that purpose on systems other than Windows and Mac: https://github.com/transmission/transmission/blob/d8e60ee44f4295935bd98bf741f85ed19f5a7dfb/qt/CMakeLists.txt#L233-L237

It's not defined in qt.pro (I guess one could pass it to qmake somehow), but then CMake is the preferred method to build Qt client (and all the rest of Transmission really) going forward. openSUSE spec file seems to still be using autotools and qmake to configure the build which is why there is a problem on this system.

Also, I personally think that using `QLibraryInfo::TranslationsPath` (which resolves to "/usr/share/qt5/translations" for me as well) to search for application-specific .qm files is wrong. You could notice that it's being used to initialize `qtQmDirs` since this directory indeed contains Qt translation files but application translation files, as far as I could tell looking at my Gentoo box, are usually installed into "/usr/share/\<program\>/..." (which is what we set `TRANSLATIONS_DIR` to in CMakeLists.txt as could be seen above):

```console
% find /usr/share -name '*.qm' | xargs -n1 dirname | uniq -c
     76 /usr/share/virtualbox/nls
     32 /usr/share/nextcloud/i18n
     37 /usr/share/sddm/translations
     36 /usr/share/keepassxc/translations
      2 /usr/share/qt5/translations
```

**Comment by mikedld** [comment]
`TRANSLATIONS_DIR` is set to a sensible value (e.g. "/usr/share/transmission/translations") when configuring with CMake and translation files are installed there, so there is no need in configuring it explicitly; you could still influence the value by passing `CMAKE_INSTALL_FULL_DATADIR` to CMake. Unless this does not satisfy someone, there is nothing to fix.

As I said before, autotools and qmake are generally deprecated. They will most likely be removed in one of upcoming releases. I tried keeping them in sync with all the recent changes in CMake configuration, but that's additional work that I don't want to have in the future so any issues with those systems won't be addressed in a timely fashion (or ever) unless it's something critical.

I don't use KDE and I'm not sure I'm looking in the right place but at least [kde-plasma/plasma-desktop package files](http://www.portagefilelist.de/site/query/listPackageFiles/?do&category=kde-plasma&package=plasma-desktop&version=5.12.7) don't incude any .qm files but instead have .mo.

The fallback to Qt translations is required for phrases used in Qt-provided dialogs unless we want to translate them ourselves. What happens if we don't fallback is that those dialogs (in full or in part) are displayed in English; things may have changed though and everything's dandy with recent Qt versions, but this would require testing.

**Comment by marguerite** [comment]
Sorry I made a false alarm. /usr/share/qt5/translations on my system now contains Qt translations and transmission translations only, no KDE stuff. Sorry!

**Comment by marguerite** [comment]
I'll at first switch the specfile to cmake and see if there's any problem then. thanks for the clarification.
