### ISSUE TITLE
Drop in systemd unit will not work to change user.

### ISSUE THREAD

**Issue by thibmaek** [transmission/transmission#75]
I tried using a systemd drop-in on Debian 8 to modify the user transmission-daemon runs as to my home user. Installed with `apt-get transmission-daemon` the daemon runs as debian-transmission by calling `/lib/systemd/system/transmission-daemon.service` which calls the older init.d script.

My drop in is located in `/etc/systemd/system/transmission-daemon.service.d/local.conf` and looks like:

```systemd
[Service]
User=pi
Group=pi
```

Reloading with `systemctl daemon-reload && systemctl restart transmission-daemon` does show the service as running with `systemctl status transmission-daemon` but the web interface can't be started and no significant errors are produced by transmission-daemons --log-error flag.

![screenshot 2016-11-02 17 57 00](https://cloud.githubusercontent.com/assets/6213695/19939179/2d2df79c-a128-11e6-8137-598278ebb1bb.png)

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.

Changing the user changes default (as you're not running the daemon with `-g` argument) configuration directory as well (see [this wiki page](//github.com/transmission/transmission/wiki/Configuration-Files) for details). This could mean that daemon is not using settings you think it does, including settings for RPC. Further help will depend on more information from you (like version of Transmission, content and location of settings.json, clarfication of "can't be started" etc.) and since there is no reason to treat your issues as an actual defect in Transmission software, forums are better suited for this.
