### ISSUE TITLE
Discussion: How to authenticate with Authorization HTTP header

### ISSUE THREAD

**Issue by rcdailey** [transmission/transmission#771]
I'm using NGINX as a reverse proxy for Transmission and I have it set up to authenticate with a different web application (specifically: Organizr). Because of this, I do not want authentication in Transmission to take effect unless using actual RPC (via `/rpc` URI). Here is how I currently have this configured in NGINX:

```
set $upstream_transmission http://transmission:9091;

location /transmission {
    auth_request /organizr/auth-0;
    proxy_pass $upstream_transmission;
    proxy_set_header Authorization "Basic dXNlcm5hbWU6cGFzc3dvcmQ=";
    proxy_pass_header Authorization;
}

location /transmission/rpc {
    proxy_pass $upstream_transmission;
}
```

This doesn't seem to work 100% though. For example, on the Chrome browser on Android, I am still prompted for authorization by Transmission.

So my question is: Is the Authorization header supported by Transmission? If not, what is the appropriate way to disable RPC authentication selectively for all endpoints except `/rpc`?

**Comment by LaserEyess** [comment]
@rcdailey I just went through the code for rpc and I think I found your issue. Can you try: 

`
proxy_set_header Authorization "basic dXNlcm5hbWU6cGFzc3dvcmQ=";`

(Notice the lowercase 'b' in basic!)

The issue is probably [this line](https://github.com/transmission/transmission/blob/master/libtransmission/rpc-server.c#L651) returning false because it's comparing case.

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com) for support.
