### ISSUE TITLE
don't store data files in XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by L0ric0** [transmission/transmission#798]
transmission should store changing and not configuration related data per default in $XDG_CACHE_HOME (~/.local by default) and not in $XDG_CONFIG_HOME. So for example move the resume folder or the dht.dat or the stats.json to $XDG_CACHE_HOME

**Comment by ckerr** [comment]
Caching `.resume` files would be a terrible mistake. For example when using Transmission's rename-torrent-files feature that mapping is stored in the `.resume` files, so permaseeders would lose that information when the cache is blown away and lose their ability to seed.

Likewise, the whole purpose of `stats.json` is to show the user information about their cumulative use of Transmission over time. Storing this in a cache directory would defeat that purpose.

Arguably the `torrents`, `resume`, and `stats.json` files could go into `$XDG_DATA_HOME` but it's not clear to me what practical benefits would come from this change?

**Comment by L0ric0** [comment]
you can easily use git or other version control tools on your config dir

**Comment by ckerr** [comment]
That's a fair point; I like that use case.

Still, it seems like a pretty slim edge case because I suspect few people would do that. If someone submits a PR to transition `torrents/`, `resume/`, and `stats.json` to `$XDG_DATA_HOME`, it had better be bulletproof otherwise we're going to break a lot of users' setups for that slim edge case.

**Comment by L0ric0** [comment]
@mikedld yes i do but I think it is cleaner to use the proper directory's.
