### ISSUE TITLE
the multi threads didn't work

### ISSUE THREAD

**Issue by ImMrMa** [transmission/transmission#812]
Hi man,I compile the tr from source code,and i find that when i download many bt torrents.It only use 1 cpu(I have 6).
When I use the old version from apt, I  find the multi threads work.
My computer is arm64 rk3399 with armbian(base on debian).
where is the problem?
the old version in apt is 2.9.2
I compile in 2.9.4

**Comment by xavery** [comment]
Transmission isn't necessarily massively multithreaded. What exactly do you mean and how did you observe the effect?

**Comment by ImMrMa** [comment]
Beacuse it's a arm linux system,and I just use htop and find it only use one core but the tr from apt use multi threads and speed is high




| |
haha
邮箱：ma870587394@163.com
|

Signature is customized by Netease Mail Master

On 01/30/2019 18:40, Daniel Kamil Kozar wrote:

Transmission isn't necessarily massively multithreaded. What exactly do you mean and how did you observe the effect?

**Comment by ckerr** [comment]
Closing this issue as invalid since Transmission's threading system didn't change between 2.92 and 2.94 so I don't think the behavior described in https://github.com/transmission/transmission/issues/812#issuecomment-458897454 can really be fixed in Transmission's code.

As an aside, nearly all of Transmission's work is either network- or disk- bound, so extra processing generally doesn't help that much.
