### ISSUE TITLE
Use of hardening flags

### ISSUE THREAD

**Issue by Avamander** [transmission/transmission#855]
Hi,

I just wanted to ask, are there any plans on using GCC/Clang hardening flags such as `-fstack-clash-protection`, `-D_FORTIFY_SOURCE=2`, `-fstack-protector-strong`? This would help to mitigate possible security issues in Transmission or the libraries it statically compiles in.

**Comment by mikedld** [comment]
We may consider this for macOS and Windows builds where we provide the binaries ourselves. Otherwise it's up to the particular package maintainer and/or general OS/distro guidelines whether to pass those flags to the build system or not, I don't think we want to force people to use them (it's always easier and more convenient to add them than to remove since the latter usually requires a patch). We may consider adding a configuration option that adds those flags though, but their set may be hard to manage.

**Comment by Avamander** [comment]
On a slightly related topic, could `-flto` be enabled for builds? Or is that too left to the distro maintainers? It would help to make things even more lightweight.

**Comment by mikedld** [comment]
In my experience, LTO slows down link phase (which is to be expected) and negatively impacts debug information quality, so I wouldn't enable it in official builds. Package maintainers are free to do whatever they want ;)
