### ISSUE TITLE
Transmission should auto-enable (or allow to enable) DHT/PEX/LPD after a certain torrent age in the case of private torrents

### ISSUE THREAD

**Issue by Avamander** [transmission/transmission#860]
As the title says, Transmission should auto-enable or allow users to enable DHT/PEX/LPD after a certain torrent age (something between five to ten years) and if the tracker is down in the case of private torrents.

This suggestion would fix the enormous torrent-rot I've encountered with really old torrents, there would be zero harm to any active private trackers, yet every single one of those (old) torrents wouldn't instantly die if the tracker does.

What do you think?

**Comment by LaserEyess** [comment]
I think this is a bad idea for two reasons. First, it will most certainly be misused/abused/accidentally turned on by users and they could (and most likely will) get banned for 'cheating'. Even if you assume perfect users, the staff for private trackers most likely will not whitelist a client that allows you to turn on DHT for a private torrent, because of the concerns above. So all you'd be doing is removing a great client from the whitelist of many sites. 

Second, this would only work for transmission clients, and most importantly transmission clients that are updated to the latest version. Windows users and certain linux distros (debian, etc.) will not be running that version for years to come since they never update, so it would not help with the torrent rot as much as it could. A better idea would be to re-upload the data to a new tracker, public or private, because even with DHT turned on they'll still need a torrent file to get the metadata from anyway.

So not only would this most likely get transmission banned, it would not actually solve the issue you're talking about. Loss of data to the void sucks, but this is not your solution.

**Comment by Avamander** [comment]
> First, it will most certainly be misused/abused/accidentally turned on by users and they could (and most likely will) get banned for 'cheating'.

Given that with the suggestion you would have to block both the tracker and change the clock five to ten years I don't think a regular person could cheat (more than one could with a modded client) without messing up the rest, such as web browsing. It's really trivial to modify pretty much every open-source client to ignore the DRM currently irrationally enforced, and use DHT/PEX/LSD(LPD), this suggestion on its own would not allow more people to "cheat" than they currently can.

> Windows users and certain linux distros (debian, etc.) will not be running that version for years to come since they never update, so it would not help with the torrent rot as much as it could. 

The update will propagate to those computers eventually, Transmission doesn't have to be the only client that has this feature.

> Even if you assume perfect users, the staff for private trackers most likely will not whitelist a client that allows you to turn on DHT for a private torrent, because of the concerns above. 

If some private tracker staff is so irrational then there's really no loss here, those users are better of using a private tracker that doesn't arbitrarily limit what clients they should use.

> A better idea would be to re-upload the data to a new tracker, public or private, because even with DHT turned on they'll still need a torrent file to get the metadata from anyway.

The goal is to have a replacement if the single tracker private trackers usually supply with their torrents goes down, not to make private torrents public.

**Comment by LaserEyess** [comment]
It's not irrational to ban transmission if it allows DHT with with old private torrents. Consider the scenario of a tracker that has been running for 10+ years with a torrent that's 10+ years old. The tracker goes down one day for maintenance, DHT suddenly activates in transmission. That is not something any staff would accept. Sure that's only possible through what you just proposed, and you could add more checks and assurances that the tracker is actually dead, but the bottom line is there is no guarantee. All the complex logic in the world won't help you if it's tripped one day and some people get DHT on their private torrents. 

The propagation of these changes also matters, are you going to convince other clients to add this? Most won't add this 'feature' unless they were forced to by the spec. What about the infamous utorrent 2.2.1, what most windows users prefer? They will never update their clients, they're basically allergic to it. I understand what you're trying to accomplish but this is not really going to help. It requires changes in all clients and acceptance by private tracker staff. Your first step would be getting this into a BEP, then demonstrating a proof of concept and helping implement it on major clients. Then you'd have to convince tracker staff that it's safe and will still work with their anti-cheat and anti peer leak algorithms. There is no sense it putting this in transmission first, it will accomplish nothing.

**Comment by Avamander** [comment]
> Consider the scenario of a tracker that has been running for 10+ years with a torrent that's 10+ years old. The tracker goes down one day for maintenance, DHT suddenly activates in transmission. 

Fair enough, this could be an issue. Though I don't think a single tracker is offline in maintenance for more than a week or even a month. adding that check is a trivial increase in the complexity of the check but yet provides a nice grace time for private trackers, the chances that a torrent is older than ten(/five) years and that the single tracker has been offline for a week both simultaneously is pretty much zero.

> All the complex logic in the world won't help you if it's tripped one day and some people get DHT on their private torrents.

And the worst that happens is that people having the torrent file can download the torrent and those who don't, can't?

> The propagation of these changes also matters, are you going to convince other clients to add this? 

I'll attempt. The fact that a "feature" like this exists in all common clients is not a reason why changing the behavior a bit should be impossible.

**Comment by AngelFalse** [comment]
I suppose that, private torrents are not **supposed** to be downloaded by such ways.(Though that DO help the users in some way...)

http://wiki.bitcomet.com/private_torrents

>Most private trackers operate a forced ratio tracking system where a user is required to have a minimum amount of upload and are often required to seed their torrents for a minimum time limit to maintain their membership.

If you use DHT and such to discover peers, it's cheating, with no doubt. The biggest problem is that the private trackers are always supposed to be overseeing all the bt client, and downloading/uploading without being seen is quite a severe damage to the pt network as a whole.

Rules are the most important thing in the pt network. All clients' upload and download action shall always be overseen by the private tracker, and user satisfaction is NOT THAT IMPORTANT, after a fashion.

**Comment by Avamander** [comment]
> If you use DHT and such to discover peers, it's cheating, with no doubt. 

After a tracker has shut down, it isn't.

**Comment by Riotous** [comment]
This is a terrible idea. We should not enable anything automatically.

**Comment by Avamander** [comment]
@Riotous Care to elaborate why exactly?

**Comment by AngelFalse** [comment]
> > user satisfaction is NOT THAT IMPORTANT, after a fashion.
> 
> That is the number one priority after the health of the entire BT ecosystem.
> 
> > Rules are the most important thing in the pt network.
> 
> Standards maybe, rules, those are unenforceable anyways.

You ABSOLUTELY don't understand those people playing with PT...
PT is a far more smaller and much more **closed** circle, and their thought differs from what most open torrent seeder think, thus they shall NOT be considered as a part of the whole BT ecosystem.

Also, making a torrent with "private torrent" selected **CHANGED THE HASH VALUE**, even if your(and ONLY YOUR) bt client search for the hash on DHT/PEX, there will be no return, totally **USELESS**.

https://pirates-forum.org/Thread-Torrent-file-to-private-to-public

Believe me when I said they think different, 'cause I use private torrent, too. Usually when our download is finished, we seed for some time to make contribution, but this is not enforced. If you (no offence) decided to "hit and ran", download the whole thing and upload nothing, though we will feel unconfortable, it's totally okay.

But in the world of PT, this kind of thing is NOT OKAY AT ALL. You have to register an account to download. Private tracker **keeps records of what you've downloaded, how much you've downloaded, how much you've uploaded**, and when it found out that you uploaded less that a preset value (mine is 0.4 times os your downloaded volume), it bans your account, and you cannot download anything anymore.

You might have just understand what happened: PT requires everyone to upload to others before they can download more. BT likes to share, whether a peer contribute to others and how much exactly, is very flexible. PT goes another way, forcing everyone to contribute. The most important thing in the PT world is fairness, and it forces all of its members to do the same. 

Open seeders seeds torrent and hopes that, they will be given the wanted files while they leech.
Private seeders seeds torrent because they **have to**, or they won't be able to download anymore.

That's why I've said:

>user satisfaction is NOT THAT IMPORTANT

**Comment by Avamander** [comment]
> Also, making a torrent with "private torrent" selected CHANGED THE HASH VALUE, even if your(and ONLY YOUR) bt client search for the hash on DHT/PEX, there will be no return, totally USELESS.

If there are other people with that privatized torrent they can still exchange blocks.

You still haven't read the suggestion, this should apply after the PT is **dead**, after than any speak about fairness or rules is absolutely silly and unenforceable.

**Comment by AngelFalse** [comment]
>this should apply after the PT is **dead**.

After the PT is dead, most people just **removes all the private torrents** from their BT client software, not everyone will keep those torrent in the list for years before you even enabled DHT/PEX/LPD. In my humble opinion, 99% users won't.

You've considered about user satisfaction, that's great. But have you ever think about whether people will ever **run a private torrent with no speed and no hope for furthur progression**, for **a few year**? No, or, at least, I won't.

>even if your(and **ONLY YOUR**) bt client search for the hash on DHT/PEX, there will be no return, totally USELESS.

Also, as I already said(you might have missed sth., I said **"only your bt client"** for a reason), not all of those PT users uses transmission as their bt client, so if you really think it's a good idea, you'll need to **convince other open-source BT client implementations to change their idea(and their code)** before you can really start leetching from the DHT... network. Or, only transmission users can use DHT to download/upload, and the private torrent's hope for completion will be much smaller.

**Comment by Avamander** [comment]
> After the PT is dead, most people just removes all the private torrents

Because they're effectively DRMed, there's no way to recover currently.

> But have you ever think about whether people will ever run a private torrent with no speed and no hope for furthur progression, for a few year?

**This suggestion concerns DEAD private trackers, not active ones. If your tracker is down for a month and the torrent is that old then any rights on the torrent by the tracker must be banned**

> not all of those PT users uses transmission as their bt client,

Yeah, one client implements it and others will consider, that's how community decisions are made.

**Comment by AngelFalse** [comment]
>If they really want the file, yes.

Yes, of course, **if those files are not available otherwise**. The problem is, mostly there's always **another way to gain access to a similar copy** of the file(for example: movies, music, TV series, pirated games), or sometimes better(for example:mp3 => flac) or worse(for example:8k => 4k) in quality, or, something that have a similar functionality.

In fact, when dealing with a torrent that goes extremely slow(like <10k/s), I just remove the torrent and find another way out(unless assured that this torrent is the only one provided).

Another proposal has just came to my mind: How about we showing a switch on the interface, and let the user decide whether to use DHT... on a private torrent with the server connection down? This switch can only be toggled when using another more complicated mode(like: developer mode? advanced mode? or even: debug mode?), and show a warning before toggling it on.

It's essential to let the user decide everything, right?

**Comment by Avamander** [comment]
> The problem is, mostly there's always another way to gain access to a similar copy of the file

But sometimes there isn't.

> How about we showing a switch on the interface, and let the user decide whether to use DHT... on a private torrent with the server connection down? This switch can only be toggled when using another more complicated mode(like: developer mode? advanced mode? or even: debug mode?), and show a warning before toggling it on.

Yes, this could work. But it would reduce significantly the chance that someone enables it, but it's absolutely step forward I'd also be happy with, maybe a special status code could be used to signify certain torrents could be DHT/PEX/LPD(LSD)-enabled?

**Comment by Riotous** [comment]
How about we stop trying to fix a problem that doesn't exist? Nobody needs this "feature" to be a thing.

**Comment by andreygursky** [comment]
Why not just to introduce a comfort function to transmission "transform torrent to public (use with care)", which would do few steps instantly (which must be done manually now):
- stop torrent
- edit torrent: remove private flag, remove tracker URL(?)
- recalculate hash (and rename .torrent file)
- start torrent

That's it. No dangerous ambiguity with private torrents with enabled DHT.

**Comment by AngelFalse** [comment]
> How about we stop trying to fix a problem that doesn't exist? Nobody needs this "feature" to be a thing.

You're probably right.

>>The problem is, mostly there's always another way to gain access to a similar copy of the file
>But sometimes there isn't.

As I said, MOSTLY.

> * recalculate hash (and rename .torrent file)

Recalculate hash is almost impossible without all of the files. As said before, the private flag changes the hash, and hash algorithm(of, hash function) is a hash algorithm because it is "a function which is infeasible to invert. The only way to recreate the input data from an ideal cryptographic hash function's output is to attempt a brute-force search of possible inputs to see if they produce a match, or use a rainbow table of matched hashes."(quoted from Wikipedia)

Even without Wikipedia, the answer is still clear. Because if a open torrent's hash can be easily derived from its private version's hash, there's no real needs for this question anymore: I can just derive its open version's hash and create a magnet address for everyone else (not in this circle) to download, and pt will be totally meaningless!

**Comment by andreygursky** [comment]
> Recalculate hash is almost impossible without all of the files.

Sure I was not speaking about this case but about the OP how to get both in a comfortable way: private flag drop and still no DHT enabled for private torrents.

**Comment by Avamander** [comment]
@andreygursky Recalculating the hash would mean DHT/PEX/LPD becomes useless which is the entire point of this issue, to make it useful for private torrents. 

There's also no "dangerous ambiguity" when a torrent is old and it's tracker is dead.

@Riotous Speak for yourself.

**Comment by Riotous** [comment]
@Avamander Torrents are made private for a reason. They're never supposed to go to DHT. Ever. This goes against everything torrent clients are made for, and this terrible idea would just get Transmission banned from any private tracker.  What you're asking for is a non-problem. Nobody cares about private torrents being private. If you want to access them, go join a private tracker, make another torrent and set the files free on your own. That's how you're supposed to do it, not suggest a client should just go rouge. 

You should really stop wasting your time and just close this issue. It's a terrible idea and you have no right to ask the devs to make their client go against how every torrent client works.

**Comment by Avamander** [comment]
@Riotous 
> This goes against everything torrent clients are made for, and this terrible idea would just get Transmission banned from any private tracker.

This suggestion would kick in after the tracker is dead, if the tracker is dead it should have zero rights over the torrent.

> What you're asking for is a non-problem.

It's not a non-problem for me.

> That's how you're supposed to do it, not suggest a client should just go rouge.

Again, this suggestion would kick in after the tracker is dead, it's not rogue if there's no "law".

> If you want to access them, go join a private tracker,

In case you don't know, DHT doesn't work on it's own, if you don't have the torrent file you can't properly access the torrent, this means this suggestion only works for those who managed to grab the .torrent from the tracker before it died. And even then, it really really doesn't matter once the tracker itself is dead.

> make another torrent and set the files free on your own

Changing the private flag changes the infohash, that's not the intention. 

> It's a terrible idea and you have no right to ask the devs to make their client go against how every torrent client works.

Past misimplementations must not mean no further improvements. There would actually still zero harm done to any swarms if a peer would just prioritize peers from the tracker before peers from DHT/PEX, but getting that changed is too much work thanks to the FUD of all the private trackers.

Also, I'm well aware how open-source works, I don't have the right but I absolutely can.

**Comment by Riotous** [comment]
@Avamander Go use your silly patches then. It's a waste of time to beg the Transmission devs to make their client go rogue like this. This will never go into the official client. People who use Transmission want their client to function the way it should, not the way somebody with a grudge against private trackers thinks it should. 

@mikedld You may want to end this pointless issue.

**Comment by AngelFalse** [comment]
> I don't have the right **but I absolutely can**.

Can't agree more. Recommendation is always welcomed, though they not all of them will be accepted.

![image](https://user-images.githubusercontent.com/28922095/54928875-9dcd5100-4f4f-11e9-9908-cab1f170074e.png)

Though enable users to start DHT for (any) private torrent is still a very bad idea, and several workaround cheats can be achieved via this by blocking the trackers from being accessed(for example, use with tracker blocked by route table or iptables, I've tried this before, believe me, for experimental purpose, image ahead), and this will force pt admins to block transmission from their users.

You can, however, use the github's function "Fork" to make a modified version of you own, at anytime. But, well, remember to change the client identification, and don't impose like you're a "Transmission 2.94", ok?

@mikedld This issue is ready to be closed now. Thanks for letting us discuss about it here.

**Comment by Avamander** [comment]
@Riotous

> Go use your silly patches then. 

Or I could open an issue to try and get to discuss this properly without any FUD.

>  It's a waste of time to beg the Transmission devs to make their client go rogue like this. 

It's not begging. It's not "rogue" either. 

> not the way somebody with a grudge against private trackers thinks it should.

How can you hold a grudge against something that doesn't exist any longer? Because as I've repeatedly said, this issue talks about allowing enabling DHT/PEX/LPD(LSD) after the tracker is dead and the torrent is old.

@AngelFalse 

> I've tried this before, believe me, for experimental purpose, image ahead)

The inconsistency only occurs though when you actually submit status to a tracker though.  
Another possibility when you have a working PT would be not downloading from non-tracker peers and only upload to them and keep separate count of those numbers.

**Comment by Mlocik97** [comment]
this is worst idea ever... please don't implement it.

**Comment by Avamander** [comment]
> this is worst idea ever... please don't implement it.

@Mlocik97 you could keep it disabled for yourself.

**Comment by marwanpro** [comment]
It should be a thing, to be honest. User should always have a choice to do what he wants with his files. If he wants to deal with DHT cause the tracker is dead, why not ?

**Comment by ckerr** [comment]
# ABSOLUTELY NOT

This would get Transmission banned from every private tracker on the planet
