### ISSUE TITLE
Local Peer Discovery Discovery not working between linux and macOS

### ISSUE THREAD

**Issue by mauron85** [transmission/transmission#889]
First I must say that I really love transmission.

My problem is that it seems that peer discovery on my LAN is not working between macOS and linux.

How to reproduce:

1. Add same magnet link torrent to both linux and macOS box
2. Remove all trackers from linux box (to force it to just use locally discovered peers).
3. On linux box uncheck: PEX, DHT (keep only Local Peer Discovery).
4. monitor with tcpdump multicast address eg:
```
tcpdump -i enp4s1 -vvv -X -s 0 net 239.192.152.143
```

Expected behavior:

Linux box will "discover" macOS box and add it as peer and start downloading from it

Actual behavior:

Boxes don't add them-self as peers.

Version:

Linux: transmission-gtk: 2.92
macOS: Trasmission: 2.94

Side notes:

Running tcpdump on both boxes reveals that unicast discovery packets are send from to another and vice versa. But packets have Host ip of unicast address (not sure if it's packet header or body).

```
14:48:17.747010 IP (tos 0x0, ttl 1, id 48008, offset 0, flags [DF], proto UDP (17), length 147)
    Ikarus.38874 > 239.192.152.143.6771: [udp sum ok] UDP, length 119
	0x0000:  4500 0093 bb88 4000 0111 23cb c0a8 510e  E.....@...#...Q.
	0x0010:  efc0 988f 97da 1a73 007f 2035 4254 2d53  .......s...5BT-S
	0x0020:  4541 5243 4820 2a20 4854 5450 2f31 2e31  EARCH.*.HTTP/1.1
	0x0030:  0d0a 486f 7374 3a20 3233 392e 3139 322e  ..Host:.239.192.
	0x0040:  3135 322e 3134 333a 3637 3731 0d0a 506f  152.143:6771..Po
	0x0050:  7274 3a20 3439 3631 300d 0a49 6e66 6f68  rt:.49610..Infoh
	0x0060:  6173 xxxx xxxx xxxx xxxx xxxx xxxx xxxx  ash:.
	0x0090:  0a0d 0a 
```

**Comment by lps-rocks** [comment]
So.. ```239.192.152.143``` is an administratively scoped multicast address.  - https://en.wikipedia.org/wiki/Multicast_address#Administratively_Scoped_IPv4_Multicast_addresses

Unless your network is set up to properly handle multicasting (some cheap switches don't do it right) - it might not work. WiFi can sometimes cause problems for multicast. Managed network switches without IGMP snooping may not work properly as well. 

Also the packets cannot cross network segmentation boundaries since administratively scoped multicast addresses do not get repeated across network boundaries.

I would suggest running tcpdump on both machines and see if they are seeing the multicast packets from the other device - If they're not then it's something on the network level since you're showing evidence that the packets are leaving the host.

**Comment by ckerr** [comment]
Is this still happening in Transmission 4?

**Comment by Avamander** [comment]
I'd test it but it's difficult because Transmission 4 picks a single interface and does not send LPD messages on any others. Meaning I can't give two transmissions a clean bridge without any interference to test this.

**Comment by purpleidea** [comment]
FWIW I was curious about this and so tested it with two Linux machines running transmission on the same LAN.

Both: Fedora37 / Transmission 4.0.3 (6b0e49bbb2)

Both have LPD enabled. Nothing happens, they never add each other as a peer.

**Comment by jamesr42** [comment]
I believe this is because you have to set the source address explicitly. I have a fix; waiting to see how the contribute process works.

**Comment by tearfur** [comment]
I tested with #5825 between Windows and Linux and it is working as intended.
