### ISSUE TITLE
Transmission MacOS crashes repeatedly during magnet downloads

### ISSUE THREAD

**Issue by smrtlyio** [transmission/transmission#918]
Suddenly the MacOS version of Transmission 2.94 (d8e60ee44f) is crashing after a period of time downloading magnet torrents. 

MacOS X El Capitan 10.11.6
MacPro 2 x 3.46Ghz (6 core)
64Gb 1333Mhz DDR3 Memory
PIA VPN v 1.1.1 (build 02545)
[Transmission Crash Logs.zip](https://github.com/transmission/transmission/files/3244174/Transmission.Crash.Logs.zip)

Crash reports have been sent to Apple.

**Comment by ArchI3Chris** [comment]
I need to bump this, because I have the same problem on ARM with Transmission GTK. And I've had it for months. Currently running version 2.94 too.

It seems, this happens increasingly during other activities on the same hard disk. But actually, transmission doesn't need other activities to just crash on it's own. For example, just running checks on finished downloads will often result in a crash. Even more likely, if you put up a number of files for check.

Of course transmission won't restart on it's own and be inactive until you see it. But even more annoying is that transmission messes up a lot when it crashes. For example, the whole waiting list gets reset and needs to be set every single time. Finished downloads go from finished to paused for no reason. Which makes management a lot more compliated. And not only, but especially in case an error happens during a crash, transmission is not capable of recovering the according download that is now listed in the error section. You have to delete it, find the download again and start over. Another problem I've noticed is, that when transmission crashes, the progress of downloads gets messed up. Ever since transmission started crashing a lot, I have to check every single download after it's finished. Because many of them turn out to be incomplete. This only happens in case transmission has crashes while the download was listed. Small files that are downloaded start to finish, don't usually show the same problem when transmission doesn't crash during the download.

But to top it all off, relisting the unfinished downloads, they stay in the directory with the finished downloads. Aside from the downloads that go to the paused section getting realigned when unfinished and now don't get finished and you need to search your whole paused list to find the unfinished download again. So, the crash literally messes up everything. The waiting list, the downloads, the error files, the progress, management of finished vs. unfinished...

The crashes have reached a point where it gets really annoying. Meanwhile, transmission crashes almost every single day at least once. Sometimes 5 times a day...

**Comment by ckerr** [comment]
Thanks for reporting this. Since so much time has passed since this report, could you please try running with a nightly build to see if the problem persists?

**Comment by ckerr** [comment]
Closing due to lack of response
