### ISSUE TITLE
Download button on web UI

### ISSUE THREAD

**Issue by nickkelley42** [transmission/transmission#940]
I have a seedbox that I control using the web UI. I retrieve downloaded files using ftp from my PC to my seedbox. This works for me but there are other users on my network who aren't as comfortable with tools like sftp, so I'm working on adding a "download" button in the web UI.

Is there any ongoing work on this, or has this been considered in the past? Are there any pitfalls or reasons not to do this that I haven't thought of? I'd be interested in any thoughts people have on this.

**Comment by nickkelley42** [comment]
After looking around the bug tracker I found [ticket 6138](https://trac.transmissionbt.com/ticket/6138) which seems to be exactly what I'm talking about.

**Comment by ckerr** [comment]
I generally feel like this is more appropriate for dedicated web server software, because there is an endless rabbit hole that this would go down -- could we support wget / curl, could we download the entire torrent in a zipfile, how can I add remote access for my friends to files from tracker X but not from Y, etc, etc. -- these are all valid  ideas, and they are all already things that can be done with off-the-shelf web servers or ftp servers.

**Comment by nickkelley42** [comment]
I think that makes sense. After delving into it for a bit, I found that there were lots of rabbit holes/design decisions to be made, and I found it was easier to either:

* Automatically copy completed downloads to a directory covered by a server, or
* Configure a server to point to the download directory. (This option came with some challenges around incomplete downloads, so I opted for the first option.)

My apologies for leaving this open for so long - do you prefer I close it, or would you like to keep it open for community input?

**Comment by ckerr** [comment]
> My apologies for leaving this open for so long - do you prefer I close it, or would you like to keep it open for community input?

You're too polite :smile:  I'm the one who should apologize for not triaging this ticket (much) sooner. I appreciate your response! 

Generally if I would accept a contributor's PR I leave the ticket open, but in this case since it's such an open-ended feature I think it makes more sense to close it.

**Comment by killemov** [comment]
@nickkelley42 FYI [Shift](https://github.com/killemov/Shift) supports downloading the payload (files) of a torrent by configuring a base URL to prepend the files. You still need to configure your HTTP/FTP/... server for the actual serving of the files.
