### ISSUE TITLE
[Feature Request] Only autostart at login if seeding or downloading, otherwise, disable

### ISSUE THREAD

**Issue by BeatLink** [transmission/transmission#945]

**Comment by ckerr** [comment]
This is one of those features that absolutely is valid for a group of people, but most people will never use it. If the project said "yes" to every feature request like this, the Settings / Preferences dialog would be 100 pages long, full of features that all broke each other because they made the code so complex. And the maintainers would all be dead because their heads exploded :skull: :boom: 

Happily, this is something that would be reasonably doable in a 3rd party script that talked to Transmission via RPC. If you feel strongly about this feature, I'd suggest either using one of the RPC libraries in your scripting language of choice, or perhaps having a script invoke `transmission-remote` to do the work.
