### ISSUE TITLE
Hardcoded permission of settings.json

### ISSUE THREAD

**Issue by Hakun1n** [transmission/transmission#958]
Hi!

I am running Transmission on FreeBSD and i have custom script which fetches some values from settings.json. The script is called externally from another system over SSH via its own (service) user. File settings.json has "700" by default so it can not be read by other users even if i add them to "Transmission" user group. I have to chmod the settings file to 740 in order to do so.

Problem is that if i change the permission it gets reset back to 700 every time the Transmission or server restarts. Transmission user itself has umask 027 so other files are generatet with 750 permissions. Also i've checked demon service config file (/etc/rc.d/transmission) and there is nothing related to settings.json. Therefore i assume the 700 file permission is hard-coded in the demon binary which re-generates the settings.json file upon service stop.

Is there anything to make this a bit more user-friendy? I understand that the config file contains hashed password but the 700 is too restrictive basically for nothing.

It could be handled by various approaches:
- Do not force the permission and respect the user UMASK
- Parameter in daemon file to define with which flags the file is generated
- Check the current file flags before re-generating the file and set up the same.

Thank you in advance for your feedback.

Alex

**Comment by sio** [comment]
Did you stop the daemon before changing permissions? It's a known quirk of Transmission that any changes made to settings.json while daemon is running will be lost upon restart. I'm not sure that that includes file permissions and I'm not at computer right now, so I couldn't check.

**Comment by Hakun1n** [comment]
Yes, i stopped the service, changed the permission and started. It gets changed back to 700 upon next restart :/

**Comment by sio** [comment]
Oh, so it's being set to 600, not 700 - that would be very weird :)

I've tried to locate the place where permissions are being set, and if I'm not mistaken it's `mkstemp`: https://github.com/transmission/transmission/blob/5a5fe7d7fe22e78af82c6cf8b32ed6894813e932/libtransmission/file-posix.c#L528

The chain of function calls is: `tr_sessionSaveSettings -> tr_variantToFile -> tr_sys_file_open_temp -> mkstemp`. [It is a POSIX function](http://man7.org/linux/man-pages/man3/mkstemp.3.html) that always produces a file with permissions set to 600. It seems that Transmission uses the resulting file and never bothers about its permissions.

I agree that it would be sensible for `tr_variantToFile` to restore previous permissions value when overwriting the file. If no one fixes this by that time, I'll maybe take a shot at it and submit a PR after 3.00 release.

**Comment by Hakun1n** [comment]
@sio My mistake regarding the 700, sorry :] 

And thanks a ton about so prompt response and possible fix!

**Comment by pF-arQon** [comment]
3.00 still has this problem, and I don't seem to be able to find the commit that closed this (or anything with #958 in it at all, though that may just be github's search). I also don't see any relevant changes in the file-posix source linked above around the time this was closed. Can someone please point me at it so I can investigate?

My motivation is that the excessive restrictions make it impossible to even backup the settings file without running as root, which is obviously a bit too much of a sledgehammer/nut scenario. Since it's running on a Pi booted from an SD card, backups of system files are unfortunately a fairly critical thing to have - especially when they contain things like rpc-whitelist.

Thanks.

**Comment by sio** [comment]
As far as I understand, no changes to temp file handling were made. Call path is now `tr_sessionSaveSettings -> tr_variant_serde::json().to_file -> tr_file_save -> tr_sys_file_open_temp -> mkstemp` and it should still result in 600 permissions after any settings.json modifications. It's possible that I've missed something while reading the code today (I did not do any test runs), but it appears that this issue was closed by mistake.

Since neither me nor you can reopen this one, I think you should just post a new issue. Test with a newer transmission release though - 3.00 was released two years prior to closing this issue and it could not have possibly contained any fix for this.

On a side note, why do you need root permissions for backing up mode 600 files? They should be readable by their owner, and you can execute backup script as that user as a workaround. Running transmission as root is not a good idea from a security point of view.
