### ISSUE TITLE
Silently switch to hardened SHA1

### ISSUE THREAD

**Issue by SoniEx2** [transmission/transmission#976]
Hardened SHA1 is mostly backwards-compatible, so this shouldn't be much of an issue. (2^-90 probability of breaking compatibility with any given hash. you only have a handful on a torrent, it'll be fine.)

**Comment by ckerr** [comment]
I guess my question is, it a torrent client switched to hardened SHA1, does that cause issues when communicating with other peers that aren't using it?

**Comment by SoniEx2** [comment]
yes, with a very low probability. it's good enough tho.

**Comment by ckerr** [comment]
I 100% agree with the usefulness of avoiding torrent hash collisions. Since the BitTorrent spec version 2 uses SHA2-256, and is the standard, IMO that is the right way of solving this problem.

The issue to track BitTorrent spec version 2 is https://github.com/transmission/transmission/issues/458

I'm closing this issue since 458 will be the fix, but I appreciate the suggestion. It's a good idea.
